### ISSUE TITLE
Improve PropertyGrid for Nested Cases

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#123]
As described [here](http://forum.adamslair.net/viewtopic.php?f=4&t=288), editing heavily nested object hierarchies doesn't really look nice in the PropertyGrid. Maybe there are ways to improve this?

![Nested Objects](http://forum.adamslair.net/download/file.php?id=45)

**Comment by ilexp** [comment]
Closing this as part of the regular issue cleanup, as the situation has been improved and there currently seems to be a lack of need and direction to this issue - making it a bit of an aimless endeavor. Re-open when that changes.

(Note that a general improvement to list editors in the property grid is kind of a different matter that would deserve its own issue in any case, so closing this is not a statement about that.)
