### ISSUE TITLE
Auto-Compile Game Code after Package Update

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#126]
As mentioned [here](http://forum.adamslair.net/viewtopic.php?f=16&t=294), it would be really nice if the Duality Package Manager would also compile local game plugins after updating packages.

**Comment by hsnabn** [comment]
Wow, I feel like digging up old issues today.  

Just chipping in what I think: it probably wouldn't be a good idea. The package update could introduce breaking changes or incompatibilities, so wouldn't it basically be an exercise in futility to try to compile the code in such cases? The user would probably be better off manually compiling the code, right?

**Comment by ilexp** [comment]
In these cases, the editor could just tell the user that he needs to fix his code - which might be better than a runtime failure when trying to run outdated Assemblies.

Still, this is probably more or less a half-arguable, half-nice2have feature, depending on how it would be executed.

**Comment by ilexp** [comment]
Closing this, because it seems a bit questionable and a lot like a nice2have feature.
