### ISSUE TITLE
Option to not load OpenAl

### ISSUE THREAD

**Issue by Andrea** [AdamsLair/duality#127]
Hi there

This is super low priority but, I though I would document it anyway. (also it might be there already and in that case it would be great to know)

It is always possible that people will be using something like FMod or WWise for sound, it would be nice if there was a configuration option so that openAL is not used in Duality .
I am sure that adds some extra loading and starting time. 

Seems kind of trivial to not create the SoundDevice on DualityApp.OnInt() but a little bit more to check that is not used if the device is not there :D

**Comment by AdamsLair** [comment]
This issue has been superseded by the [OpenTK Abstraction Layer](https://github.com/AdamsLair/duality/issues/184) and will be implemented as part of that. Closing this.
