### ISSUE TITLE
Automatic Viewport Scaling to Target Size / Resolution

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#151]
## Problem:
- Certain games are designed to use a fixed resolution.
- The resolution on a user device might be entirely different.
## Solution:
- Similar to this: https://github.com/BraveSirAndrew/duality/commit/2cb48ed12a585e39168ed3f0749e0284ecd45248
- A Camera should allow to specify a NominalViewportSize and optional viewport scaling.
- When active, viewport scaling should scale everything during rendering in order to display the exact same screen area, just "bigger" or "smaller", while also maintaining aspect ratio.
  - This **should** apply when rendering from world to screen. (Nominal fit screen)
  - This **should** apply when rendering from world to texture. (Nominal fit texture)
  - This **should** apply when rendering from texture to screen. (Texture fit screen)
  - This **should not** apply when rendering from texture to texture, as these are internal renderpasses that are likely configured carefully and should not be disturbed.
- Everything outside the nominal viewport (but inside the target rect) should be black.

**Comment by ilexp** [comment]
This has been addressed as part of the v3.0 RenderSetup feature. 

There is now an option to specify a world view size that will represent the viewports "world space" size regardless of rendering resolution. When the target view aspect ratio doesn't match with the actual rendered aspect ratio, the rendered view will be fitted into the available space.
