### ISSUE TITLE
Changing Time.TimeScale affecting movement in Editor

### ISSUE THREAD

**Issue by eriksk** [AdamsLair/duality#158]
### Steps to reproduce
1. Create a component that sets Time.TimeScale to something say 3.5f. 

### Expected Result
Change doesn't affect editor at all.

### Actual Result
Moving in editor is really fast, also zooming and rotating becomes quick and stiff.

**Comment by AdamsLair** [comment]
Thanks for reporting. Will look into this!

**Comment by AdamsLair** [comment]
Should be fixed in source and updated CamView package now. Closing this!
