### ISSUE TITLE
Consider Moving Editor away from WinForms?

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#159]
**Original Title:** Consider Moving Editor to WPF?

As the title says - this should be considered in the future. Not an actual plan, but a rough idea for long term development.

Pro:

- Getting rid of the decade old WinForms cruft.
- Shiny new UI with styling capabilities.
- Fully hardware accelerated rendering performance.
- DPI independent rendering.
- XAML and Data Binding seems really, really neat.

Con:

- Rewriting all editor UI code.
- Rewriting the custom PropertyGrid.
- Searching WPF equivalents for Docking, fast / virtualized TreeViews, etc.
- Fully hardware accelerated rendering - does it interact with OpenGL performance, and can it host OpenTK GLControls? Is there any OpenTK support?
- Startup performance.
- "Never change a running system".
- A big change that isn't really necessary to advance Duality.

Not sure whether this is a good idea at all. So far it doesn't look very good, but opinions are welcome.

**Comment by Andrea** [comment]
Hi Adam

I think the only good reason to do a move on the editor code would be to make it cross platform, and WPF so far does not support that.
GTK# I think it's what is used for the editor for MonoDevelp and Xamarin Studio, surely a bit behind when it comes to features, however I maybe it's worth checking out.
When it comes to the future, I would think deploying to multiple platforms is higher on the list of priorities, but perhaps that is just me.

**Comment by AdamsLair** [comment]
Allright, WPF is probably a dumb idea (again). *If* porting the editor to a different UI framework, then might as well use something platform independent. Or create a custom ingame UI framework, so Duality can render its own editor. Or something else.

Maybe there is already a great ingame UI framework based on OpenGL, free and open source, which could just be integrated? Cool thing is, it would mean having the exact same UI system for games and the editor. Even cooler would be if UI was separated properly with logic and presentation, like when using XAML or HTML5 + CSS. Problems here would be:

- High-Performance requirements
- "Crash-proofness"
- Free / compatible license would be required, ideally Open Source
- Logic backend required to be C#
- Library required to be 100% managed code for portability, since it's also used ingame
- Ideally super-lightweight
- Requiring the means to define (or use predefined) complex and high-performance Controls like WeifenLuo Docking, TreeView
- Requiring the means to define custom high-performance Controls like the PropertyGrid

Even when identifying such a framework though, this would require *loads* of work. Kind of a big deal and if anything more of a very-long-term goal.

**Comment by AdamsLair** [comment]
Closing this after making up my mind. Will pop up again anyway, if this should become viable at some point.
