### ISSUE TITLE
Copy / Paste for GameObjects and Components

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#16]
- Instead of the current Clone functionality, implement a proper Cut / Copy / Paste
- Use the Clipboard
- Apply to SceneView and CamView
- Use Case: Copy GameObject and Paste it somewhere else (Hierarchially)
- Use Case: Copy Component and Paste it into a different GameObject
- ...

**Comment by ilexp** [comment]
Done by @deanljohnson. Closing this.
