### ISSUE TITLE
Investigate OpenTK Gamepad Support

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#160]
Due to [Gamepad issues](http://forum.adamslair.net/viewtopic.php?f=4&t=367), which are likely fixed in the newest OpenTK version, an upgrade would be a good idea.

**Comment by AdamsLair** [comment]
[Apparently](http://forum.adamslair.net/viewtopic.php?p=1678#p1678), they're not "likely" fixed in the newest version. But there may still be hope. Investigate this.

**Comment by AdamsLair** [comment]
**ToDo:** Put together a demo program with the new OpenTK version to let everyone test their controllers and gather data.

**Comment by eriksk** [comment]
Sign me up for testing. I've got a couple of weird cheap controllers.

**Comment by AdamsLair** [comment]
Updated the OpenTK Version in the wake of the v2.0 update. Time will tell whether gamepad issues still remain.
