### ISSUE TITLE
PlaneRenderer Component

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#161]
Displaying a partially-infinite, looping, scrolling background is a recurring problem. Provide a specialized standard Component for this along with the SpriteRenderer.
## Properties
- SharedMaterial
- CustomMaterial
- Offset
- AlignToPixelGrid
- ColorTint
- VisibilityGroup
- Rect: Offset and Measurements of the non-infinite sides
- InfiniteDirection: None, Horizontal, Vertical, Both
- ScrollOffset: Vector2 describing the UV offset in [0.0 ... 1.0] at unscaled Z
## Behavior
- Non-Infinite sides always "stretch" instead of "repeating".
- Should properly use Z sorting and parallax tranformation.
- Should properly interact with rotated Camera and rotated objects.

This issue requires further discussion and concept work before implementing a solution.

**Comment by SirePi** [comment]
Implemented in
https://github.com/SirePi/duality-companion/blob/a30b44441d44c563da1615b2689a8f3ea5719739/Source/Code/Companion/Drawing/PlaneRenderer.cs

**Comment by Barsonax** [comment]
Is this issue done or not? Its not clear to me.

**Comment by ilexp** [comment]
I'd say it counts as done, as it's implemented in the community plugin and I don't currently see a strong incentive to have one in core as well. Open to re-visit this at some point in the future.
