### ISSUE TITLE
OpenTK Loads SDL From PATH (Editor Crash)

### ISSUE THREAD

**Issue by ProtectedMode** [AdamsLair/duality#164]
After seeing Duality and reading the getting started guide, I decided to download it and try it out. The first time starting `DualityEditor.exe` it seemingly succeeds with download some packages, but then nothing happens. Upon restarting it, a splash screen is shown for less than half a second, a process is started, and then the splash screen disappears but the process remains active.

I've the .net framework installed and am using VS Express 2013 for desktop.

**Comment by AdamsLair** [comment]
It's very hard to say anything concrete based only on the information you provided. Can you upload your `logfile_editor.txt` somewhere?

**Comment by ProtectedMode** [comment]
I've uploaded the log at [pastebin](http://pastebin.com/bkgGVV3V). It seems to be the same issue as #155. I had a SDL2.dll in my path, but after renaming it, everything worked. Is this intended?

**Comment by AdamsLair** [comment]
> Is this intended?

Well, intended is kind of the wrong word. It is expected behavior though, the SDL2 backend is not officially supported, although you can use it as a drop-in when releasing your game.

How did the SDL library get in there though? Did you copy it there yourself? If not, then this would require some investigation.

**Comment by ProtectedMode** [comment]
It wasn't in the working directory of Duality, but I had installed it myself in a directory listed in the PATH variable, to get something else working. I understand it would load it from the current directory, but loading from the environment is a bit annoying, but I guess most people won't have libraries installed in their PATH...

**Comment by AdamsLair** [comment]
Ah, I see. That doesn't sound very intuitive. Will take a look if I can prevent OpenTK from loading SDL from anywhere except the current folder.
