### ISSUE TITLE
Trigger component

### ISSUE THREAD

**Issue by Deviver** [AdamsLair/duality#171]
In my game I have lots of situations where I need to use triggers. For example if a player goes through a trigger, then some events happen. I think that would be a really nice feature to have, especially for platformers

**Comment by AdamsLair** [comment]
Definitely! However, this is not a core feature, but something that can easily be added with a third-party plugin. I'll leave this one to the community. :)

**Comment by AdamsLair** [comment]
By the way, if you'd like to, feel free to share your code snippets for triggers in the [Tutorials an HowTo](http://forum.adamslair.net/viewforum.php?f=17) section of the forum. Maybe others will find this helpful as well, or could point out how to improve or generalize it.
