### ISSUE TITLE
Available Gamepads aren't enumerated correctly

### ISSUE THREAD

**Issue by BraveSirAndrew** [AdamsLair/duality#176]
Hello

It looks like the GamepadInputCollection.AddGlobalDevices method has a bug in it when the player's gamepad is not the first device. It stops looking for devices after the first missing device, so if my gamepad is device 2 and nothing is plugged in on device one, I'll have no valid gamepads:(

Suggest something like the following instead, where the number of supported devices is either hard coded, or exposed as user or application data:

    public void AddGlobalDevices()
    {
        for (var i = 0; i < MaxSupportedDevices; i++)
        {
            GlobalGamepadInputSource gamepad = new GlobalGamepadInputSource(i);
            gamepad.UpdateState();
            if (!gamepad.IsAvailable) continue;

            this.AddSource(gamepad);
        }
    }

**Comment by AdamsLair** [comment]
I'm confused - how is it possible to have a device one, which isn't connected? Wouldn't device two become device one then?

What would I need to do to reproduce this?

**Comment by AdamsLair** [comment]
In any case, I have committed a fix for this, similar to the one you suggested. :) I'm now checking a minimum of eight joysticks and gamepads, but more as long as they're reporting to be available.

**Comment by BraveSirAndrew** [comment]
Oops, sorry. Quite right, forgot steps to reproduce. Its quite easy, even with one gamepad.

* Start Dualitor with your gamepad plugged in and registered as controller 1.
* Unplug your controller while Dualitor is running then plug it back in. On my system at least, this causes the controller to be registered as controller two.
* Restart Dualitor and see that it doesn't add controller two to the list of devices

Anyway, you've fixed it already, so its moot:) I've also seen some devices, Razor devices in particular, register themselves in Windows as gamepads but not pass the IsAvailable check in Dualitor, which answers how its possible to have a device one which isn't connected:)
