### ISSUE TITLE
Dual monitor crash

### ISSUE THREAD

**Issue by Deviver** [AdamsLair/duality#177]
I think I've stumbled across a bug. The problem is that when I have a Game View open on my second monitor, and then restart Duality, it crashes. It works fine when I have only 1 monitor enabled.

**Comment by AdamsLair** [comment]
Can you upload your editor logfile somewhere? I'm going to need something to investigate this :)

**Comment by Deviver** [comment]
http://pastebin.com/FcqDbi6D didn't give me a clue on what happened

**Comment by AdamsLair** [comment]
There doesn't appear to be an exception thrown by Duality. Can you rule out driver or hardware issues? Do you have a second device you can test this on?

Can someone else reproduce this with a local Duality build, step through it and report where it fails? The problem is, I do not have the hardware to test and reproduce this right now, and without callstack in the logfile, this is going to be really hard.

**Comment by Andrea** [comment]
This is the setup I use here for over a year, and many of us at the office
too without trouble , maybe consider other reasons ?

Andrea
www.roundcrisis.com

**Comment by SirePi** [comment]
Same here.. dual screen and never an issue because of that.

@Deviver what kind of crash are you talking about? The usual "[program] has stopped working" window or something else? in the first case, can you get the error details from the "View problem details" panel and post them?

**Comment by Deviver** [comment]
@SirePi It's a usual "[program] has stopped working", also when i press close the program, the exact same window appears for the second time with the exact same error. It is related to a gpu driver as I can see from the error http://pastebin.com/bnbNkV5R

**Comment by Deviver** [comment]
@AdamsLair Unfortunately I don't have a second computer to test this

**Comment by SirePi** [comment]
@Deviver can this be related? http://superuser.com/questions/684779/adobe-photoshop-cs6-crashes-dual-vga

Do you have two different video cards where each outputs to a different screen?

**Comment by Deviver** [comment]
@SirePi Yes, I think that is the problem, because the second monitor is connected to the Intel HD.

**Comment by AdamsLair** [comment]
So this mystery is solved then? Thanks everyone :D
