### ISSUE TITLE
Sandbox bug

### ISSUE THREAD

**Issue by Deviver** [AdamsLair/duality#179]
That one is a really annoying bug. In my game new objects are generated from prefabs every 2 seconds. It works ok in sandbox, but when I press stop, objects still continue to be generated. Eventually it will lead Dualitor to crash. because there will be far too many game objects.

**Comment by AdamsLair** [comment]
You mean, there are new GameObjects spawning from Prefabs while in editing mode?

I would assume that this is likely not a Sandbox bug, or it would have been all over the place for a long time. There were no recent changes to any of the related systems, so my guess would be that this is an issue in your local game plugin. Maybe this is related to those weird physics crashes on your machine as well?

If this should indeed be a bug, I'll need a description on how to reproduce this in a fresh Duality install, but to be honest, I think that this being a game-related issue is more likely.

**Comment by AdamsLair** [comment]
(Feel free to open up a new forum topic in case you need help on this. Just closed it because I doubt it's an actual issue with Duality in this specific case.)
