### ISSUE TITLE
Creating new project from "Current Project" results in errors on build.

### ISSUE THREAD

**Issue by RabbitB** [AdamsLair/duality#180]
Create a new project and select "Current Project" as the project source option; when you first build the new project, you'll encounter two related errors (note that this is the only way to generate the error; it doesn't occur if you create a new project by selecting "Empty Project").

* `Error 1`
    `The best overloaded method match for 'Duality.ReflectionHelper.ResolveType(string, System.Reflection.MethodInfo)' has some invalid arguments`
    `File: ...\EmptyTest\Source\Code\CorePlugin\Properties\ErrorHandlers.cs`
    `Line: 25 Col: 38`
    `Project: CorePlugin`

* `Error 2`
    `Argument 2: cannot convert from 'bool' to 'System.Reflection.MethodInfo'`
    `File: ...\EmptyTest\Source\Code\CorePlugin\Properties\ErrorHandlers.cs`
    `Line: 25 Col: 80`
    `Project: CorePlugin`

I have tested this using Duality version (Core: 1.6.2; Editor: 1.3.12 -- A fresh download), compiled against .NET 4.0 in VS 2013.

This doesn't appear to be a show stopping bug, as I've gotten it to compile and run by simply deleting the erroneous `false` argument in the call to ReflectionHelper.ResolveType. I haven't actually done any testing past making sure the editor launches properly, so this may cause issues down the road.

**Comment by AdamsLair** [comment]
Thanks for reporting this. (And for doing some basic research in advance - I already have an idea what could be causing this thanks to your description!) Will look into it as soon as I get around to.

**Comment by AdamsLair** [comment]
Confirmed, Fixed and Committed. You should find an update in the package manager that reflects this.
