### ISSUE TITLE
Components on inactive game objects can be initialized twice 

### ISSUE THREAD

**Issue by BraveSirAndrew** [AdamsLair/duality#181]
Hello

I don't think this is expected behaviour. To reproduce:

1. Programatically add an inactive game object to the current scene
2. Notice that all components of the game object that implement ICmpInitializable have their OnInit methods called.
3. Now activate the game object. All initializable components will be initialized again.

I guess the solution to this, if its not intended behaviour, is to check whether the new game object is active before calling OnActivate in Scene.OnGameObjectAdded. We probably won't make that change locally as we can't be 100% sure what else it will break.

**Comment by AdamsLair** [comment]
Thanks for reporting this.

I was able to reproduce this behavior and fixed this in my recent commit. There is also a new test to check for this behavior and similar cases. 

As for accidentally breaking things, the ICmpInitializable interface is tested quite thoroughly, so we're [relatively](https://xkcd.com/1172/) safe - but in your specific case, I would probably not touch it until after release. Might be not worth it :)
