### ISSUE TITLE
Prefab ChangeLists Always Clone

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#191]
- When applying a PrefabLinks change list entries, the value of each entry is cloned before assigning it.
- This is correct for container classes and similar, but not for references.
- It works when the object in question is not the root value.
  - A ```GameObject``` property fails by copying the referenced GameObject.
  - A ```List<GameObject>``` property succeeds, because copying the list is correct and the cloning system automatically decides not to clone each GameObject reference inside.
- **Solution:** Let the cloning system decide how to handle the root object as well in this case. It clearly has a better idea of what to do than the current PrefabLink apply code.

**Comment by ilexp** [comment]
Fixed.
