### ISSUE TITLE
Disable SDL2 Support in OpenTK Editor Backend

### ISSUE THREAD

**Issue by orthoxerox** [AdamsLair/duality#192]
```System.AccessViolationException was unhandled
Message: An unhandled exception of type 'System.AccessViolationException' occurred in OpenTK.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.```

After downloading the packages, Duality Editor crashes on startup somewhere in `Sdl2GraphicsContext.cs` with the exception shown above. I'm trying to run it on Surface Pro 3, Win 8.1 Pro 64.

**Comment by orthoxerox** [comment]
I've compiled it from sources (branch 1.x), and it crashes now in `DualityEditorApp.cs`, line `mainContextControl.MakeCurrent();`

**Comment by AdamsLair** [comment]
This is a known issue for users who have added SDL2 binaries to their PATH. OpenTK automatically switches to an SDL2 backend when it is able to locate its binaries, and unfortunately, the SDL2 backend doesn't support embedding an OpenGL view within a WinForms application such as the editor.

To work around this, remove SDL2 from your PATH. Sorry for the inconvenience.

@thefiddler This issue has popped up several times in the past months - is there a way to tell OpenTK not to search for SDL2? It wouldn't be an issue if it didn't use PATHed binaries, but apparently that's just how DllImport works?

**Comment by orthoxerox** [comment]
Yep, that was mingw in my PATH, thank you.

**Comment by AdamsLair** [comment]
Requested an OpenTK feature for disabling SDL2 support [here](https://github.com/opentk/opentk/issues/266)

**Comment by AdamsLair** [comment]
As stated in the OpenTK issue linked above, there apparently is a way to not use SDL2 even if it can be found. Use that option in the editor backend of OpenTK.

**Comment by AdamsLair** [comment]
Done.
