### ISSUE TITLE
Create an environment variable that sets Duality's installation path

### ISSUE THREAD

**Issue by RockyTV** [AdamsLair/duality#196]
When you run Duality for the first time in your computer, it should add an environment variable for later use. The value of this variable would be the directory where you have extracted Duality.

**Comment by AdamsLair** [comment]
This is a contradiction to Duality's decentralized concept and I think that it wouldn't work well with multiple Duality installations or projects on the same machine. 

As you probably know, the core idea is that each game or project has its own Duality "installation", locally within its folder, to prevent version conflicts entirely and allow customized binaries and plugin configurations for each project. However, moving more towards a centralized approach with one "main" Duality installation would kind of "get in the way" of this. 

I'm really glad that Duality in its current state needs neither an actual installer, nor interferes with any system settings - this is a big plus in my opinion! I'd rather not change this explicitly by setting PATH values :)

So.. while it can be useful for you to set this environment variable yourself, it is not something that I think would be a good idea as a default behavior.
