### ISSUE TITLE
Hidden GameObjects and Components via Attribute

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#204]
As described [here](http://forum.adamslair.net/viewtopic.php?p=2875#p2875), users might want to hide certain objects from the Scene tree view and similar views. Consider implementing this.

**Comment by SirePi** [comment]
To avoid the issue described in @AdamsLair answer to the post, instead of having a specific Debug mode maybe it could be easier to implement a "Show Hidden objects" button as well.

**Comment by AdamsLair** [comment]
Things to do:

1. Add a new EditorHintFlag for objects that are considered internal and thus won't be displayed in editor views by default, such as the Scene View or Project View.
2. Have Scene View and Project View check for this.
  - Potentially by adding a new bool property to their tree view items, which states whether it's an internal object.
  - Then, filter the displayed items accordingly.
3. Add a setting to these views which allows to toggle the display of internal / hidden objects. 
  - Potentially something like the "debug mode" of the already existing PropertyGrid.
  - Make it a neat toggle button in their toolbar and add an icon.
  - The toggle state should also be serialized.

**Comment by RockyTV** [comment]
Hey Adam! I'm trying to give it a go, but I can't figure out how to apply two filters at the same time on the SceneView. Here is my actual code:

https://github.com/RockyTV/duality/commit/56f197e493629750c5e4b6495dc14dda46727cf4

For me, it should work, but it simply does not. Is there anything wrong?

**Comment by AdamsLair** [comment]
Could be a logic issue. Set a breakpoint in the line that determines the visibility state of an item (isVisible = ...) and check what happens, maybe split it into more lines to see the details of it.

Also, the code in `objectModel_IsNodeVisible` is only executed as long as the method is assigned to the tree models `NodeFilter` [here](https://github.com/AdamsLair/duality/blob/master/DualityEditorPlugins/SceneView/Modules/SceneView.cs#L244), which is only the case as long as you've entered text into the filter box of the Scene View.

**Comment by RockyTV** [comment]
After messing around for a while, and fixing the breakpoint (it was not being hit), I figured that the current code to get the EditorHintFlagsAttribute does not work on objectModel_IsNodeVisible:
`EditorHintFlagsAttribute editorHintFlags = obj.GetType().GetAttributesCached<EditorHintFlagsAttribute>().FirstOrDefault();`

That might be the reason why hidden objects were shown even when the button wasn't checked.

**Comment by AdamsLair** [comment]
That method should work as expected though, it's comparatively well tested. Anyway, I'll take a look when I get around to it.

**Comment by RockyTV** [comment]
The problem I've found is to cast object to Component, or Node, or anything else. It is quite tricky, and if we figure out how to get this working on the SceneView, we can use the same code on ProjectView (IMO).

**Comment by ilexp** [comment]
> Could we just use the existing MemberFlags.Invisible? It is already used in a few places (CamView and SceneView for example) to hide types.

I'm not sure the `EditorHintFlags` attribute is allowed to be applied to a type, but if it is, we should definitely re-use that flag.

> What would Project View display that could be filtered this way? I don't see how this attribute could be applied to GameObjects/Prefabs, and I 

Good point. Since a per-type attribute can only be applied to component types, there is no way to hide an entire GameObject. The current proposal on how to address this issue may already fall flat there. Do you have an idea how to address this instead?

> If the display of hidden items is turned on, should text filtering still be applied? I'm thinking yes but just want to check.

Yep, it should still be applied independently 👍 

> Also, how does this setting interact with the debug mode of the Object Inspector? I would think that hidden components would be hidden from the inspector unless debug mode is active, but what is kind of annoying then is that the user has two options they must toggle to reveal a component completely. It'd be nice if it was one option that affected both displays, but I am not sure how we would unify those right now.

Hiding an object prevents it from being selected - however, once it _is_ selected, I think there should be no difference whether it is hidden or not. 

----

Overall, I must say I'm no longer sure a hide option would be an overall win. There are very very few objects where hiding them is good for the user, and even for them, it removes a bit of potential knowledge and understanding, replacing it with "magic". This may not be a good thing to do in the first place - so unless there is a specific use case that we would enable with implementing this feature, I'd probably close this issue instead and let it rest.

Thoughts on this?

**Comment by ilexp** [comment]
> That being said, I do wonder if it is potentially more trouble than it is worth. It can be confusing and it is a very minor convenience generally.

As they say, it's easier to add new features than remove existing ones. I'll close this for now. Would be willing to re-open if it comes up again with a solid case.

> Note that getting this to work for components has been very little code (~30 lines) and I have it working in the scene view and in the object inspector.

If you have a partially working solution, feel free to link the commit or branch so we can get a quick start should we decide to pick this up again at some point.

**Comment by deanljohnson** [comment]
Partial implementation [here](https://github.com/deanljohnson/duality/tree/hidden-components). Components decorated with `[EditorHintFlags(MemberFlags.Invisible)]` are not shown in the scene view or the inspector unless "Show Hidden Items" or "debug mode" are toggled in those views.
