### ISSUE TITLE
Create v2.0 NuGet Packages

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#206]
- As the title says - for the upcoming release, all NuGet packages need to be updated with proper dependencies and updated semantic version numbers. 
  - A full set is required, including all core, editor and sample packages.
  - Package specs for backend plugins need to be created.
  - Backend plugins need to be added to the default plugin list to download.
- The final package setup needs to be tested locally, with a local repo.
  - Does a fresh install work?
  - From a v1.x version, does the package manager properly display warnings when trying to update? Is it clear that an update would introduce breaking changes and is likely not a good idea for an existing project without preparation?
  - When doing an update anyway, is the editor fully operable, so backend plugins can be installed later?

**Comment by AdamsLair** [comment]
**Progress:**

- Updated all AssemblyInfo and NuGet package specs to a solid v2.0 lineup.

**ToDo:**

- The final package setup needs to be tested locally, with a local repo.
  - Does a fresh install work?
  - From a v1.x version, does the package manager properly display warnings when trying to update? Is it clear that an update would introduce breaking changes and is likely not a good idea for an existing project without preparation?
  - When doing an update anyway, is the editor fully operable, so backend plugins can be installed later?

**Comment by ilexp** [comment]
**Progress:**

- Tested the build process.
  - Works as expected now.
- Tested a fresh Duality v2.0 install.
  - Works as expected now.
- Tested install and functionality of all samples projects.
  - Load, compile and integrate properly.
  - Work as expected now.
- In the course of the above, various bugs in build process and core have been fixed.

**Immediate ToDo:**

- The final package setup needs to be tested locally, with a local repo.
  - From a v1.x version, does the package manager properly display warnings when trying to update? Is it clear that an update would introduce breaking changes and is likely not a good idea for an existing project without preparation?
  - When doing an update anyway, is the editor fully operable, so backend plugins can be installed later?

**Comment by ilexp** [comment]
**Progress:**

- Tested the final package setup locally.
- Tested what happens when updating v1.x to v2.0 despite warnings.
  - Works as expected, editor remains functional in order to install backend packages manually.
- In the course of the above, various bugs in the build setup and editor have been fixed.

**Immediate ToDo:**

- Merge into release branch and test the automatically built packages.

**Comment by ilexp** [comment]
Done. Duality v2.0 has been released.
