### ISSUE TITLE
Improve Physics API

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#21]
Problem:
- The current Duality Physics API does not include a lot of useful Farseer Physics features.
  - Texture to polygon
  - Cutting Shapes
  - A lot of polygon utility methods
    - Make any polygon clockwise
    - Check whether a polygon is convex
    - Decomposing non-convex polygons to multiple convex ones (Convex Decomposition)
  - Controller Support
    - Wind, Gravity, Buoyancy, VelocityLimit
    - Custom Controllers
      - Provide a flexible base class (Component) that works on RigidBodies / Duality, but is a Farseer Controller internally?
      - Does it even need to be a Farseer Controller?
      - Is there even a need for such base class? The user can always just iterate over RigidBodies in the Scene.
- Dualitor could probably also benefit from some of these features
  - When adding a RigidBody to a GameObject with a SpriteRenderer etc. automatically generate a starting shape from the used primary texture.
  - This could be done using the Convert API to keep it extensible. Just ask for a collection of ShapeInfos and add converters for SpriteRenderer-to-ShapeInfo, etc.
- Dualitor, RigidBody Editor:
  - Add a "Freeform Polygon" tool that allows any kind of polygon using any number of vertices that automatically decomposes the user input after finishing the operation.
  - Add a "Move Vertices" tool that allows moving already set vertices.
  - To allow all that, move the default cursor state to a distinct toolbar button. 
  - Probably refactor some RigidBodyEditor code so all this can be implemented in a clean way without hacking.
  - Make sure switching modes behaves intuitively.
  - Add keyboard shortcuts for new modes.

Solution:
- Implement this.

**Comment by ilexp** [comment]
Closing this as it partially overlaps with issue #54 and is way to broad to be useful as an issue to resolve. Create separate issues for smaller sub-tasks as their need arises instead.
