### ISSUE TITLE
Display a "First Editor Session" Dialog

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#212]
Right now, there is no way to stumble across sample packages as a newbie.

- On the first startup of the editor, a "Welcome" dialog should ask whether the user would like to browse sample packages to install.
- If he chooses to, the Package Manager should open, switch to Online packages and filter by sample packages only.
- If he chooses not to, a menu option should be there to invoke this functionality later.
  - Probably add it to the Help menu on the upper right.

All of this can be implemented in the PackageManagerFrontend plugin.

**Comment by AdamsLair** [comment]
**Progress:**

- Various fixes and tweaks in the PackageManager UI.
- Added a "Browse Samples..." item to the Help menu.
- The editor can now determine whether it is being run for the first time.

**Immediate ToDo:**

- Add an introductory dialog asking whether or not to browse samples when running the editor for the first time.

**Comment by AdamsLair** [comment]
It might actually be a neat idea to extend this to a full-blown "First Start Intro" dialog in the main editor Assembly. It could use `IEditorAction` API with a specific context to display things to do - specified in the base and package manager UI plugins.

- Inform the user about minimum requirements.
  - .Net 4.5
  - Visual Studio 2013 Update 2
- Offer to browse sample packages.
- Offer to open up Getting Started docs.
- Offer to visit the forums.

**Comment by AdamsLair** [comment]
Done.

**Comment by SirePi** [comment]
Small issue, but the minimal VS2013 version required by Duality should be Update 3 and not Update 2. Without it PCL profile 111 is not available.

**Comment by ilexp** [comment]
Fixed. Thanks!
