### ISSUE TITLE
Generated CorePlugin has mixed tabs and spaces

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#222]
The auto-generated CorePlugin.cs file by the Duality Editor contains mixed tabs and spaces.
I use Productivity Power Tools, which pops up a prompt asking me to Tabify and Untabify everytime I open it up.
I propose modifying the auto-generated file to either use tabs or spaces exclusively, instead of interchangeably.

**Comment by ilexp** [comment]
Fixed. Thanks!
