### ISSUE TITLE
Generated projects have System namespace references

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#228]
I noticed that the plugin projects (at least CorePlugin) generated by Duality have explicit references to the System namespace (System and System.Xml.Linq, to be specific).

It was mentioned in the Duality 1.x to 2.0 upgrade guide ([here](http://forum.adamslair.net/viewtopic.php?f=17&t=557)) that we should remove all of these explicit references.

Removing these references seem to have no detrimental effects, as my code compiles cleanly without them.

**Comment by ilexp** [comment]
Fixed. Thanks for reporting!

**Comment by ilexp** [comment]
Binary fix released.
