### ISSUE TITLE
Allow adding Components to multiple selected GameObjects

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#231]
Right now, you can only add components to one GameObject at a time. It gets tiring when, for example, you change a Component class's namespace and have to re-add it to different GameObjects.

It would be much easier when you can add Components to selected GameObjects in the same way as it is done right now.

**Comment by ilexp** [comment]
Just to clarify: You're asking for an "Add a new Component of this Type to all selected GameObjects" editor feature, but **not** an engine core feature that would allow a Component to belong to multiple GameObjects at once - right?

I agree with the first option.

**Comment by hsnabn** [comment]
Yep, the first option was what I was talking about.
I actually don't understand that second option entirely, actually.

**Comment by ilexp** [comment]
> EDIT: A small thing I didn't want to create an issue for: the wiki could use an update. Duality 2.0 has been released, and there recently was someone with an issue with the wiki examples and Duality 2.0, so it would help newcomers if the wiki was up-to-date.

Fixed. Next time, please use a distinct issue though ^^

**Comment by hsnabn** [comment]
I'll keep that in mind next time.

**Comment by ilexp** [comment]
Done, see the referenced Pull Request above. Closing this.
