### ISSUE TITLE
Move Flap-Or-Die Sample Content

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#242]
The content of the [Flap-Or-Die Sample package](https://github.com/AdamsLair/duality/tree/master/SampleProjects/FlapOrDie) is located in the [Data root directory](https://github.com/AdamsLair/duality/tree/master/SampleProjects/FlapOrDie/Content/Data). It needs to be moved into a subfolder that is named after the sample package, so users can safely install multiple sample packages at once, without them accidentally overwriting each other's content.

@SirePi This one might be for you - do you have time to fix this? If you do, also remember to update the [.nuspec](https://github.com/AdamsLair/duality/blob/master/NuGetPackageSpecs/FlapOrDie.Sample.nuspec) file with a new version number and dependency versions (need to match the latest binary release) so the automated build process is able to build and deploy a new release for your package.

**Comment by SirePi** [comment]
If I understand correctly, it basically consists of creating a new FlapOrDie folder inside Content\Data, and move all the resources inside it, right?

**Comment by ilexp** [comment]
Yep :)

**Comment by SirePi** [comment]
Ok, I have fixed the content, but now I'm looking at the .nuspec and it seems already fine.. am I missing something?

**Comment by ilexp** [comment]
You'll need to adjust the dependencies of the package to reference the latest binary release with their version number. Otherwise, your package will be skipped in the automated build process for safety reasons.

**Comment by SirePi** [comment]
Sorry, but it's monday :smile:
Ok for upgrading the version of the sample and the version of Duality's dependency, but I also see that inside content, the files already appear to be in the correct place (i.e. under FlapOrDie\etc...)
I thought it was in the wrong place, but as it is now, I'm afraid I will do the wrong thing. Can I just push the fixes to the project, and let you fix the nuspec?

**Comment by ilexp** [comment]
Okay, so just to prevent misunderstanding: Right now, the content files are located in `FlapOrDie\Content\Data\`. Where they _should_ be is `FlapOrDie\Content\Data\FlapOrDie`, because the first FlapOrDie is just the root folder of the overall sample project.

> I thought it was in the wrong place, but as it is now, I'm afraid I will do the wrong thing. Can I just push the fixes to the project, and let you fix the nuspec?

Sure!

**Comment by ilexp** [comment]
Done.
