### ISSUE TITLE
WAV audio importer

### ISSUE THREAD

**Issue by importjingles** [AdamsLair/duality#246]
Feature Request: I'd like to see a built in WAV importer. Vorbis/mp3 is fine for long music tracks and ambiences, but most sound designers are used to working with lossless WAVs, so manually converting to compressed formats every time will be a big workflow impediment.

Duality could compress internally to optimise memory requirements (with exposed compression level controls of course).

**Comment by importjingles** [comment]
If nobody else is working on this right now, I'd like to have a go at implementing it.

**Comment by hsnabn** [comment]
It would be a nice feature to see, I suppose. If you'd like you could release the importer as a plugin, if you are implementing it yourself.

If @ilexp would like to see it integrated into Duality, then all the better.

I am curious about one thing: do you need any external dependencies (sound library) to work with WAV? I see that there are built-in facilities for playing sounds (I searched for "c# wav"), but would they make the cut?...

**Comment by importjingles** [comment]
As long as the WAVs are uncompressed you can load them in using a BinaryReader. That data can be passed directly to Duality's OpenAL objects. https://msdn.microsoft.com/en-us/library/ff827591.aspx (substitute the DynamicSoundEffect parts for OpenAL)

If it's compressed, then I'm not sure, I'd need to do more reading. I know that my sample library and many other sound designers' libraries are uncompressed WAV.

There are some third party libraries that make loading a large variety of formats easy (eg. sox), but I wouldn't like to be the one that has to check every format works as expected. In spirit of Duality's minimalism, I think a few well supported built-in importers are the way to go.

**Comment by ilexp** [comment]
> It would be a nice feature to see, I suppose. If you'd like you could release the importer as a plugin, if you are implementing it yourself.

I agree. This is indeed a nice feature add-on, and it would be an ideal fit for Duality's plugin system.

> If @ilexp would like to see it integrated into Duality, then all the better.

Nope. Part of the idea behind Duality's modular structure is to keep functionality _out_ of the core, so it can be removed and replaced depending on the users needs. And this is a prime example of plugin functionality :)

What I'd suggest would be a distinct GitHub repo for the plugin and a binary release as a plugin package, so users can install it easily into their own editor.

> If nobody else is working on this right now, I'd like to have a go at implementing it.

Great! :)

**Comment by importjingles** [comment]
Cool beans. That's a good excuse to get my head around making new plugin packages.

**Comment by importjingles** [comment]
I had to take time out due to a period of epic crunch at work and fear of burnout, but I now have a first draft of this.

As usual, it wasn't as straightforward as I hoped due to the audio data needing to be encoded in Vorbis format. As far as I could tell there's no vorbis encoder in pure .net, so I ended up implementing a native library (libsox) to do the encoding. That library comes with support for a whole bunch of other file formats, so I've implemented most of them and confirmed the following formats are working:

.aiff (.aif, .aifc), .mp2, .mp3, .flac, .wav

You can get at the repo here: https://github.com/importjingles/DualityExtendedAudioImporter

It needs unit tests, documentation and turning into a proper package. I'll look at sorting this out today.

**Comment by importjingles** [comment]
I've now made this available as a NuGet package too, under the name: Duality Extended Audio Importer

**Comment by ilexp** [comment]
I don't have the time for a thorough test myself right now, but from a quick first glance, this looks really, really good. Very nice work there, especially with the thorough intro guide on your GitHub page! :+1: 

I'm closing this issue, as you've obviously dealt with it successfully - thank you for your contribution. I do hope you'll get a lot of feedback for this in our small community. If you need anything with regards to future maintenance or have any questions, feel free to message me, or @mention me in issues on your repo, should they arise.
