### ISSUE TITLE
Duality editor does not remember Camera View settings

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#247]
A small issue I just thought of putting up here.

When you create a new Camera View in the editor, change it's view type (for example, to Game View) then restart the editor, it does not remember the new setting. It's not much of a hindrance, but it gets annoying after a time, since I like to have a Scene View/RigidBody Editor and Game View workflow, so I can easily test changes in the user's perspective.

**Comment by ilexp** [comment]
Yup, that's annoying. Will fix!

**Comment by ilexp** [comment]
Turns out, there was a typo in editor user data serialization beginning with the v2.0 release. Fixed and released!
