### ISSUE TITLE
SVG import support.

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#248]
I was just wondering whether SVG support is planned for Duality? Or is it not making it in?

If it isn't making it in, how much work would it take for someone to make an SVG importer? If it's not too hard I could try it, however limited my skills may be. Anyone else could also give it a go (nudge nudge).

**Comment by ilexp** [comment]
> I was just wondering whether SVG support is planned for Duality? Or is it not making it in?

Nope. Similar to the [.wav file audio import](https://github.com/AdamsLair/duality/issues/246), this is a prime candidate for external plugin functionality :)

> If it isn't making it in, how much work would it take for someone to make an SVG importer?

The Duality-specific part of that isn't too hard, just [implement your own importer](https://github.com/AdamsLair/duality/tree/master/DualityEditorPlugins/EditorBase/Importers) in an editor plugin. I suppose SVG rendering is much harder, but there are likely libraries for that out there.

**Comment by hsnabn** [comment]
So all I have to do is add an importer, and add rendering support? I see that there is an SVG rendering library for C# available here: https://github.com/vvvv/SVG

As I said before, if the rendering part isn't too hard I'll take this on.

**Comment by hsnabn** [comment]
Okay, so I've managed to get in simple SVG import. All I do is just convert the SVG document to a bitmap, albeit using an external library (the one I mentioned in my last comment). Only a few lines changed.

I doubt you'll get SVG's 1:1 resize-ability or any other goodies though. When it's resized, is there a way I can re-render the image?

I'm sorry for all theses questions. I know next to nothing about, well, anything.

I'll be looking into creating a repository for it soon.

**Comment by hsnabn** [comment]
Okay so I created the repository. It's available here:
https://github.com/hsnabn/duality-svg

Please note that I got SVG to work by only removing and adding three or four lines of code. It's not very featured yet.

**Comment by ilexp** [comment]
> I doubt you'll get SVG's 1:1 resize-ability or any other goodies though. When it's resized, is there a way I can re-render the image?

Nope, that's not what Pixmaps and Textures are designed for. If you want real vector graphics ingame, you'll need to write a custom Resource for vector art (could just encapsulate SVG data) and a custom ICmpRenderer that is able to submit vertex data which is derived from the SVG. Basic support for simple shapes like polygons and circles shouldn't be too hard, but supporting the whole SVG featureset is, I think, not a small task.

> How should I be licensing my repository?

No idea. Maybe [tl;dr legal](https://tldrlegal.com/) can help? They're not in any way guaranteeing correctness though. If you want to be really sure, you'll have to read the actual license yourself though.

> OR do I not include the SVG library? I think this is the way to go. I could just mark it as a dependency and let the user deal with installing it?

They probably have a NuGet package of their library. Right-click on your VS project of the plugin and search for something like "Manage NuGet Packages". Then install theirs. When you at some point publish your Duality package (which is also a NuGet package), you can add theirs to its dependency libraries.

The licensing question still remains though, you should definitely check that.

**Comment by hsnabn** [comment]
License looks good, I guess.

I don't think I can make a custom renderer. But wait! Would it be possible to make a resource, like you said, and then I could have a function that creates a new Pixmap based on an image size given in the resource? Perhaps attached to the resource itself, like a button? Is that even possible?

**Comment by ilexp** [comment]
> Perhaps attached to the resource itself, like a button? Is that even possible?

Possible, but I'd probably just go with the custom importer that creates a Pixmap directly. No need to create another Resource type just as an editor-only container. With an importer, if the Pixmap doesn't exist yet (Import), you could spawn a user dialog asking for the desired rendering size. If it exists already (ReImport) you could just assume the size of the existing Pixmap.

**Comment by ilexp** [comment]
(Edited the above post with another thought)

**Comment by hsnabn** [comment]
> This means that importing an SVG would essentially be a one-time convert operation. I'm not sure if that's what you want.

Well, I'm sure it'll be useful to someone who somehow has a large collection of SVG art they want to use inside Duality for some reason.

However, I'm quite spent/burnt out/(insert similar word here). This ended up being way too hard than I imagined, and I don't know how to do even a quarter of the things that need to be done.

I'm going to keep the repository and maybe, *maybe* work on it once in a while. If I do in fact work on this I'm going to try to go for the aforementioned resolution dialog idea.

You can close this issue if you want, or keep it open for someone else to pick up.

**Comment by ilexp** [comment]
> However, I'm quite spent/burnt out/(insert similar word here). This ended up being way too hard than I imagined, and I don't know how to do even a quarter of the things that need to be done.

Don't worry about it - it was an idea and some ideas just need a bit of exploration before deciding what to do or whether to act on them. This is an open source project, we publicly discussed your idea and you are not in any way obligated to implement this now.

I'll close this issue for now.

------

(Also, if you feel burnt out, take some time off!)
