### ISSUE TITLE
Find a way to Recover from Incompatible Plugin Exceptions

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#252]
Right now, installing an incompatible or faulty plugin can lead to the editor not being able to start up again due to a `TypeLoadException` being thrown, as seen [here](http://forum.adamslair.net/viewtopic.php?p=3706#p3706). This is very unfortunate.

Find a way to recover from this, discard the faulty plugin and go on without problems. Both editor and core plugins.

**Comment by RockyTV** [comment]
I don't know if it is like that in the code, but you could surround the load plugin part with a try/catch, and if it catches an exception it just warns the user that the plugin is incompatible/won't work and the editor will unload the faulty plugin?

**Comment by ilexp** [comment]
> I don't know if it is like that in the code, but you could surround the load plugin part with a try/catch, and if it catches an exception it just warns the user that the plugin is incompatible/won't work and the editor will unload the faulty plugin?

Yup, something like that is what I intended :)

**Comment by hsnabn** [comment]
Is this the part of the code in question?
https://github.com/AdamsLair/duality/blob/master/DualityEditor/DualityEditorApp.cs#L224

**Comment by ilexp** [comment]
Done.
