### ISSUE TITLE
Minor Bug in AnimSpriteRenderer (No Observed Negative Effect)

### ISSUE THREAD

**Issue by amberGit** [AdamsLair/duality#253]
lines 463,464 the code block “else if " cannot be executed.

**Comment by ilexp** [comment]
Confirmed. [Link to the code in question](https://github.com/AdamsLair/duality/blob/master/Duality/Components/Renderers/AnimSpriteRenderer.cs#L463-L464).

**Comment by hsnabn** [comment]
Is that piece of code supposed to be included in the `if` code block above it, or the `else` block below it? Or is it to be left out of the code entirely? Just asking.

**Comment by ilexp** [comment]
It's old fallback code from the time when Textures didn't have a copy of their source Pixmap's atlas. Removing that bit of code entirely should be fine.

**Comment by amberGit** [comment]
Got it.

**Comment by ilexp** [comment]
Fixed by @hsnabn
