### ISSUE TITLE
Scene contents are deleted when saving fails and Sandbox is ran

### ISSUE THREAD

**Issue by deanljohnson** [AdamsLair/duality#263]
To reproduce this bug:

* Create a new empty project
* Add an empty GameObject
* Save the scene
* Create a component that throws an exception in OnShutdown

```charp
public class ExceptionThrower : Component, ICmpInitializable
{
    public void OnInit(InitContext context)
    {
    }

    public void OnShutdown(ShutdownContext context)
    {
        throw new NotImplementedException();
    }
}
```

* Add this component to the empty GameObject
* Run the sandbox

If you re-open your scene file, everything will be deleted. This will delete all GameObjects, not just the object containing the component that threw the exception.

Duality makes backups, which kind of protects against this, but I think that it would be better to prevent the saving in the first place if this kind of bug occurs, or at least save all valid GameObjects/Components

See http://forum.adamslair.net/viewtopic.php?f=16&t=669 for the forum post that mentioned this issue.

**Comment by ilexp** [comment]
Looks like there should be an editor guard somewhere. Thanks for reporting! Will look into this.

**Comment by priyanshus1** [comment]
*Regards    Priyanshu Shukla                            *

*Student       *

*Department of Computer Engineering       Pune Institute of Computer
Technology   *


*India                                 *
PS: To reach please mail at priyanshus1@gmail.com or call +91-90280-80386

**Comment by ilexp** [comment]
Addressed this issue in [this commit](https://github.com/AdamsLair/duality/commit/57bb4dea529c87feacdb90698901e027e75aa02c): Whenever an exception occurs in the save preparation of a Resource (including Scenes), the save operation will no longer be performed.

This will lead to Scenes containing the above mentioned kind of problematic Components being reverted to their already persistent / saved state when attempting to enter Sandbox mode, which is equal to manually retrieving the latest backup file.

The problem of certain faulty Components potentially corrupting Scenes while saving them is a more general one and could be addressed either by per-object try-catch use (which I'm not in favor of, seems a bit excessive) or by getting rid of `OnSaving` / `OnSaved` altogether and thus removing the execution of user code as part of the saving process. Both options have their drawbacks.

Still, as the main goal of preventing faulty save operations from happening should be fixed now, I'll close this issue. The more general problem should be addressed elsewhere.
