### ISSUE TITLE
Project name in Title bar of Duality Editor window

### ISSUE THREAD

**Issue by toyners** [AdamsLair/duality#267]
Currently the title of the Duality Editor window is "Dualitor" (see attached image).

![untitled](https://cloud.githubusercontent.com/assets/11983537/12376384/5f9225cc-bd45-11e5-81e0-68914bf1c638.png)

With two or more projects open it would be nice to see the project name in the window title bar so the correct editor can be selected. Not a big deal but would be nice to have.

**Comment by ilexp** [comment]
Sounds like a neat idea. Tagged and noted for future improvements!

**Comment by ilexp** [comment]
Implemented and released.
