### ISSUE TITLE
Incorporate Some of the batbuild Changes

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#272]
The [batbuild fork](https://github.com/batbuild/duality) of Duality recently incorporated some interesting changes for improving performance and memory footprint. Since this is done on an old and heavily modified Duality version, being able to merge changes directly might be a rare luxury, but they could nevertheless be considered for manually implementing similar changes to the master branch. Some of them _do_ seem quite interesting.

Some examples:
- [ ] TexSubImage: https://github.com/batbuild/duality/commit/907d5b33eead239f616a75e08183e6d85d4e6950
- [ ] Texture.Clear: https://github.com/batbuild/duality/commit/1d552360d57523e96b54799953895880a769de3a
- [x] GameObject.GetChildrenDeep: https://github.com/batbuild/duality/commit/6f311c3c2ae5aadf3e46120ca07719989bb0c0f6
- [x] Some LINQ Removal: https://github.com/batbuild/duality/commit/f3da098c49b15ece05e4d42e5ff1d7dcbdd1eab3
- [x] Renderer Active Check: https://github.com/batbuild/duality/commit/b30acf2b454a59f67b22208b822bd0546ee81a50
- [x] Camera Z Sorting: https://github.com/batbuild/duality/commit/118007f1fb41593fa3b8722f6b6b2ab40e9c7e73
- [x] RigidBody Transform Updates: https://github.com/batbuild/duality/commit/0f93fe7a77276d8c76620e5f92cd13757c77fada
- [ ] UpdateAbsChild: https://github.com/batbuild/duality/commit/963ef89217cc7f525e30d5f65f42cb8c7d49c692

cc @BraveSirAndrew to make sure this is fine for everyone before shamelessly grabbing code.

**Comment by BraveSirAndrew** [comment]
Hey Adam, absolutely fine! Let me know if you want to discuss any of them, although they're for the most part very simple tweaks.

**Comment by ilexp** [comment]
Thanks! I'll let you know if something comes up.

**Comment by ilexp** [comment]
Moved to v3.0 milestone, as some of the above changes have either been done or prepared inadvertently by the general cleanup that happened in the meantime.

**Comment by ilexp** [comment]
Closing this issue as part of a v3.0 roadmap cleanup. Parts of it have been implemented, others were addressed [as part of other v3.0 issues](https://github.com/AdamsLair/duality/milestone/6?closed=1) like #510 and #388. The texture API extensions remain open and should be addressed when there's demand for it.
