### ISSUE TITLE
TreeViewAdv Exception in PackageManager

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#293]
#### Summary

When using the Package Manager tree view with keyboard input, an unhandled exception is thrown when attempting to scroll past the end of the list.

#### How to reproduce

- Open the Package Manager.
- Select "Online Repository" as a source.
- Click into the package list.
- Hold the down arrow key until reaching bottom. Each subsequent keydown of the down arrow will result in a logged exception.

#### Attachments

```
[Edit] Error:   An error occurred: ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
CallStack:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Aga.Controls.Tree.NormalInputState.NavigateForward(Int32 n)
   at Aga.Controls.Tree.NormalInputState.KeyDown(KeyEventArgs args)
   at Aga.Controls.Tree.TreeViewAdv.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by RockyTV** [comment]
This should be happening because when you switch to the Online Repository as source, the package manager will load all available plugins first, and then removes the incompatible ones, but my guess would be that the TreeViewAdv is not updated to reflect this change.

In other words, the package manager should only load compatible packages, instead of loading all Duality packages.

**Comment by ilexp** [comment]
> This should be happening because when you switch to the Online Repository as source, the package manager will load all available plugins first, and then removes the incompatible ones, but my guess would be that the TreeViewAdv is not updated to reflect this change.

It actually is updated, but I had to add some custom code in order to be able to filter items efficiently. I suspect that I forgot a bit of code (or introduced a bug) when using keyboard navigation to select the next element in order to account for hidden / fitlered items. There's probably some code in `NavigateForward` that doesn't properly check hidden items and gets an index wrong.

> In other words, the package manager should only load compatible packages, instead of loading all Duality packages.

Not sure if this is really the cause of the problem, but I've been thinking about this as well. The reason it is implemented like this is that displaying only items that are compatible requires the system to wait until compatibility is determined. This increases wait time a lot since dependency information needs to be downloaded from the repository and you get the usual web delay while waiting for a server response. As a result, these are the options:

1. Only display compatible ones: It takes longer for items to appear and you may end up waiting for an item you already know is compatible, but the system isn't sure yet.
2. Display all, determine compatibility later: Items appear immediately and disappear again when deemed incompatible.

I've preferred the first one, but it's an arguable choice. In any case, this is probably not part of the issue, so we shouldn't add too much design discussion here :)

**Comment by RockyTV** [comment]
> There's probably some code in NavigateForward that doesn't properly check hidden items and gets an index wrong.
My guess would be this `while` loop [in here](https://github.com/AdamsLair/treeviewadv/blob/1adc3100fee84760639b437f671ee91809af1ef8/Aga.Controls/Tree/Input/NormalInputState.cs#L148). Perhaps changing the `while` to `if` should fix the issue. I'll get to testing it.

**Comment by ilexp** [comment]
> My guess would be this while loop in here. Perhaps changing the while to if should fix the issue. I'll get to testing it.

I'm pretty sure this needs to be a `while` - how else would it handle N consecutive hidden elements? That said, I think you spotted the correct line, the while loop will simply run over the last element if it's hidden.

What needs to be done instead:
- Do the while loop, but have a range check.
- When exceeding the range, break out of the loop. However, this means we found _only hidden elements_.
- So, instead of breaking out of the loop (which would lead to executing the forward navigation), we need to `return` instead (and thus do nothing, since we're apparently already at the last element).
- `NavigateBackward` needs to be adjusted in the same way.

**Comment by RockyTV** [comment]
What about completely removing the `while`, and checking for visible nodes only? Would it be better than range checking?

**Comment by ilexp** [comment]
> What about completely removing the while, and checking for visible nodes only? Would it be better than range checking?

Well, that's what we're doing here. :smile: The purpose of this method is to navigate to the next visible element. In order to do so, we'll need to skip all the elements that aren't visible, which is the purpose of the `while` loop in question.

**Comment by RockyTV** [comment]
I was looking around and found that there's a property which is `Tree.VisibibleRowCount`, returning the count of the visible nodes. Why not use it instead?

**Comment by ilexp** [comment]
> I was looking around and found that there's a property which is Tree.VisibibleRowCount, returning the count of the visible nodes. Why not use it instead?

Because the count doesn't tell us where exactly these visible items are.

**Comment by ilexp** [comment]
Fixed as described in one of the previous comments. Closing this.
