### ISSUE TITLE
Weird Behaviour when Moving Objects in the Scene View

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#302]
#### Summary
This issue was first reported on the forum by user **indiemaatheus**: [Forum Topic](http://forum.adamslair.net/viewtopic.php?f=16&t=733)

> Hey, recently I noticed that something weird is happening when dragging and dropping objects in the scene, it was not happening before. I just have no clue what I'm doing wrong, see:
[Image](http://i.imgur.com/yKM5O4o.gif)
Instead of following the mouse, the sprite starts moving extremely fast in its direction. (surprised/confused face here)
What should I do?

#### How to reproduce
Just place an object into a scene and try dragging it around. The object should move weirdly, and a lot of error messages should be written to the log.

This issue seems prevalent on the latest Duality binary release. Versions built from source seems to not have the problem. **indiemaatheus** uploaded a sample project ([Dropbox](https://db.tt/WQabs6OP)), but as said before, the problems seem to occur even in the binary release (from [the Duality website](http://duality.adamslair.net/)).

#### Workaround
No workarounds are known, except to use a version built from the source code.

#### Attachments
- An error occurs and is written to the log when moving objects: [Pastebin](http://pastebin.com/raw/CYuQhecV)
- An animated GIF image was uploaded by **indiemaatheus**, available here: [Image](http://i.imgur.com/yKM5O4o.gif)

**Comment by ilexp** [comment]
Thanks for reporting! Apparently, there was a binary version mismatch in the latest package release. I have released a new set of packages that should fix this. Can someone aside from me verify this?

**Comment by hsnabn** [comment]
Downloaded the binary release again, and it seems to be working perfectly now. I could drag an object around without any bugs or errors.

**Comment by ilexp** [comment]
Thanks! :) Closing this.
