### ISSUE TITLE
Problem with System reference

### ISSUE THREAD

**Issue by kinger6** [AdamsLair/duality#305]
#### Summary

I am trying to use Console.WriteLine() for my debugging. But the console namespace doesnt exist in my project(i have using System;) i've tryed added the System.dll to my project through other means but it tell's me the build system automaticlly add's it.. Is there a duality equivalent to unity's Debug.Log() where i can log in the editor Log View?

EDIT: I found Log.Game.Write()
 so don worry about this..

**Comment by ilexp** [comment]
The game plugins Duality generates are Portable Class Libraries, which operate on a reduced surface API in order to improve portability across platforms. This portable API does not include the Console class. For logging use the Duality `Log` class instead!
