### ISSUE TITLE
AnimSpriteRenderer CustomFrameSequence not showing full count in GUI

### ISSUE THREAD

**Issue by mika76** [AdamsLair/duality#312]
When setting the CustomFrameSequence array count to 13, the list only shows 9 items. I'm not sure if this is a general gui list limitation or just for this specific list.

**Comment by mika76** [comment]
Example below.
![screen shot 2016-04-15 at 17 01 11](https://cloud.githubusercontent.com/assets/229311/14565500/b0f77dfa-032b-11e6-8eb1-d4bb6481d636.png)

**Comment by ilexp** [comment]
That's not a bug, but by design for performance reasons when your array / list types get large or contain complex objects. Use the `Offset` pseudo-property to adjust what section you're seeing. :)

**Comment by mika76** [comment]
Ah-ha I was wondering what the offset thing is for. What about adding popup editors kind of like Visual Studio does?

**Comment by mika76** [comment]
Actually just thinking - a simple little text hint at the bottom of a list like this saying "Use offset to edit more..." or something would solve this problem quite nicely...

**Comment by ilexp** [comment]
Yep, this can be improved regarding to usability - but it's not on my ToDo horizon right now. It's working and not too bad, so I'd prioritize this more as a nice to have kind of thing. There's simply so much else to do.
