### ISSUE TITLE
Physics Support for Chain Shapes

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#330]
#### Summary

Duality currently supports Circle-, Polygon- and Loop Shapes. There is no way to specify a shape that is not a closed loop, which can be unwieldy at times and also gets in the way of issue #279. Extend the physics backend and Duality glue code to support Chain Shapes to fix this.

#### Analysis

- The Farseer Physics backend currently does not support Chain Shapes, but Farseer 3.5 does. It is likely that Chain Shape support could be merged into the Duality-specific version of Farseer, potentially replacing the Loop Shape entirely.
- A Loop Shape is actually a special case of a Chain Shape. The physics backend might only need support for the chain shape case, while the Duality glue code could use it in one or the other way.
- There needs to be editor support for Chain Shapes. It is likely that this could share a lot of code with Loop Shape editing.

#### Next Steps

- [x] Merge back ChainShape to Farseer backend, replacing LoopShape.
- [x] Update Duality to internally use the physics ChainShape for creating LoopShapes.
- [x] Introduce a new ChainShape type to Duality.
- [x] Implement editor support for ChainShapes.

**Comment by ilexp** [comment]
**Progress:**

- Updated the Farseer backend accordingly, with some additional cleanup.

**Comment by ilexp** [comment]
**Progress:**

- Updated Duality physics backend and glue code for the existing LoopShape.
- Introduced a new ChainShape type to Duality.
- Implemented rendering logic for ChainShapes in RigidBodyRenderer and the RigidBodyShape CamView layer.

**Comment by ilexp** [comment]
**Idea:**

This would actually be a nice opportunity to refactor some of the old RigidBody editor code and clear it up to make potential improvements (#54) much easier. The [TilemapTool](https://github.com/AdamsLair/duality/blob/tilemap-wip/DualityEditorPlugins/Tilemaps/CamViewStates/TilemapTool.cs) approach can serve as a role model for this: Instead of aggregating code for all tools / user actions at a single place, have a base class that defines a user action and keep those actions separate from the environment in which they are executed.

In practice this would mean to replace the internal CursorState enum with an abstract RigidBodyEditorTool class.

**Comment by RockyTV** [comment]
Why merge the feature into Duality's fork of Farseer instead of updating it?

**Comment by ilexp** [comment]
Mostly because of two reasons:

- Because updating would mean jumping to Farseer 3.5, which hasn't been maintained for years and still has some unresolved issues that would be critical to Duality. I'm not proficient enough with Farseer to fix any issues that might be adopted with jumping to 3.5. The current version, on the other hand, is very stable.
- Because the Duality version of Farseer has deviated a lot from the original source. Merging a single feature back is a lot more manageable than merging the entire 3.5 release back.

I did do some tweaks and cleaned up a lot of code in the process though.

**Comment by ilexp** [comment]
**Progress:**

- Refactored the RigidBodyEditor CamViewState as described in the above idea. It should now be a matter of five to ten minutes to implement a new tool for creating chain shapes.
- Overall cleanup in RigidBodyEditor, SceneEditor and ObjectEditor (base) classes. 
  - This also involves renaming and moving classes which is technically a breaking change.
  - As far as I know though, there is not a single editor plugin project out there that actually relies on any of them directly, so that should be fine.

**Comment by ilexp** [comment]
**Progress:**

- Completed editor support for ChainShapes.

Closing this.
