### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#333]
There is is a spelling mistake in the documentation of the [ICmpEditorUpdatable](https://github.com/AdamsLair/duality/blob/master/Duality/Components/ICmpInterfaces/ICmpEditorUpdatable.cs#L13)-Interface on line 13:

> Implement this interface in **C**<see cref="Component">Components</see>...

**Comment by ilexp** [comment]
Fixed.
