### ISSUE TITLE
Tilemap: Restitution of rigidbody gets overridden 

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#369]
The restitution-value of the rigidbody (WorldGeometry-Object) gets overriden on startup.

When you start the game, the value is always 0.3.

I've already create a custom component which sets the value to 0, but it doesn't affect anything.

**Comment by ilexp** [comment]
This should definitely work, but there's not code to make it work yet. Will look into this.

**Comment by ilexp** [comment]
Done and Released. It'll take a few minutes until the new package release will be indexed and available.
