### ISSUE TITLE
Tile Palette could show texture index of hovered/selected tile

### ISSUE THREAD

**Issue by RockyTV** [AdamsLair/duality#373]
There's not much to describe, and I don't know how the tile palette works, but I think it's entirely possible to make it display what index is the selected/hovered tile's texture in the tileset's pixmap/texture?

It's a really helpful feature.

**Comment by ilexp** [comment]
Great suggestion! Sounds super helpful, both for debugging and development in general.

**Comment by ilexp** [comment]
As forum user loeller pointed out, this could also be added to the `Tilemap Editor` CamViewState hover overlay. Right now, it only shows X and Y coordinate of the hovered tile, but it could easily show the index as well.

**Comment by ilexp** [comment]
Done. Release in progress, check for updates in about 30 minutes.
