### ISSUE TITLE
Rigidbody display bug in Rigidbody Editor 

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#383]
#### Summary

Rigidbodies with a non-null angular velocity will be displayed oddly in the rigidboy Editor, but will behave normally (see first gif).

It seems that the rigidbody is displayed using a different Z value (see second gif). Changing RB Editor camera to Flat or Parallax doesn't do anything. 

#### How to reproduce [Bugs]

- Tried to reproduce in a fresh project but couldn't, will update if found. [Project source uploaded here](https://chatpion.itch.io/the-rocks-and-bowls-war)

#### Attachments

![Normal collisions](https://cloud.githubusercontent.com/assets/3697923/18091609/81487b54-6ec9-11e6-83e6-a4a4b71f83a0.gif)

![Z problem ?](https://cloud.githubusercontent.com/assets/3697923/18091524/3cb12040-6ec9-11e6-9ce5-eb3e1a208705.gif)

**Comment by ilexp** [comment]
:+1: for this really really nice bug report.

**Comment by ilexp** [comment]
Fixed and release in progress. Check for package updates in about 30 minutes.
