### ISSUE TITLE
Introduce Filter-By-Component to Scene View

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#408]
Like the title says, introduce a way to filter components in the scene view.

At the moment, it's only possible to search for gameobject names.

**Comment by ilexp** [comment]
Good suggestion. Could actually done similar to the way the Camera View allows to filter by Components types.

**Comment by ilexp** [comment]
As discussed in the chat, this is already possible by switching to display Components and entering the name of the Component type in the search field. There is potential for a more sophisticated unified / editor-wide filtering, but closing this for now as this would be a separate issue with a much larger scope.
