### ISSUE TITLE
Fix invisible name of interfaces in lists

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#420]
When you added a new interface to a list in the editor, the name of the interface isn't visible.
Only when you open the list item, the name gets visible and stays visible. 

![gif](https://thumbs.gfycat.com/AgedVigorousBactrian-size_restricted.gif)
https://gfycat.com/AgedVigorousBactrian

My code:

```C#
public List<IHudRenderer> HudRenderers
{
	get { return hudRenderers; }
	set { hudRenderers = value; }
}
private List<IHudRenderer> hudRenderers = new List<IHudRenderer>();

// IHudRenderer is just an interface.. nothing special...
```

**Comment by ilexp** [comment]
Fixed in a recent commit. Release in progress. Check for package update in about 30 minutes.
