### ISSUE TITLE
SpriteRenderer removes first character of text

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#434]
When you add a slash in front of the text of the spriterenderer, the frist character of the string gets removed.

Example:
/hello -> /ello

**Comment by ilexp** [comment]
Are you talking about the TextRenderer text? Otherwise I'm not sure what you mean.

**Comment by ilexp** [comment]
Closing this, as it has been cleared up by @SirePi in the chat. Thx!
