### ISSUE TITLE
Fix Case Sensitivity Bugs in .csproj Files

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#436]
### Summary

As discovered by @mfep when building Duality using a unix system, there's a case sensitivity bug in one of the `.csproj` files. There might be more. Track them down and fix them.

### Analysis

- `RaycastCallback.cs` is referenced as `RayCastCallback.cs`

**Comment by mfep** [comment]
This is not the only problem regards the monodevelop build. Most of them comes from the fact, that monodevelop parses the .csproj files slightly differently. The xml syntax of post-build arguments is different, also on linux different commands are required

**Comment by ilexp** [comment]
> This is not the only problem regards the monodevelop build. Most of them comes from the fact, that monodevelop parses the .csproj files slightly differently. The xml syntax of post-build arguments is different, also on linux different commands are required

Agree 100%, but this is a different issue. There needs to be a separate postbuild for unix systems.

**Comment by ilexp** [comment]
Done.
