### ISSUE TITLE
Autotile system provides incorrect fallbacks for 16 part tilesets

### ISSUE THREAD

**Issue by mfep** [AdamsLair/duality#450]
### Summary

I've run into issues when used a simpler 16 part tileset. These tilesets do not contain tiles with corner specific connectivity For example in the following tilemap (where x means tile and o means empty - a tile from a different autotile set), both tiles should fallback to the no-connection one. Note, that this example works as expected in Duality, but there are problems with some more convoluted cases.
```
o o o o
o x o o
o o x o
o o o o
```
### How to reproduce [Bugs]
1. Create a 16 part tileset. Use this image, if you don't have better. It has a transparent row below.
![tileset](https://cloud.githubusercontent.com/assets/12499658/21072967/9781ae0e-bed3-11e6-8553-987313407bce.png)
2. Configure the autotiling:
![c](https://cloud.githubusercontent.com/assets/12499658/21072976/080514ea-bed4-11e6-9dd3-afaec03ad62d.PNG)
3. Create the following 3x3 Tilemap:
```
x x o
x x x
x x o
```
The fallbacks are calculated incorrectly, thus the look of the tilemap is the following:
![capture](https://cloud.githubusercontent.com/assets/12499658/21072988/512ef0f0-bed4-11e6-9ecc-e1137e87b64f.PNG)

### Workaround [Bugs]
Double up the image file behind the tileset, and configure all 8-connection tiles on it.

**Comment by ilexp** [comment]
Added to my immediate ToDo list. If someone else wants to grab this and do it instead, please comment first so we don't do the same work twice.

**Comment by ilexp** [comment]
Edited Tileset image that helps to illustrate the problem:
![tileset](https://cloud.githubusercontent.com/assets/14859411/21075090/bed09426-bf09-11e6-9b38-ed42ede43fe9.png)

Also made a quick test map to see which permutations are affected:
![unbenannt](https://cloud.githubusercontent.com/assets/14859411/21075096/ddcc531a-bf09-11e6-8d36-5f935e69b82d.PNG)

So far it seems that the neighborhood relationship above (in four directions) is the only one affected.

**Comment by ilexp** [comment]
These four lines are probably the ones to be adjusted: [Link](https://github.com/AdamsLair/duality/blob/2f648f4874b8b3f82aff059324ab5e3382c62500/Source/Plugins/Tilemaps/Core/Tilesets/TilesetAutoTileFallbackMap.cs#L97-L100)

**Comment by ilexp** [comment]
Done. Release in progress.
