### ISSUE TITLE
Wrong AnimFirstFrame in AnimSpriteRenderer depending on the frame count

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#453]
### Summary

If the AnimFrameCount is one or more, the AnimFirstFrame is normal.

However, if it's equal to zero, then everything is offset by one : 
AnimFirstFrame               : 0 1 2 3 ...
Actual` index in spritesheet : 0 0 1 2 ...

**Comment by ilexp** [comment]
I'm not 100% sure what you mean by "everything is offset by one". Can you provide a short source code excerpt and comment on the expected vs. the actual values of affected properties and methods?

**Comment by ChatPion** [comment]
From what I experienced,
AnimFrameCount = 0
![paintdotnet_2016-12-12_20-22-41](https://cloud.githubusercontent.com/assets/3697923/21113173/cf407498-c0a8-11e6-9755-1f2e9660f0d7.png)

AnimFrameCount >= 1
![paintdotnet_2016-12-12_20-22-14](https://cloud.githubusercontent.com/assets/3697923/21113177/d0dbf660-c0a8-11e6-936a-cfb82b33c88e.png)

**Comment by ilexp** [comment]
That makes it a bit clearer, thanks! I'll leave this open and up for grabs for now in case someone wants to tackle it. Doesn't seem that critical and could be a good case for new contributors.

### Workaround

Never assign less than one to `AnimFrameCount` - it doesn't usually make much sense anyway.

**Comment by IanTeo** [comment]
Hi, is it ok for me to try to do this?

**Comment by ilexp** [comment]
Yep 👍

**Comment by IanTeo** [comment]
Are there any automated tests that I can run for this project after I have made the changes?
I looked around the contributing guide and could not figure out how to run the tests.
Could someone point me in the right direction? Sorry for the inconvenience.

**Comment by ChristianGreiner** [comment]
I think you can use this nunit project:
https://github.com/AdamsLair/duality/blob/master/Test

**Comment by ilexp** [comment]
Alternatively, you can select one of the test project as startup project in Visual Studio and it should launch the NUnit project @ChristianGreiner mentioned.

**Comment by ilexp** [comment]
Fixed by @IanTeo
