### ISSUE TITLE
Write a Wiki Article on "Audio Handling" Documentation

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#483]
### Summary

Write a wiki article that deals with how to use the audio backend of Duality.

### Analysis

- Basics: Play sounds
- 3D sound effects
- adjust audio properties like panning, pitching, level (SoundInstance)
- tipps & tricks

**Comment by ilexp** [comment]
[Moved](https://github.com/AdamsLair/duality-docs/issues/9) to the docs repo.
