### ISSUE TITLE
Duality keeps recreating ProjectPlugins.

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#491]
### Summary

In my case i have renamed my solution to 'Pathfindax'. This works fine except for the fact that duality keeps recreating the ProjectPlugins solution file and the CorePlugin folder. From what I have seen in the source code the name of the solution file seems to be hardcoded.

### How to reproduce

-Rename solution file to a different name
-Restart duality
-Notice the ProjectPlugins solution file has been recreated.

### Workaround

Not really a workaround but you can ignore it in visual studio/source control and pretend its not there.

### Analysis

A way to change the default hardcoded name of the solution file would prevent this

**Comment by ilexp** [comment]
It wouldn't hurt to allow changing this (similar to launcher selection), or wait with creating the solution until the user explicitly wants to open the game plugin source code.

**Comment by Barsonax** [comment]
Another alternative would be that instead of searching for ProjectPlugins.sln it searches for *.sln inside the SourceCodeDirectory. This shouldn't be that hard to change I think and this will avoid recreating the ProjectPlugins.sln.

Eventually it would be nice if you could actually specify the name of the solution before they are added but this requires more work. After its created it could simply do the above check.

**Comment by ilexp** [comment]
> Another alternative would be that instead of searching for ProjectPlugins.sln it searches for *.sln inside the SourceCodeDirectory. If this solution file exists there shouldn't be a reason to also generate the other projects.

Sounds good. If you're up for it, go ahead 👍

**Comment by Barsonax** [comment]
Done :)

**Comment by ilexp** [comment]
Fixed by @Barsonax in PR #585.
