### ISSUE TITLE
Open sub folder when mouse hovering the root folder in the scene view

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#492]
### Summary

In my opinion it's quite annoying when you want to import an asset from the windows explorer into the scene view (or an already imported asset) and the folder that you are hovering doesn't open automatically after a few seconds. 

![](http://i.imgur.com/r5mf7Dm.gif)

So every time you have to release the mouse button to know which folders are stored in the root folder...

I know you could also open the folder directly like this:
![](http://i.imgur.com/IvQpLWB.gif)
... but in my opinion it's not very user friendly.

What do u think?

**Comment by ilexp** [comment]
Looks like a straight-forward usability improvement to me 👍 

A quick fix / test can probably be implemented in Project View and Scene View separately first. A proper longer-term solution would be to extend the behavior of [TreeViewAdv](https://github.com/AdamsLair/treeviewadv) directly.

**Comment by ilexp** [comment]
Fixed by @nhold and awaiting binary release.
