### ISSUE TITLE
Package Manager should map content folder to project root on non-Duality packages

### ISSUE THREAD

**Issue by RockyTV** [AdamsLair/duality#495]
Using my plugin as an example: it depends on `IronPython.StdLib`, which extracts a `Lib/` folder to the project root according to NuGet (`target="content/Lib"`). 

The issue here is that Duality maps all content inside `content` to the `Data` folder, which may not be desired for non-Duality packages (user would have access to package-related stuff inside Duality. Instead, Duality should just map `content` to the project root if the package is not related to Duality.

**Comment by ilexp** [comment]
Thanks! This should be a comparatively small change, somewhere around [here](https://github.com/AdamsLair/duality/blob/fd7d826ac4dcf313754cb73d4a29430f538b9d24/Source/Editor/DualityEditor/PackageManagement/PackageManager.cs#L1036). The binary base directory is already remapped depending on whether or not it is a Duality or plugin package - should be sufficient to do the same for the content base directory.
