### ISSUE TITLE
Scene editor rendering issue with the Aero theme on

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#497]
### Summary

When Windows Aero is on, the scene editor grid is buggy while scrolling inside (see gif below).

![buggy_aero](https://cloud.githubusercontent.com/assets/3697923/22854625/e962941a-f072-11e6-8634-9518ca97f022.gif)

**Comment by ChristianGreiner** [comment]
I'm not sure, but do you use an integrated or a dedicated graphics card? When I'm develop on my laptop and start duality with the integrated graphics card, I will get similar artifacts. So maybe, it seams to be an OpenGL-Issue... (?)

**Comment by ChatPion** [comment]
I have an Intel Iris Pro something, probably an integrated graphic card.

**Comment by ChristianGreiner** [comment]
Maybe this could be the problem... I think your graphics-card isn't that good to do the windows aero stuff and render the OpenGL stuff at the same time properly

**Comment by ChatPion** [comment]
After some testing, it gets even weirder. Holding mouse middle lets me have a normal looking grid.
![buggy_aero_2](https://cloud.githubusercontent.com/assets/3697923/22856492/7f976e64-f092-11e6-8fcb-4147c1168ea8.gif)

**Comment by ilexp** [comment]
This does look like a graphics card issue. Can you check two things?

1. Can you upload `logfile_editor.txt` after you reproduced the behavior and closed the editor?
2. If you open the default user data and disable antialiasing completely, then restart the editor, does the issue persist?

**Comment by ChatPion** [comment]
1. http://pastebin.com/1d1Kfrh8
2. By turning the antialiasing off, the issue disappears.

**Comment by ilexp** [comment]
Nothing obvious in the logfile, but I think I remember having problems with a builtin Intel card and MSAA / antialiasing before - something like OpenGL reporting to support MSAA level X, but when actually using it some weird behavior like in the gifs you posted starts to appear, I'm guessing that there is either something broken in the driver, or this is some sort of an optimization that they do that happens to work well in some situations but is failing here. 

Closing this, as I don't see what could be done about this on the Duality-side. But one thing that you could try to fix this is open your Intel graphics control panel and search for MSAA-related options. If there is a "Force MSAA Off" option, try that one. Let me know if that helps!

**Comment by ChatPion** [comment]
I turned every antialiasing options off and now it works ! Thanks !
