### ISSUE TITLE
Dualitor crashes when closing with the Log View undocked

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#500]
[logfile_editor.txt](http://pastebin.com/Jnc5nDXi)

### How to reproduce [Bugs]

- Open Dualitor
- Show the Log View and completely undock it (it should be a floating window)
- Load a Scene (create one if needed)
- Close Dualitor, it should crash

**Comment by ilexp** [comment]
Fixed by @hsnabn
