### ISSUE TITLE
Add Zoom Level Option to Tileset View

### ISSUE THREAD

**Issue by mfep** [AdamsLair/duality#503]
### Summary

Editing AutoTiles in the Tileset editor is difficult at tiny tile sizes. Although tiles under 24x24 are scaled up, on some displays, editing larger tiles than that is a challenge too.

### Workaround

Windows Magnifier

### Analysis

- The display size of the tiles in the tile editor could be modified arbitrarily
- ..with a pair of buttons on the toolbar,
- and by scrolling the mouse wheel (that's a standard way of resizing the view in many applications)

### Icons
`magnifier_zoom_in` and `magnifier_zoom_out` icons from the fatcow set could be used for the buttons.

**Comment by ilexp** [comment]
Done by @mfep, release in progress.
