### ISSUE TITLE
Make Scenes (More) Self-Contained

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#504]
### Summary

Duality is hardwired to always have one active Scene and some of its code is built on that assumption. Gradually move away from this by making Scenes self-contained / independent classes as a first step.

### Analysis

- Internally, all Scenes share a single static physics `World`. Replace this with a Scene-local instance that is created on-demand and cleared / re-used.
- Rename `scene.IsCurrent` to `IsActive` to clear the way for future changes in behavior.
- Find all references to `Scene.Current` and evaluate whether they can be removed or replaced with `gameObj.ParentScene`.
- Make `Render` and `Update` API public and allow calling them when the Scene is not the `Current` one. 
  - Modify switch locking behavior to only trigger for the `Current` scene.
  - Write a unit test to verify whether Component methods for rendering and updates are properly called for non-`Current` scenes when called explicitly.
- Replace the static `OnLeaving` and `OnEntered` handlers with public `Activate` and `Deactivate` methods for the scene class, allowing to properly activate and deactivate a secondary / non-`Current` scene before calling update and render methods.
- When done, consider going a step further and extracting `SceneManager` functionality from `Scene` that would handle scene activity and (previously) static global events. This is a new issue that would have to be created afterwards.

**Comment by ilexp** [comment]
Started investigating what needs to be done to decentralize scenes and found that the situation is a bit more complicated physics-wise, since `RigidBody` and `JointInfo` are quite entangled in direct calls to static `Scene` API related to retrieving the (shared) physics library `World` instance.

- `JointInfo` requires a `World` instance to create and delete its internal joints.
- `RigidBody` has lots of static query and raycast API that implicitly works on the current scene. Changing this requires some design / concept work on what future API and behavior should look like.
  - Adding a first `Scene` parameter to all static query methods?

This needs to be gradually solved first.

**Comment by Barsonax** [comment]
Personally I don't think a method like PickShapesGlobal really belongs in RigidBody. You always execute this method in the context of a scene, not a rigidbody. So it makes more sense that you operate on the Scene itself.

Adding these methods directly to the Scene API might make the Scene API a bit messy though. I think it could be done like this:
- Add a new class called PhysicsWorld. This class has a reference to the FarseerPhysics.Dynamics.World. Move static methods like PickShapesGlobal to this class. Since these methods always operate on the PhysicsWorld instance there's no need to keep these static.
-Replace the reference to FarseerPhysics.Dynamics.World in Scene with PhysicsWorld.

**Comment by Barsonax** [comment]
@ilexp any thoughts on this?

**Comment by ilexp** [comment]
I think that two points of your suggestion would need to be addressed:

- A `PhysicsWorld` class doesn't seem to provide any value except encapsulating the physics library world in order to have a place to put those methods.
- New users who look for a way to do physics operations like raycasts and point checks might actually look in `RigidBody` first, since that's what they're dealing with.

You're still right that those methods will always executed in the context of a scene though, and that it would make sense to move them to scene itself - if anything, the fact that they might end up all having a first argument of type `Scene` would be solid evidence of that.

Not yet sure how I'd like to resolve this, but as a middle ground, why not make them extension methods of `Scene`, defined as static methods in `RigidBody`?

- New users who come searching will find them there.
- No new wrapper class required.
- Scene itself won't get cluttered.
- You can execute those methods in the context of a scene whenever you're using the physics namespace.

**Comment by Barsonax** [comment]
You cannot have extension methods in a non static class. The compiler will not accept that.

I get your point that new ppl will look at the rigidbody class first but on the other hand if iam doing something like 'Find all the bodies in this area in scene1' it makes sense that I call that using a method of the scene class (or physicsworld class). Its different than the question 'Does this body collide with this rectangle?' which is in the context of a rigidbody.

You could however make a static Physics class which contains all these methods as extension methods. This is something that new ppl will be looking for. Especially considering the fact that unity does this too so ppl might even already be used to such a pattern.

**Comment by ilexp** [comment]
> You cannot have extension methods in a non static class. The compiler will not accept that.

Ah, damn. You're right, no chance for that approach then.

> I get your point that new ppl will look at the rigidbody class first but on the other hand if iam doing something like 'Find all the bodies in this area in scene1' it makes sense that I call that using a method of the scene class (or physicsworld class). Its different than the question 'Does this body collide with this rectangle?' which is in the context of a rigidbody. It just does not belong in the rigidbody class.

You could argue that the bulk of the methods we're talking about are really "does X collide with Y" in the broader sense, especially raycasts and point or rect overlap tests, which could actually be extended to polygon or circle overlap tests later. They're in that sense as much in the context of RigidBody as they are in the context of Scene. So while I do think that you have a point, it doesn't feel like there's a pressure to "switch to an obvious choice" because either way has its advantages and disadvantages.

> You could however make a static Physics class which contains all these methods as extension methods. This class can reside in the same namespace as the rigidbody class. This is something that new ppl will be looking for. Especially considering the fact that unity does something similar: Physics class so ppl might even already be used to such a pattern.

Good point, this would be another option.

**Comment by ilexp** [comment]
For the overlap check methods, there isn't really a big semantic difference between the instance and the static methods - they're both asking "does X collide with (point or area) Y?" while either looking at all bodies, or just at a single one. It's of course different for raycasts and broadphase queries, but still - not an unheard-of pattern to have a static method that finds instances of its class in a global scope.

Again, not saying the current approach is per se better, but that there's a figurative score to be assigned to each approach, and a threshold to be crossed to switch from one to another - and that right now, it feels like that threshold is potentially reached, but without being an obvious case.

I'd probably just let that sink in for a bit and come back to it when it comes to actually updating the API. Sometimes you just have to play around with implementations and get some hands-on experience with either approach to see which is a better fit for the situation.

**Comment by Barsonax** [comment]
> Sometimes you just have to play around with implementations and get some hands-on experience with either approach to see which is a better fit for the situation

True

**Comment by Barsonax** [comment]
What about separating scene and physics by moving physics related things to a Physics class like discussed earlier? As to not break existing code instead of removing all public physics properties you could rewrite the public properties to use the Physics class instead and only mark them as obsolete. Eventually ppl should use the Physics class for this.

Existing code in `Rigidbody` and `JointInfo` will have to be rewritten to use the Physics class instead of the Scene class. I dont think the public API will be changed here as this logic seems to be internal.

I think doing this will make it easier to convert all state from static to instance in the Scene class. Besides I think separating Scene logic and Physics logic is a good thing design wise and will keep both classes small and cohesive.

**Comment by ilexp** [comment]
> What is the long term goal of this? In the extreme case should eventually everything be a instance so that its possible to have n number of duality instances in application at the same time?

No, eventually having everything as an instance and no static state is not the goal here. Static state is essentially "Process state", and some things just make sense at that level. Launching multiple instances of Duality inside the same Process for example doesn't add much value for 99% of use cases - at that point, you might as well just launch multiple processes.

For scenes however going full per-instance mode is definitely a goal. For example, it would be super useful to be able to just simulate a scene on its own, or render a scene to some texture, regardless of other application state. Games could eventually simulate multiple active scenes at once, side by side, allowing scenarios like:

- Simulating the world map in scene A while the player walks around in a specific area in scene B.
- Simulating a space battle in scene A, while the player is in the interior of a participating ship in scene B.
- Simulating tetris, rendering it to a texture and playing it on the player characters game console in their living room.
- Letting two players complete split-screen playing a level, but each player in their own, isolated instance.

All of this is "theoretically, somehow" possible as-is, but with a lot more work on the user side.

> Besides I think separating Scene logic and Physics logic is a good thing design wise and will keep both classes small and cohesive.

Totally. And I think you're right that we shouldn't put more physics related code into scene than there already is. 

> What about separating scene and physics by moving physics related things to a Physics class like discussed earlier?

This is actually the next issue on my ToDo -  let's start getting a bit more concrete. Do you have a rough first "API proposal" as an example to talk about? I'll throw some ideas around in the IDE as soon as I manage, and get back with progress updates and some more concrete thoughts.

**Comment by Barsonax** [comment]
As a first step I moved physics related code to a separate Physics class in [this](https://github.com/Barsonax/duality/tree/504_API_playground) branch. This change shouldnt break any existing code. The Physics class instance itself is still shared across all scene instances but the Physics class itself doesnt contain static state except for the instance field. There are still a couple of static methods/properties in the Scene class that depend on this and need to be refactored in order to completely clean this up.

**Comment by ilexp** [comment]
Will check it out, thanks! 👍

**Comment by ilexp** [comment]
### Progress

- Started working on this in the `feature/self-contained-scenes` branch.
- Extracted a `PhysicsWorld` class from `Scene`, inspired by the implementation of @Barsonax.

### ToDo

- Move towards per-scene-instance physics world handling and adjust `RigidBody`, `JointInfo` and `ShapeInfo` API and implementation to match.
- Rename `scene.IsCurrent` to `IsActive` to clear the way for future changes in behavior.
- Find all references to `Scene.Current` and evaluate whether they can be removed or replaced with `gameObj.ParentScene`.
- Make `Render` and `Update` API public and allow calling them when the Scene is not the `Current` one. 
  - Modify switch locking behavior to only trigger for the `Current` scene.
  - Write a unit test to verify whether Component methods for rendering and updates are properly called for non-`Current` scenes when called explicitly.
- Replace the static `OnLeaving` and `OnEntered` handlers with public `Activate` and `Deactivate` methods for the scene class, allowing to properly activate and deactivate a secondary / non-`Current` scene before calling update and render methods.
- When done, consider going a step further and extracting `SceneManager` functionality from `Scene` that would handle scene activity and (previously) static global events. This is a new issue that would have to be created afterwards.

**Comment by ilexp** [comment]
### Progress

- Moved all global physics queries from static `RigidBody` methods to `PhysicsWorld`.

### ToDo

- Rework global / static physics queries in `RigidBody` to require a `Scene` parameter.
- Consider removing global / static physics queries from `RigidBody` altogether in favor of using `scene.PhysicsWorld.QueryXY`.
- Rename `scene.IsCurrent` to `IsActive` to clear the way for future changes in behavior.
- Find all references to `Scene.Current` and evaluate whether they can be removed or replaced with `gameObj.ParentScene`.
- Make `Render` and `Update` API public and allow calling them when the Scene is not the `Current` one. 
  - Modify switch locking behavior to only trigger for the `Current` scene.
  - Write a unit test to verify whether Component methods for rendering and updates are properly called for non-`Current` scenes when called explicitly.
- Replace the static `OnLeaving` and `OnEntered` handlers with public `Activate` and `Deactivate` methods for the scene class, allowing to properly activate and deactivate a secondary / non-`Current` scene before calling update and render methods.
- When done, consider going a step further and extracting `SceneManager` functionality from `Scene` that would handle scene activity and (previously) static global events. This is a new issue that would have to be created afterwards.

**Comment by ilexp** [comment]
### Progress

- `PhysicsWorld` instance is no longer shared across all scenes, but instantiated locally for each `Scene` instance.
- Renamed `Scene.PhysicsWorld` property to `Scene.Physics`.
- Renamed `GameObject.ParentScene` property to `GameObject.Scene` and introduced a `Component.Scene` shortcut property.
- Removed static `RigidBody` physics queries in favor of `this.Scene.Physics.QueryXY`.
- Renamed `Scene.IsCurrent` to `Scene.IsActive`.
- Various smaller bugfixes.

### ToDo

- Find all references to `Scene.Current` and evaluate whether they can be removed or replaced with `gameObj.Scene`.
- Make `Render` and `Update` API public and allow calling them when the Scene is not the `Current` one. 
  - Modify switch locking behavior to only trigger for the `Current` scene.
  - Write a unit test to verify whether Component methods for rendering and updates are properly called for non-`Current` scenes when called explicitly.
- Replace the static `OnLeaving` and `OnEntered` handlers with public `Activate` and `Deactivate` methods for the scene class, allowing to properly activate and deactivate a secondary / non-`Current` scene before calling update and render methods.
- Write a unit test to check whether a scene can be activated, updated, rendered, deactivated in isolation, including physics.
- Investigate how to approach the remaining global scene events and event handlers.
- When done, consider going a step further and extracting `SceneManager` functionality from `Scene` that would handle scene activity and (previously) static global events. This is a new issue that would have to be created afterwards.

**Comment by ilexp** [comment]
### Progress

- Integrated `OnLeaving` and `OnEntering` handlers into the `Current` setter.
- Introduced public `Activate` and `Deactivate` API to scene, which is used internally as well.
- Made `Update` and `Render` public methods and cleaned up some frame cycle specific code.

### ToDo

- Find all references to `Scene.Current` and evaluate whether they can be removed or replaced with `gameObj.Scene`.
- Write a unit test to check whether a scene can be activated, updated, rendered, deactivated in isolation, including physics.
- Investigate how to approach the remaining global scene events and event handlers.
- When done, consider going a step further and extracting `SceneManager` functionality from `Scene` that would handle scene activity and (previously) static global events. This is a new issue that would have to be created afterwards.

**Comment by ilexp** [comment]
### Progress

- Added unit tests to verify isolated de/activation, simulation and rendering of Scenes.
- Removed unnecessary references to `Scene.Current` and replaced them with `this.Scene`.

### ToDo

- Investigate how to approach the remaining global scene events and event handlers.
- When done, consider going a step further and extracting `SceneManager` functionality from `Scene` that would handle scene activity and (previously) static global events. This is a new issue that would have to be created afterwards.
- Merge back to `develop-3.0`.

**Comment by ilexp** [comment]
Reviewed the code in its current state and postponed further refactoring related to a potential `SceneManager` class in order to move forward with v3.0. Code looks fine so far, tests pass. Merged back, closing this.
