### ISSUE TITLE
SpriteRenderer Flip Horizontal Conflict with RigidBody Rotation

### ISSUE THREAD

**Issue by YMRYMR** [AdamsLair/duality#511]
### Summary

When you have a SpriteRenderer attached to a RigidBody, and the Flip property is set to Horizontal, if the RigiBody rotates the sprite does it in the opposite direction.

### How to reproduce [Bugs]

- Add a GameObject
- Add a SpriteRenderer to the GameObject.
- Add a RigidBody to the GameObject.
- Change the RigidBody's angular velocity and press play to see it working.
- Change the Flip property of the SpriteRenderer to Horizontal.
- Press play to see the bug.

### Attachments

https://gfycat.com/ParallelBlushingBlacknorwegianelkhound

**Comment by YMRYMR** [comment]
Replacing this line
`MathF.GetTransformDotVec(this.GameObj.Transform.Angle, scaleTemp, out xDot, out yDot);`
for this one
`MathF.GetTransformDotVec(this.GameObj.Transform.Angle * (this.flipMode != FlipMode.None && ((this.flipMode & (FlipMode.Horizontal | FlipMode.Vertical)) != (FlipMode.Horizontal | FlipMode.Vertical)) ? -1 : 1), scaleTemp, out xDot, out yDot);`
solves the issue.

**Comment by ilexp** [comment]
Thanks for reporting! Definitely a bug. I'm on it.

**Comment by ilexp** [comment]
Should be fixed. Check for package updates in about 15 minutes.
