### ISSUE TITLE
Add method to import resources in the editor via a file select dialog.

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#513]
### Summary

Currently, the only method of importing a resource in the Duality editor is via dragging-and-dropping a file into the Project View. Consider adding an alternative method of importing, via a file selection dialog.

#### Benefits
- Allows importing of resources in scenarios where file drag-and-drop may be unavailable.
- Makes the editor more accessible to touchpad users (drag-and-drop is kind of hard to do with a touchpad).

#### Feature Access
- Could be accessed through a tool button on the Project View.
- Might also be accessible through an option in the right-click context menu in the Project View.

#### Implementation Ideas
- The file select dialog would presumably open to the project's root folder at first launch.
- In subsequent launches, would it perhaps be possible for it to open at the folder that was last open in the dialog?

**Comment by ilexp** [comment]
Implemented by @megabytefisher in PR #702. Closing this.
