### ISSUE TITLE
Tileset Editor draws tiles without being in focus

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#526]
![https://gfycat.com/SpottedInfatuatedBlackandtancoonhound](https://zippy.gfycat.com/SpottedInfatuatedBlackandtancoonhound.gif)

In this gif you can see that I selected the "Auto Tile" button. After that I switched to the Tilemap Editor
and selected the selection tool. Without clicking the mouse button I navigated the mouse back to the Tileset Editor. 
When the mouse is in the view of the Tileset Editor, crazy stuff happens...

**Comment by ilexp** [comment]
Fixed by @megabytefisher. Closing this.
