### ISSUE TITLE
Fix IUniqueIdentifyable Implementations to Not Rely on GetHashCode

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#538]
### Summary

Right now, Component and GameObject rely on GetHashCode to produce the same result for the same value across different runs. While true for now, this is not guaranteed to be true across runtimes and could one day cause problems. Change the implementations to not rely on GetHashCode.

### Analysis

- It's a problem specifically in the case of `IUniqueIdentifyable`, because the returned value of `PreferredId` is used for persistence.
- It will not cause errors, but may cause a complete restructuring of Scene and Prefab files on every save, killing version control usability.
- Spotted in the following code:
  - [GameObject](https://github.com/AdamsLair/duality/blob/bb9ad80b32a62c5ad9d2ed977ba66f8b72f8a0e6/Source/Core/Duality/GameObject.cs#L253-L256)
  - [Component](https://github.com/AdamsLair/duality/blob/bb9ad80b32a62c5ad9d2ed977ba66f8b72f8a0e6/Source/Core/Duality/Component.cs#L136-L150)
  - Others? Investigate!

**Comment by SirePi** [comment]
Grabbed!

**Comment by ilexp** [comment]
> Grabbed!

👍 

Can't assign you for some reason, but consider yourself assigned.

**Comment by SirePi** [comment]
Implementation based roughly on this https://stackoverflow.com/questions/2351087/, tested with 1M calculation runs show an increase of roughly 50% in execution time comparing the new algorithm vs the standard GetHashCode implementation for strings.

For GUIDs, execution time is now comparable to the old GetHashCode for strings.

ToDo: unit tests to be implemented before delivery

**Comment by ilexp** [comment]
Done by @SirePi.
