### ISSUE TITLE
Improve the RigidBodyEditor

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#54]
- Add some more tools to the RigidBodyEditor: They could automatically create a matching PolygonShape.
  - Square
  - Triangle
  - etc.
- Also, Return and Escape keys should be properly evaluated during edit operations.

**Comment by hsnabn** [comment]
Old issue, yes, but I just wanted to drop my thoughts on this.
Would it be possible to add automatic shape generation while we're at it? From a sprite, I mean. From what I've read I believe it's going to required getting the vertices of the sprite, then creating a polygon?
I'm not very well versed in such matters, so here's one of the links I read:
http://gamedev.stackexchange.com/questions/16417/create-a-body-of-an-irregular-2d-sprite-in-farseer

**Comment by ilexp** [comment]
> Would it be possible to add automatic shape generation while we're at it?

Yes. I'm not currently working on this issue, but this is definitely among my list of potential features. I believe, Farseer already has some builtin algorithms to do this. What's missing is the "glue code" between Duality, Farseer and the editor.

**Comment by hsnabn** [comment]
Great! I'm looking forward to the RigidBody improvements in general (one day). It's kind of a pain to work with RigidBodies right now.

**Comment by ilexp** [comment]
**Idea:**

As a first step for RigidBodyEditor improvements, it would be really nice if non-convex polygon shapes with an infinite number of vertices were allowed. To achieve this, `ShapeInfo` and especially `PolyShapeInfo` can be refactored and re-implemented in a way that separates source vertices and a set of internal convex polygons with one fixture each. It would need to be further evaluated what impact an N-to-1 relation between fixtures and ShapeInfos has, and whether (especially but not exclusively) collision event handling is prepared for it.

As soon as non-convex polygons with N vertices are supported, it would make a lot more sense to have a nice vertex editor. Maybe there could be a shared "edit shape" tool that would allow to:

- Resize (using radius "vertex") and move (using center "vertex") circles.
- Move vertices of a poly-like shape.
- Dynamically add vertices to a poly-like shape by dragging a point on the outline where currently no vertex exists.
- Deleting vertices from a poly-like shape.

As a soft prerequisite, there probably should be a base ShapeInfo API / class for the various ShapeInfos (Poly, Loop, Chain) to reduce the amount of type checking code and keep it more extensible. This would also allow to simplify some RigidBodyShapeCamViewLayer rendering, RigidBodyRenderer and RigidBodyEditor code a lot.

**Comment by ilexp** [comment]
Closing this, as it has been split up into multiple smaller issues.
