### ISSUE TITLE
Backwards tab order in New Project dialog.

### ISSUE THREAD

**Issue by misnor** [AdamsLair/duality#542]
### Summary

Tab order appears to be backwards on the new project dialog.

### How to reproduce [Bugs]

1. Open Duality Editor
2. Click "Project Folder" text box
3. Hit Tab, repeat hitting tab.

### Workaround [Bugs]

1. Open Duality Editor
2. Click "Project Folder" text box
3. Hit **SHIFT** + Tab, repeat hitting **SHIFT** + Tab.

### Attachments

[Gif illustrating tab order in New Project](http://i.imgur.com/3BLFceE.gif)

Relatively minor issue, something i noticed right away when trying out Duality.

Windows 10 Pro 64-bit (10.0, Build 15063) if needed.

**Comment by ilexp** [comment]
Fixed in PR #543.
