### ISSUE TITLE
"Unable to retrieve property 'Family' of type 'Font'", Error sound plays on startup

### ISSUE THREAD

**Issue by gregnk** [AdamsLair/duality#544]
### Summary

Whenever Duality is started up, an error sound is played. Upon further inspection in the log file, it is found that the "Family" property from font resource is not loading properly.

Also for some reason the log file says im on windows 8 when im actually in windows 10.

### How to reproduce

- Update to the latest version of duality

### Attachments

[logfile_editor.txt](https://github.com/AdamsLair/duality/files/1088961/logfile_editor.txt)

**Comment by ilexp** [comment]
Thanks for reporting! That's a bug that was introduced with the last update. It should be non-critical, but I'll address this ASAP to get the noise back down.

**Comment by ilexp** [comment]
Fixed and release in progress. Give NuGet some time to update its index, then check back for package updates in about 15 minutes.
