### ISSUE TITLE
Vertices Dragpoints are still visible when the Gameobject is hidden

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#547]
Like the title says, the vertices dragpoints are still visible in the rigidbody editor when the Gameobject is hidden.

![](http://i.imgur.com/z3HUg2V.png)
![](http://i.imgur.com/rIGf0Ix.png)

**Comment by ilexp** [comment]
Yup, that's a bug 😄 Thanks for reporting!

Putting this up for grabs. If anyone's up for the task, comment here. Otherwise, I'll do it soon-ish.

**Comment by ilexp** [comment]
Fixed.
