### ISSUE TITLE
Simple Math and Geometry convenience improvements

### ISSUE THREAD

**Issue by mfep** [AdamsLair/duality#550]
### Summary
The following suggestions were gathered while using the engine for a number of projects. The intention is to make one's life easier by providing shortcuts for common calculations.

### List of suggestions

1. Vector component properties for `Vector2` and `Vector3` types. Obtaining the X, Y and Z vector components quickly. Names are arguable.
Implementation example:
``` csharp
struct Vector3 {
    Vector3 XVector { get { return new Vector3 (this.X, 0f, 0f); } }
    Vector3 YVector { get { return new Vector3 (0f, this.Y, 0f); } }
    Vector3 ZVector { get { return new Vector3 (0f, 0f, this.Z); } }
}
```

2. More coordinate selector properties for `Rect`. Convenient access for: `TopMiddle`, `RightMiddle`, `BottomMiddle` and `LeftMiddle` coordinates.

3. A saturation function to the `MathF` class. Similar to `Sign`, but accepts an epsilon value too.
Implementation example:
``` csharp
float Saturate (float val, float eps)
{
    if (Abs (val) <= eps) return 0f;
    return Sign (val);
}
```
4. `Clamp` is quite often used with `0f` and `1f` as boundaries. Let's create a function for that: `Clamp01`.

5. Inverse linear interpolation to `MathF`, and possibly to `Vector2` and `Vector3`.
Implementation example:
``` csharp
float InvLerp (float value, float min, float max)
{
    return (value - min) / (max - min);
}
```

6. Inverse linear interpolation with `0f` and `1f` as boundaries.

7. Introduce the well known `smoothstep` function to `MathF`. The formula is `x * x * (3 - 2 * x)`.

**Comment by ilexp** [comment]
> 1. Vector component properties for Vector2 and Vector3 types. Obtaining the X, Y and Z vector components quickly. Names are arguable.
Implementation example:

> 3. A saturation function to the MathF class. Similar to Sign, but accepts an epsilon value too.
Implementation example:

I think they're a bit too specific, so I'd leave them out for now.

> 2. More coordinate selector properties for Rect. Convenient access for: TopMiddle, RightMiddle, BottomMiddle and LeftMiddle coordinates.

Sounds reasonable. I don't want to introduce "middle" as a new terminology to the rect class, but I we could probably go with either "center" instead, or nothing at all, e.g. `Top`, `Right`, `Bottom` and `Left` each returning the middle of that side as a Vector2. What do you think?

> 4. Clamp is quite often used with 0f and 1f as boundaries. Let's create a function for that: Clamp01.

I've been missing this myself a lot. There should definitely be a `MathF.Clamp01` function.

> 5. Inverse linear interpolation to MathF, and possibly to Vector2 and Vector3.

That's pretty neat. Let's add `MathF.InvLerp`.

No vector versions for now, as it's ambiguous what an inverse lerp would do for them in cases like `InvLerp(new Vector2(0, 10), new Vector2(-1, 0), new Vector2(1, 0))`. Pretty sure there are ways to define similar operations properly, but I suspect we're no longer in the realms of an "inverse lerp" there and in fact doing something else that probably already has a different name and definition.

> 6. Inverse linear interpolation with 0f and 1f as boundaries.

By that you mean a shortcut for `MathF.Clamp01(MathF.InvLerp(value, min, max))`? I'm all for it, but we need a catchy name. Can't use `InvLerp01`, since the same would suggest a min max shortcut like with `Clamp01` when it's actually something else. Would probably go with `InvLerpClamped`, but if there's a better way to put it I'm all ears.

> 7. Introduce the well known smoothstep function to MathF. The formula is x * x * (3 - 2 * x).

Sounds good. Let's have multiple variants:

```
// value is between 0..1, result is between 0..1
MathF.SmoothStep(value);
// value is between min..max, result is between 0..1
MathF.SmoothStep(value, min, max);
```

**Comment by ilexp** [comment]
Putting this issue up for grabs, could be a good first one for new contributors.

**Comment by mfep** [comment]
> > Inverse linear interpolation with 0f and 1f as boundaries.

> By that you mean a shortcut for MathF.Clamp01(MathF.InvLerp(value, min, max))? I'm all for it, but we need a catchy name. Can't use InvLerp01, since the same would suggest a min max shortcut like with Clamp01 when it's actually something else. Would probably go with InvLerpClamped, but if there's a better way to put it I'm all ears.

I'm not quite sure what I meant with that suggestion initially. It was maybe `InvLerp(value, 0, 1)`, which is quite useless. The implementation that you suggest seems a bit too specific for me.

**Comment by ilexp** [comment]
> I'm not quite sure what I meant with that suggestion initially. It was maybe InvLerp(value, 0, 1), which is quite useless. The implementation that you suggest seems a bit too specific for me.

Alright, let's skip the `InvLerpClamped` for now.

**Comment by Barsonax** [comment]
Some more ideas:
-Add cast operators between vectors (explicit ones?).
-Add arihmetric operators between vector2 and vector3. Sometimes you have a vector3 and want to add a vector2 to it for instance.

**Comment by ilexp** [comment]
> -Add cast operators between vectors (explicit ones?).

Which ones?

> -Add arithmetric operators between vector2 and vector3. Sometimes you have a vector3 and want to add a vector2 to it for instance.

I think this would be better covered by an implicit cast, but I'm honestly not sure I want one, or that operation to succeed silently. It's sort of an odd case, and it should require some sort of explicit approval by the developer.

**Comment by Barsonax** [comment]
```
Which ones?
```
Casting from vector3 to vector2 (though the Xy property is there too? Might be redundant). I dont think there is a way to get a vector3 from vector2 though without writing it out manually.

```
I think this would be better covered by an implicit cast, but I'm honestly not sure I want one, or that operation to succeed silently. It's sort of an odd case, and it should require some sort of explicit approval by the developer.
```
Casting here would be reducing performance for no reason. When adding a vector3 and a vector2 you can return a vector3 that has the vector2's x and y added thus avoiding having to create another vector3 and the z calculation.

**Comment by ilexp** [comment]
> Casting here would be reducing performance for no reason.

Can't say for sure, but I would think this is something an optimizer should be capable of handling.

> Casting from vector3 to vector2 (though the Xy property is there too? Might be redundant). I dont think there is a way to get a vector3 from vector2 though without writing it out manually.

Casting from vec3 to vec2 and vice versa could be worth considering if they're explicit operators only, and if we're sure that there's no way either cast could be seen as ambiguous.

**Comment by Barsonax** [comment]
Float is just a scalar while vector2 and up are vectors thus I don't think its a good comparison you are making here.

Also I believe vs will tell you if there is a explicit cast available which is especially useful when discovering the API.

**Comment by ilexp** [comment]
> Also I believe vs will tell you if there is a explicit cast available which is especially useful when discovering the API.

Yeah, that's a good point.

> Float is just a scalar while vector2 and up are vectors thus I don't think its a good comparison you are making here. Its like comparing a list to its values.

Point is, I think it's not _really_ a cast if you add or remove a dimension. Is there any .Net library example where similar casts are permitted or encouraged? Casts as I'm thinking of right now are usually like this:

```csharp 
(int)42.78f
(float)42
(double)42.78f
(object)42.78f;
```

And these are not implemented as casts:

```csharp
42.ToString()
int.Parse("42")
```

From these examples, it looks to me like casting should be a change of representation for the same thing, like changing precision, or storage, but not changing the thing itself. Is that still true for adding or removing a vector dimension though? It's a close call, but I think we might be slightly off casting territory here.

**Comment by Barsonax** [comment]
> Point is, I think it's not really a cast if you add or remove a dimension. Is there any .Net library example where similar casts are permitted or encouraged? Casts as I'm thinking of right now are usually like this:

.NET doesnt have much point/vector API's but there is this:
https://msdn.microsoft.com/en-us/library/system.windows.media.media3d.point3d.aspx

So its hard to really say if this is really a convention or not. I believe its more like whats practical here? Aside from a short but clear syntax VS will also will tell you you can cast it if needed. No need for ppl to search the API for it.

**Comment by ilexp** [comment]
Just looked at System.Numerics.Vectors and it seems they don't define casting between vectors:

- [Vector2](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector2_Intrinsics.cs)
- [Vector3](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector3_Intrinsics.cs)

Doesn't mean we can't have them, but it's probably the closest thing we have to an "official" take on the matter. 

I'm still skeptical on the semantic point of view of that cast, but I'll ask around a bit to see what other game developers think. It could be a useful thing to have.

**Comment by Barsonax** [comment]
> Just looked at System.Numerics.Vectors and it seems they don't define casting between vectors:

Vector2
Vector3
Doesn't mean we can't have them, but it's probably the closest thing we have to an "official" take on the matter.

I'm still skeptical on the semantic point of view of that cast, but I'll ask around a bit to see what other game developers think. It could be a useful thing to have.

Cannot disagree with that. It really is nothing more than a nice2have thing as there is a constructor already that creates a vector3 from a vector2.

On a side note since those official vectors use SIMD! wouldnt they possibly have even better performance? I do think you need to use .NET core for that though but if we ever get there it might be worth looking into.

So checked it on .NET core 2.0 with the latest RyuJIT and first of all that compiler is alot faster. The (optimized) add operator that took 2ns in duality now takes just 0.75ns. If you use the official Vector3 it drops to 0.5ns.

**Comment by ilexp** [comment]
> On a side note since those official vectors use SIMD! wouldnt they possibly have even better performance? I do think you need to use .NET core for that though but if we ever get there it might be worth looking into.

Yes, they totally would, and we should look into it when the time comes. Related discussions from OpenTK on the same topic: [Issue 97](https://github.com/opentk/opentk/issues/97) and [Issue 401](https://github.com/opentk/opentk/issues/401). Further discussion should be moved to a distinct issue so we don't go too much off-topic in this one.

> Cannot disagree with that. It really is nothing more than a nice2have thing as there is a constructor already that creates a vector3 from a vector2.

Did a quick twitter poll on this, sort of a "conflicted" result there as well.

![](https://i.imgur.com/Z787RPZ.png)

I'd probably just postpone vector casting operators for now. It doesn't seem to be a clear decision either way and it's always easier to add later, than to deprecate and remove.

-----

Let's try to focus on the core points in this issue so we can address them and move on, while dealing with different points in separate issues.

## ToDo

- Add new `Rect` properties representing the middle on each of the four edges:
  - `Vector2 Top { get { ... } }`
  - `Vector2 Bottom { get { ... } }`
  - `Vector2 Left { get { ... } }`
  - `Vector2 Right { get { ... } }`
  - Note that the Width or Height of a rect can be negative, which should be taken into account similar to how it's done in the `LeftX` / `RightX` / ... properties.
- Add a `MathF.Clamp01` method.
- Add a `MathF.InvLerp` method.
- Add `MathF.SmoothStep(value)` and `MathF.SmoothStep(value, min, max)` methods

**Comment by Barsonax** [comment]
> I'd probably just postpone vector casting operators for now. It doesn't seem to be a clear decision either way and it's always easier to add later, than to deprecate and remove.

On top of that if you ever switch to System.Numerics.Vectors you will break ppl's code which will not have the casting operator that use our casting operator. It will probably break anyway in a few places but it might be good to align the API where possible to make that transition more smooth.

**Comment by superstewie** [comment]
> Cannot disagree with that. It really is nothing more than a nice2have thing as there is a constructor already that creates a vector3 from a vector2.

That seems to be a good solution to the problem on the surface, but it creates an exponential constructor problem, especially if more types are added. If you think about it, if you want to fix the problem with constructors, then we would need N * C constructors for each type, where N is the number of Vector types we want to be able to build from, and C is all the different parameter options for constructors.

Looking at Vector4 we can already see some early manifestations of this problem. A better, but still not perfect, solution might be to use a builder pattern to create vectors.

> Let's try to focus on the core points in this issue so we can address them and move on, while dealing with different points in separate issues.

If not already a WIP, your list seems to be a good place for me to start learning and contributing. Mind if I fork and take up adding Rect properties?

**Comment by ilexp** [comment]
> Looking at Vector4 we can already see some early manifestations of this problem. A better, but still not perfect, solution might be to use a builder pattern to create vectors.

Not a fan of builder patterns for a plain-old-data structure like a vector. I think for now we're fine with different constructors.

> If not already a WIP, your list seems to be a good place for me to start learning and contributing. Mind if I fork and take up adding Rect properties?

Saw you already opened and closed one, but if you're still up for it, sure!

**Comment by deanljohnson** [comment]
@helle253 Yep, nothing on that Todo list has been done yet. Have at it.

**Comment by helle253** [comment]
**Done:**
Added Rect properties representing the middle on each of the four edges.
Added MathF.Clamp01 method.
Added MathF.InvLerp method.
Added MathF.SmoothStep(value) and MathF.SmoothStep(value, min, max) methods

**TODO:**
More Functional Testing prior to PR. 


It should be ready for PR right quick.

**Comment by deanljohnson** [comment]
Make sure you handle negative dimensions and position on the rect properties - someone else tried to implement those once but wasn’t able to merge his code because of bugs when the rect had negatives.

**Comment by helle253** [comment]
Yup, I saw that mentioned previously in the thread. I believe I've got it right, I just haven't had a chance to ensure it is so.

I used the existing properties TopY, BottomY, LeftX, and RightX to get the farthest coordinates for the relevant edge. These already account for negative heights and widths, and I don't believe the new functions need to re-check for those cases.

**Comment by ilexp** [comment]
Remaining ToDos were done by @helle253. Closing this.
