### ISSUE TITLE
PolyShapeInfo - Object reference not set

### ISSUE THREAD

**Issue by LdsVegeta** [AdamsLair/duality#551]
### Summary

Upgrade 2015 project (VS 2010) to latest Duality version (VS 2017). Appears to be problem with the rigidbody configuration as clicking on the screen in certain places causes a error.

### How to reproduce [Bugs]

- Run project. It has 3 rigidbody gameobjects.
- Hold mouse down and click blank space which appears to somehow be trying to find a rigidbody??

### Analysis [Feature Requests]

Could an if null be added to the Duality code perhaps?

The custom code doesn't reference the rigid bodies at all anymore.

![capture](https://user-images.githubusercontent.com/30209067/28245862-2d4c56ca-6a53-11e7-9be0-cb67f5054ae6.PNG)

[Town.Scene.zip](https://github.com/AdamsLair/duality/files/1150898/Town.Scene.zip)

**Comment by ilexp** [comment]
Thanks for reporting! Not sure what's going on here, but this needs to be investigated for a potential bug. I'm putting this up for grabs, but will look into this in case no one else is interested.

**Comment by ilexp** [comment]
Found and fixed the issue, merged changes back to `v3.0` and prepared a release. Unfortunately, there is an [ongoing issue on the CI system](https://appveyor.statuspage.io/incidents/m2vdvw39kdk8) preventing me from actually publishing the fix, so we'll have to wait a bit.

That said, the root of the problem with the NullReferenceException is that you somehow ended up with RigidBody shapes that have a null reference as their internal vertices. Although it is possible to explicitly create a setup like this in game code, this shouldn't happen in a regular editor workflow. In either case, some investigation on your side as to how these empty shapes ended up there might be worthwhile if you run into something similar again.

Until then, you can also remove these empty / null shapes either using game code, or by manually editing the scene resource in a text editor and removing their ShapeInfo objects entirely. It's not great workflow-wise, but considering it should be impossible to end up with these kinds of empty / null shapes in the first place, I think it's an acceptable workaround for now.

**Comment by LdsVegeta** [comment]
Good call.

Removing the rigidbodies created in an old Duality fixed the errors. Woot!

Thanks.

**Comment by ilexp** [comment]
Release in progress. Check for package updates in about 15 minutes. Closing this.
