### ISSUE TITLE
Simple RenderToTexture

### ISSUE THREAD

**Issue by strubelz** [AdamsLair/duality#558]
### Summary

Add a better way to render to texture.

### Analysis [Feature Requests]

Currenly Duality uses RenderTargets to render to texture. This is fine when you use them in the editor, but becomes real problem when you need to do it dynamicly at runtime.

To render one frame with a shader to a texture you need to do this. At least I haven't found another way. (Code untested)

`            RenderTarget target = new RenderTarget();
            Texture tex = new Texture();
            tex.Size = new Vector2(100, 100);

            ContentProvider.AddContent(@"Data\Temp\tex.Texture.res", tex);
            target.Targets = new ContentRef<Texture>[] { ContentProvider.RequestContent<Texture>(@"Data\Temp\tex.Texture.res") };

            RenderTarget target2 = new RenderTarget();
            Texture tex2 = new Texture();
            tex2.Size = new Vector2(100, 100);

            ContentProvider.AddContent(@"Data\Temp\tex2.Texture.res", tex2);
            target2.Targets = new ContentRef<Texture>[] { ContentProvider.RequestContent<Texture>(@"Data\Temp\tex2.Texture.res") };

            BatchInfo batch = new BatchInfo();
            batch.Technique = ContentProvider.RequestContent<DrawTechnique>(@"Data/ExampleTechnique");
            //this wont work, because batch.Textures is a IEnumerable<KeyValuePair<string, Texture>>()
            batch.Textures = tex2;

            ContentProvider.AddContent(@"Data\Temp\target2.RenderTarget.res", target2);
            
            DrawDevice dev = new DrawDevice();
            dev.Target = ContentProvider.RequestContent<RenderTarget>(@"Data\Temp\target2.RenderTarget.res");

            Canvas canv = new Canvas(dev);
            canv.State.SetMaterial(batch);
            canv.FillRect(0, 0, 100, 100);`

Possible Solutions:
- Allow Renderer to change the target
- Add GameObject equivalents for Resources needed for shaders/RenderToTexture
- Add a simple new API for drawing to a FrameBuffer
- Maybe add a "Resource Prefab"?

### Attachments

- [Bugs] Complete Logfiles (if available)
- [Bugs] Screenshots (if applicable and useful)
- [Feature Requests] Mockup screenshots and sketches (if applicable and useful)

**Comment by ilexp** [comment]
You have a point that rendering to texture using the code above is pretty convoluted. However, you can already get a better experience for rendering to texture without any changes in Duality:

- You don't need to register resources and request them again to use them. The content providers purpose is to handle resolving IDs / paths to resource instances. If you have a local / private resource that isn't shared between objects, you can just new your resources and don't inform anyone.
- You can change the textures and config of a RenderTarget anytime. Just call [SetupTarget](https://github.com/AdamsLair/duality/blob/9a6c351fbaf0f7af2ce9d368d0d09342c82a122e/Source/Core/Duality/Resources/RenderTarget.cs#L127) after you make your changes.
- `BatchInfo.Textures` is assignable, as is `BatchInfo.MainTexture`, and there is also `BatchInfo.SetTexture`.
- You can set up a DrawDevice and related resources once on initialization, store and just re-use them, which can help with un-cluttering drawing code as well.
- Resources have an implicit cast to `ContentRef<T>` of their type, which can shorten a lot of code in situations like this.

Here's a [code excerpt](https://github.com/AdamsLair/duality/blob/9a6c351fbaf0f7af2ce9d368d0d09342c82a122e/Test/Core/Drawing/CanvasTest.cs#L259-L284) from the canvas rendering unit test:

```CSharp
private PixelData RenderToTexture(int width, int height, Action<Canvas> renderMethod)
{
	PixelData pixelData;

	using (Texture texture = new Texture(width, height, TextureSizeMode.NonPowerOfTwo, TextureMagFilter.Nearest, TextureMinFilter.Nearest))
	using (RenderTarget renderTarget = new RenderTarget(AAQuality.Off, texture))
	using (DrawDevice device = new DrawDevice())
	{
		device.Perspective = PerspectiveMode.Flat;
		device.VisibilityMask = VisibilityFlag.AllGroups | VisibilityFlag.ScreenOverlay;
		device.RenderMode = RenderMatrix.OrthoScreen;
		device.Target = renderTarget;
		device.ViewportRect = new Rect(renderTarget.Width, renderTarget.Height);

		device.PrepareForDrawcalls();
		{
			Canvas canvas = new Canvas(device);
			renderMethod(canvas);
		}
		device.Render(ClearFlag.All, ColorRgba.TransparentBlack, 1.0f);

		pixelData = texture.GetPixelData();
	}

	return pixelData;
}
```

It doesn't do any of the Resource and DrawDevice re-use that I'd advise you to do for efficiency reasons and its purpose is actually to extract pixel data and transfer it back to the CPU immediately, but I think it shows that rendering to texture doesn't have to look convoluted.

Closing this, as I hope that my answer addresses your issue. In case I missed something, just let me know.
