### ISSUE TITLE
Write a Wiki Article on "Plugin Handling"

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#561]
### Summary

Write a wiki article that deals with how Duality handles plugins and plugin reloads in the editor. This came up in a conversion on the chat, see [here](https://forum.adamslair.net/viewtopic.php?f=26&t=1182):

![conversation](https://user-images.githubusercontent.com/14859411/29723720-fa2548fa-89c5-11e7-86a7-8edd1ce3fb73.png)

### Analysis

- Core and editor plugins
- How they are loaded
- How they are re-loaded
- In which cases is a restart required and why
  - Why both need to be re-loaded when B depends on A and only A changes.
  - Why a restart is required on dependent reloads.
  - Why a restart is required on editor plugin reloads.
- Approaches to reducing the frequency of restarts.
  - Define a common, infrequently changed "base" plugin A, and let core plugin B and editor plugin C depend on it, but not on each other.

**Comment by BobGneu** [comment]
Do you mind if I do the exploration and put a draft together on this?

**Comment by ilexp** [comment]
Nope, feel free to look into this 👍

**Comment by ilexp** [comment]
[Moved](https://github.com/AdamsLair/duality-docs/issues/8) to the docs repo.
