### ISSUE TITLE
Canvas.FillPolygonOutline with negative width results in much too wide outline

### ISSUE THREAD

**Issue by FaithlessQ** [AdamsLair/duality#562]
### Summary

The use of `Canvas.FillPolygonOutline(Vector2[], float, float, float, float)` with a negative second parameter (width) will cause an incorrect outline which is not pixel correct to the specified negative width.

### How to reproduce [Bugs]

* Create a new Duality project
* Create a new component with the following code:
```
public class OutlineTest : Component, ICmpRenderer
{
  public float BoundRadius { get; }

  public void Draw(IDrawDevice device)
  {
    const float borderWidth = 5;
    const float minPos = 100;
    const float maxPos = 200;
    var canvas = new Canvas(device);

    canvas.PushState();
    canvas.State.ColorTint = ColorRgba.Red;

    // Polygon outer border
    canvas.DrawPolygon(new[] { new Vector2(minPos - borderWidth, minPos - borderWidth), new Vector2(maxPos + borderWidth, minPos - borderWidth), new Vector2(maxPos + borderWidth, maxPos + borderWidth), new Vector2(minPos - borderWidth, maxPos + borderWidth) }, 0, 0, 1);

    // Polygon position
    canvas.DrawPolygon(new[] { new Vector2(minPos, minPos), new Vector2(maxPos, minPos), new Vector2(maxPos, maxPos), new Vector2(minPos, maxPos) }, 0, 0, 1);

    // Polygon inner border
    canvas.DrawPolygon(new[] { new Vector2(minPos + borderWidth, minPos + borderWidth), new Vector2(maxPos - borderWidth, minPos + borderWidth), new Vector2(maxPos - borderWidth, maxPos - borderWidth), new Vector2(minPos + borderWidth, maxPos - borderWidth) }, 0, 0, 1);

    canvas.PopState();

    // Fill outer outline
    canvas.PushState();
    canvas.State.ColorTint = ColorRgba.White;
    canvas.FillPolygonOutline(new[] { new Vector2(minPos, minPos), new Vector2(maxPos, minPos), new Vector2(maxPos, maxPos), new Vector2(minPos, maxPos) }, borderWidth, 0, 0, 10);
    canvas.PopState();

    // Fill inner outline (wrong results here)
    canvas.PushState();
    canvas.State.ColorTint = ColorRgba.Blue;
    canvas.FillPolygonOutline(new[] { new Vector2(minPos, minPos), new Vector2(maxPos, minPos), new Vector2(maxPos, maxPos), new Vector2(minPos, maxPos) }, -borderWidth, 0, 0, 10);
    canvas.PopState();
  }

  public bool IsVisible(IDrawDevice device)
  {
    if ((device.VisibilityMask & VisibilityFlag.ScreenOverlay) != VisibilityFlag.None) return false;
    if ((device.VisibilityMask & device.VisibilityMask & VisibilityFlag.AllGroups) == VisibilityFlag.None) return false;
    return true;
  }
}
```
* Place the component on the scene
* Set the perspective of the main camera to flat and place the camera right above the now drawn rectangles

The component draws three polygons in red representing the intended polygon itself in its middle and the two borders, one outer border and one inner border. Both borders have the same distance to the intended polygon.

The white drawn outline is correct, because it touches the red outer polygon line and begins at the intended polying. In contrast the blue drawn outline begins at the intended polygon, but exceeds the red inner polygon by far. My expectation is, that even when using negative width at `Canvas.FillPolygonOutline` it draws a inner outline with correct pixel width.

### Workaround [Bugs]

No clean workaround is known. You can only try to adjust the negative width with a number which will result in the desired inner outline. For the sample used dividing the negative width with 7.065f will produce an acceptable result. But this does not seem to work for other shapes.

### Attachments

![innerpolygonoutlinebug](https://user-images.githubusercontent.com/30325942/29752769-6156ba82-8b64-11e7-906e-9457f03ff3e4.jpg)

**Comment by ilexp** [comment]
Thanks for your bug report and thorough description! It seems you found an "API bug", as negative widths are not supported. Instead, use the in / out factor in [this overload](https://github.com/AdamsLair/duality/blob/b6cebd62f29c918fc6ee3537eca387994754ea58/Source/Core/Duality/Drawing/Canvas.cs#L687-L690) of the fill outline method to control which side the outline is on.

The fix to be introduced will likely check width in [FillThickOutline](https://github.com/AdamsLair/duality/blob/b6cebd62f29c918fc6ee3537eca387994754ea58/Source/Core/Duality/Drawing/Canvas.cs#L1303) and invert the in / out factor and itself when it's negative.

**Comment by ilexp** [comment]
Negative widths are now automatically re-interpreted as positive widths with a flipped in / out factor. Release in progress.

**Comment by FaithlessQ** [comment]
Thanks for fixing this issue :) Negative width now creates a correct inner outline.
