### ISSUE TITLE
Build with AnyCPU does not work

### ISSUE THREAD

**Issue by jangofett4** [AdamsLair/duality#564]
I just downloaded precompiled version of the Duality from official site. Dualitor was just closing after I open it.
I downloaded the source code and compiled it with AnyCPU configuration it did not work either.
I created and changed configuration to x86, it worked, created and changed configuration to x64, worked too. But with a cost, Plugins were not copied, so duality fall into Dummy backend.
What is the problem with AnyCPU, And why the precompiled version did not work?

**Comment by ilexp** [comment]
> I just downloaded precompiled version of the Duality from official site. Dualitor was just closing after I open it.

This is a strong indication for a general compatibility issue. To find out more, please upload or copy-paste the editor logfile (`logfile_editor.txt`) just after you reproduced this behavior.

However, I compile Duality with AnyCPU by default, and so do the release builds that end up in NuGet, and so does the continuous integration as well. I think it is more likely that this is a specific issue related to your machine or software / system setup, and not one related to the project itself. As such, please move this issue into a forum thread, which is better suited for support questions than a GitHub issue :)

When you do, please include the mentioned logfile and Visual Studio version you're compiling this with. System specs are included in the logfile, so you can skip those unless you have a very unique / special system.
