### ISSUE TITLE
Write more prominent log messages when no backends are found

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#565]
### Summary

When no backends are found, tiny, easy to miss log messages are written:
```
[Core] Msg: Initializing ISystemBackend...
[Core] Msg:   No system backend...
[Core] Msg: Initializing IGraphicsBackend...
[Core] Msg:   No Graphics...
[Core] Msg: Initializing IAudioBackend...
[Core] Msg:   No Audio...
[Core] Msg: Initializing IEditorGraphicsBackend...
[Core] Msg:   No Editor Graphics...
```
Shortly after, things collapse in a cascade of exceptions.

It might be better to make these log messages more prominent instead, and note that this may result in issues?

I understand that there is no special case handling where no backend is found; it's just the dummy backends' names that are printed, not actual warnings. This means it won't be easy to make them into warnings or errors.

### Analysis

- This may potentially help users identify why their Duality setup crashes easier.
- *However*, making them warnings/errors might throw off people working on headless versions of Duality with plugins intentionally missing.
- The no-brainer approach would be to add "this may cause issues with Duality" to the messages. Perhaps in all caps to be more eye-catching?
```
[Core] Msg: Initializing ISystemBackend...
[Core] Msg:   No system backend (THIS MAY CAUSE ISSUES WITH DUALITY)...
[Core] Msg: Initializing IGraphicsBackend...
[Core] Msg:   No Graphics (THIS MAY CAUSE ISSUES WITH DUALITY)...
[Core] Msg: Initializing IAudioBackend...
[Core] Msg:   No Audio (THIS MAY CAUSE ISSUES WITH DUALITY)...
[Core] Msg: Initializing IEditorGraphicsBackend...
[Core] Msg:   No Editor Graphics (THIS MAY CAUSE ISSUES WITH DUALITY)...
```
- Preferably, though, these cases should be a warning (or error?).

Thoughts?

**Comment by mfep** [comment]
I think the all caps solution is somewhat weird - in an unprofessional manner. I think that the best thing we could do is to promote these messages to the *warning* status.

**Comment by ilexp** [comment]
Good call. There should be some warning message indicating that this can be a serious problem. Probably can be logged as an additional line in the init method of each of the dummy backends, which is called when they are actually used.

**Comment by hsnabn** [comment]
Oh yes, I'd completely forgotten about the init methods. They look like a good spot for a warning to be logged, yeah.

**Comment by SirePi** [comment]
me?

**Comment by ilexp** [comment]
There you go. Awaiting PR. 👍

**Comment by SirePi** [comment]
well that was fast :D
something like this would do?
`Log.Core.WriteError("DummyGraphicsBackend initialized. This shouldn't happen and the game will not work properly");`

**Comment by ilexp** [comment]
I'd go with a warning, since it is in fact not an error in itself. It just might cause errors down the line when happening unintended. Also would probably adjust the message with that in mind, e.g. don't write "it will not work properly", but something along the lines of "this is unusual and may cause problems when someone tries to do X".

**Comment by ilexp** [comment]
Implemented by @SirePi
