### ISSUE TITLE
Introduce a Subdirectory for Non-Plugin, Non-Executable Binaries

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#578]
### Summary

In the course of issue #574, it became apparent that the NuGet update will introduce a large number of additional binaries to the Duality runtime. Keeping them all in the main directory is not very nice to work with, but as the project grows and matures, this might not remain restricted to NuGet only. To fix this, introduce a new binary subfolder next to `Plugins` where all non-plugin, non-executable binaries are stored.

### Analysis

- Update project settings to the build output is matching the new folder structure. Maybe also fix the OpenTK library location to match the actual binary installation (currently in Plugins, isn't actually in there in a binary install).
  - Could be a bit tricky since the regular build thing is to have all output assemblies and their dependencies in the same folder.
  - The test setup matching the real one would be nice, but it's not vital as long as the implementation is done in a way that it doesn't matter. So try it, but don't get stuck trying.
- The `DefaultAssemblyLoader` will need to be updated with regard to the assembly search paths.
- All `PluginManager` implementations need to be updated so they don't try to load all available assemblies as plugins, but only those in the `Plugins` folder, if they're not already doing that.
- The existing `AssemblyResolve` handler needs to be extended to search in the new subfolder as well.
  - Make sure to load `.pdb` files too, where available.
- Update the package manager code and tests with the new file mappings.
- Need to update the `Publish Game` dialog / publish script.
- Update the plugin project template, also check the code that updates it at runtime.
- Potential names:
  - `Assemblies`, too generic. Plugins and executables are assemblies too.
  - `Binaries`, too generic. Plugins and executables are binaries too.
  - `Libraries`, probably the best one so far. Maybe shorten to `Libs`?
  - ?

**Comment by Barsonax** [comment]
CoreLibraries? As this doesn't seem to be something the user himself will be managing but something that's needed for duality to function.

**Comment by ilexp** [comment]
> CoreLibraries? As this doesn't seem to be something the user himself will be managing

If any of the installed packages contain non-Duality assemblies, or depend on them, they'll go in there as well, so it won't be Duality-only libraries in there.

**Comment by ilexp** [comment]
### Progress

- Created a new `develop-3.0-libs-dir` branch to work on this.
- Introduced a new `Libs` subdirectory to be searched for static, non-plugin dependencies in the same way as regular Assembly search paths by the runtime.
- Chose to implement this transparently in the `DefaultAssemblyLoader`s resolve handler before doing anything else. That way, the entire change is invisible to plugin loading code and no adjustments need to be made there.

### Immediate ToDo

- Update project settings to the build output is matching the new folder structure.
  - Might need to introduce an intermediate build output directory for all libraries, combined with postbuild copy and adjusted debug settings.
  - Postbuild commands previously caused problems when building in Xamarin Studio on non-Windows systems. Avoid them.
  - Instead, use `msbuild` copy commands via `csproj` to achieve the same without any command lines.
- Update the package manager code and tests with the new file mappings.
- Update the `Publish Game` dialog / publish script.
- Update the plugin project template, also check the code that updates it at runtime.

**Comment by ilexp** [comment]
### Progress

- [Updated project files](https://github.com/AdamsLair/duality/commit/3a15b0e00ecf89ca4ba027beaab608895a3e0eb2) to create a build output that matches the new folder structure using msbuild copy commands.
- [Fixed startup problems](https://github.com/AdamsLair/duality/commit/3579c77c7fa24e642d194c3e0575c36492b664ce) due to attempting to resolve Duality assemblies before the resolve handler was in place.

### Immediate ToDo

- As it turns out, this new setup has several problems.
  - Using _any_ dependency will crash the application when accidentally done before the assembly resolve handler is in place. This can happen quite easily and reduces the overall stability of the project. The alternative of depending on a config file to add another probing path is kind of ugly, and it is unclear whether this config file is evaluated consistently across runtimes.
  - The VS Test Explorer can no longer run tests as-is, as there is no easy and robust way to change the working directory they're executed in, and requiring to do so makes it more difficult to run tests in VS, NUnit and AppVeyor environments.
- Both of the above have a noticeable negative impact on maintenance while the overall issue is mostly about convenience and "look and feel" of the Duality folder structure.
  - Consider closing the issue as wont-fix and discarding the work that has been done so far.
  - Consider alternatives.

**Comment by ilexp** [comment]
Salvaged the explicit output aggregate changes for a `develop-3.0` commit in order to clean up the output directory and make sure no assemblies end up in `Plugins` by accident.
