### ISSUE TITLE
Packagemanager tests does not handle spaces in the path

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#581]
### Summary

If there is a space in the path to your output folder the unit tests for the package manager will fail. 
This is because PackageManager.CreateRepository is replacing the spaces with a %20 which in turn makes the repository unable to find the path. The Uri class is responsible for this as the Uri.AbsolutePath is putting these %20 in the repositoryUrl. See [PackageManager.CreateRepository](https://github.com/AdamsLair/duality/blob/master/Source/Editor/DualityEditor/PackageManagement/PackageManager.cs#L689)

The solution is to unescape the uri with Uri.UnescapeDataString.

### How to reproduce [Bugs]

- Clone duality and make sure the path to the output folder has a space somewhere in its name
- Try to run the package manager unit tests (such as GetPackage)
- Profit

### Workaround [Bugs]

- Make sure you don't have a space in the path to the output folder

**Comment by ilexp** [comment]
Fixed by in PR #581.
