### ISSUE TITLE
Consider using matrices for transformation methods in the Transform component

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#595]
### Summary

See if its worth it to use matrices in the Transform component that can be reused across calculations as long as properties like position, scale and rotation do not change. The current idea is to add 2 matrices to the Transform component: 1 local and 1 world matrix. Since the Transform component is only interested in 2d 3x3 matrices would suffice. Once the matrix is built transforming a vector3 or vector2 will consists of only some multiplications and additions.

At this point its not clear yet what the best way is to integrate this into the Transform API. Should it be used under the hood or be exposed as a separate property for 'batch' operations? 

First focus on researching if its actually worth it and implement this as separate properties with no caching. The test code will handle the caching for now.

### Analysis
- Would avoid repeately calling expensive operations such as sin and cos. Most of the gains would be in batch operations. Though I suspect that if its reused even once it will outperform the current implementation.
- Would avoid having to cast to Vector3 when transforming a Vector2.
- Possibly cleanup the code a bit by moving some of the calculations out of the Transform component

**Comment by ilexp** [comment]
Still skeptical as to whether this would pay off in the end when considering performance, but would be open to take a look at a prototype implementation and profiling results.

Some first thoughts:
* Public API should remain the same at first.
* There will need to be inverse matrices in addition to the regular ones to do inverse transform operations.
* Transformation is still a 3D operation - even though rotation only happens around the Z axis (2D), we do have 3D coordinates for translation. That means we need a 4x4 matrix for transformation.
* With between two and four 4x4 matrices added, memory footprint could become a concern. In addition to performance, memory size should be compared as well.

While a matrix-only implementation could be cleaner and more recognizable to contributors than the current specialized transformation code for Z rotation, scale and offset, that's still a lot of math and memory we don't actually need in our special case.

> See if its worth it to use matrices in the Transform component that can be reused across calculations as long as properties like position, scale and rotation do not change.

If caching is the main concern of this issue, we could actually just cache the `MathF.GetTransformDotVec` results for XY rotation + scale, which is essentially a 2x2 matrix and handle the translation separately. This wouldn't require restructuring all internals to use matrices and could be some middle ground. 

In this case too, memory footprint change and performance should still be evaluated.

**Comment by Barsonax** [comment]
In a console application that referenced duality I managed to get a tenfold increase in performance for big batches when using a 4x4 matrix. The break even point is around 6 reuses.

However keep in mind its currently creating alot of 4x4matrices (4 I believe) that are discarded as soon as it builds the composite matrix so I suspect this overhead could be reduced quite alot. This is the current code for building the matrix:
`		public static Matrix4 BuildLocalTransformMatrix(Vector3 translation, float scale, float rotation)
		{
			var rotationMatrix = Matrix4.CreateRotationZ(rotation);
			var translationMatrix = Matrix4.CreateTranslation(translation);
			var scaleMatrix = Matrix4.CreateScale(scale);
			return translationMatrix * rotationMatrix * scaleMatrix;
		}`

**Comment by ilexp** [comment]
@Barsonax Can you share the full code of the benchmark in order to interpret the results?

**Comment by Barsonax** [comment]
I have included 3 benchmarks: the 2 transformation benchmarks and a matrix build benchmark.

[DualityMatrixTransform.zip](https://github.com/AdamsLair/duality/files/1587663/DualityMatrixTransform.zip)

On my machine I get these results:
![image](https://user-images.githubusercontent.com/19387223/34361613-e82449c4-ea6b-11e7-9e22-e649e5de5f96.png)

**Comment by ilexp** [comment]
That looks pretty good - must admit, I wouldn't have expected the matrix variant to be so much faster for transformation. The build matrix example could likely be optimized quite a bit too, since the kind of matrix that is needed is limited and known in advance, so I'd be optimistic on that one.

On the skeptic side, we might need to build 2-4 matrices on transform changes, and another point remaining is the one of `Transform` memory overhead by the amount of matrices stored internally. Both of them could be solvable problems though. 

We might find out more proceeding with a with a full prototype implementation. To get a solid side-by-side comparison, this could be done by copy-pasting the full Transform component into a matrix variant for testing, which can then be adjusted step by step while continuously being compared to the old version.

**Comment by Barsonax** [comment]
Could be worth to check if its worth just caching the sin and cos values instead of a full 4x4 matrix. Remember all we do here is caching the calculated values so a full matrix might be overkill for just that.

**Comment by ilexp** [comment]
Sounds similar to what I meant by going with a `MathF.GetTransformDotVec` caching approach, but extended to storing _only_ the sin and cos values, further cutting this down from 4 values to 2 values. At this point it would also cease to be a "proper math" cleanup issue and should be treated as a "performance vs. memory" tradeoff. Could be worth looking into it, need to get some data on how frequent the sin / cos values are used in real world scenarios.

**Comment by Barsonax** [comment]
Jup at this point this issue is petty much only for extra performance. I dont know how often ppl use these methods. 60 ns is still very fast so it might not be needed to do this optimization.

Still I was curious how far I could push it. Writing it all out like below results in 2.2 ns per operation on my machine:
`
public Vector3 NewTransformBenchmark2()
{
	var lastX = _vector.X - _position.X;
	var x = (lastX * _cachedCos - (_vector.Y - _position.Y) * _cachedSin) * _inverseScale;
	var y = (lastX * _cachedSin + (_vector.Y - _position.Y) * _cachedCos) * _inverseScale;
	var z = (_vector.Z - _position.Z) * _inverseScale;

	return new Vector3(x, y, z);
}
`
Without crazy stuff like SIMD I dont think you can get much faster than this.

**Comment by Barsonax** [comment]
Added (way) faster transformation methods to Transform for:
- GetWorldPoint vector2
- GetWorldPoint vector3
- GetLocalPoint vector2
- GetLocalPoint vector3

Below are some benchmarks:
<img width="535" alt="2018-01-01 20_13_20-c__users_rick-_source_repos_dualitytransformbenchmark_transformbenchmark_bin_rel" src="https://user-images.githubusercontent.com/19387223/34470498-b6fd3010-ef32-11e7-9276-6306968c98e0.png">
<img width="532" alt="2018-01-01 20_24_47-c__users_rick-_source_repos_dualitytransformbenchmark_transformbenchmark_bin_x64" src="https://user-images.githubusercontent.com/19387223/34470499-b941ccfa-ef32-11e7-8ec5-9c998234e5a6.png">

**Comment by ilexp** [comment]
Do you have a branch I can compare to master or develop-3.0 to get a quick overview on the implementation side?

**Comment by Barsonax** [comment]
This one: https://github.com/Barsonax/duality/tree/%23595 (based on master)

Still have to cleanup/test though but the general idea is there.

**Comment by ilexp** [comment]
Alright, if you're up for it, I think we can get your optimizations into `master`. Some requests for the PR:

- Keep `inverseScale` out of this for now. First iteration should be cached sin / cos only, nothing else.
- The `rotationMatrix` vector is not actually a rotation matrix. Please find a different name to match, like `rotationVec`, `rotationDir` or similar.
- Keep all changes to the `Transform` class itself, no `Vector2` API additions or changes for now. Those would be another thing to discuss, and one that I don't want to start right now for the sake of being able to proceed on this issue 😄 
- Extend the [Transform test](https://github.com/AdamsLair/duality/blob/de927f8f15547e396ae6cb90c0f6ad3879621c3b/Test/Core/Components/TransformTest.cs#L17) setup with one test for each transformation method we're touching here, each testing various position / rotation / scale setups.

Maybe just create a different branch for the PR, so we don't interfere with your existing prototype branch. Let me know if you're on it, considering my change requests.

**Comment by Barsonax** [comment]
Nice name for the rotation. Wasn't entirely sure already about the name rotation matrix.

Could just do it on this branch. The commit will always be there if you wanna go back (though if you want to keep it out if the history thats also a con).

Ill will copy the methods out of the vector classes and into transform.cs as private methods to not change any public API while still keeping it encapsulated. I don't think that will be the final place as the functionality is very generic and could be used in other places as well but thats another discussion.

Tests will have to be added/changed.

**Comment by ilexp** [comment]
Merged the PR on this issue. Closing.
