### ISSUE TITLE
Cleaning up math classes

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#598]
### Summary

This issue is to see if there are any cleanup that can be done to the math code (DualityPrimitives/Math) such as Vector2. For any conveinence suggestions go to this [issue](https://github.com/AdamsLair/duality/issues/550).

**Suggested cleanups:**
1. Remove ref parameters if possible for small structs (=< 12 bytes). 
**Description:**
I believe in most cases these are used for performance reasons to prevent copying structs however I benchmarked some and it doesnt seem to make any difference for Vector2 and a very tiny bit (0.1ns) for vector3. This might vary by machine though and benchmarking this more thoroughly to verify this wouldn't hurt.
**Impact:**
Though the changes are trivial this will change the public API. It will also introduce a difference between small struct API's (Vector2, Vector3) and larger struct API's (Vector4). However once duality upgrades to C# 7.2 this might be completely solved with the in keyword (a readonly ref) so it would be better to wait until then.

2. Remove duplicate arithmetic code from Vector2, Vector3, Vector4
**Description:**
Things like multiplying a vector with a float are implemented both in a operator and as a static method. Might be worth providing just one way to do this or make sure they use the same code.
**Impact:**
Depending on the approach taken might change the public API.

3. Fix the code style
**Description:**
There are quite alot of code style errors (mostly this. is missing) in the math classes. Fix this.
**Impact:**
None

Feel free to suggest more changes. If you do not agree with one of the proposed changes thats fine too they are just idea's so far.

**Comment by ilexp** [comment]
> Remove ref parameters if possible for small structs (=< 12 bytes).

Yes, the goal here is performance. Would value consistency between Vector2/3/4 over case-by-case adjustments here and keep the `ref` versions for now. Switch to `readonly ref` / `in` at some point, but that's a different issue.

> Remove duplicate arithmetic code from Vector2, Vector3, Vector4

Removing the non-`ref` versions sounds reasonable, as they're the same as the operators. The non-breaking way would be to flag them as obsolete in `master` and remove them in `develop-3.0`. Investigate the impact of this first.

> Fix the code style

👍

**Comment by Barsonax** [comment]
> Yes, the goal here is performance. Would value consistency between Vector2/3/4 over case-by-case adjustments here and keep the ref versions for now. Switch to readonly ref / in at some point sounds good, but that's better dealt with in a separate issue after the core / internally used C# version was bumped so we don't stall this one until then.

Sounds good, I checked it and the in keyword works with operators too (the ref keyword doesn't) so if we ever switch to C# 7.2 it would be possible to remove all those methods and just provide the operators without having to do any copying overhead concessions. 

Outside the operators there are currently no non ref versions so cant really cleanup anything.

So that just leaves the code style issues

**Comment by ilexp** [comment]
> Sounds good, I checked it and the in keyword works with operators too

Ohh, didn't know that. Nice!

> So that just leaves the code style issues Done

I'll take a look at your PR as soon as I manage so we can wrap this up then. We should create a reminder issue for the `in` keyword operator change after switching core to C# 7.2 at some point in the future. Feel free to open one, otherwise I'll take care when we wrapped up the PR.
