### ISSUE TITLE
Re-Think Transform Component Implementation

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#601]
### Summary

The current implementation of the Transform component [is quite bloated](https://github.com/AdamsLair/duality/blob/master/Source/Core/Duality/Components/Transform.cs) and not as fast as a component used this often should be. A brief [attempt at simplifying it](https://github.com/AdamsLair/duality/issues/576) was made, but yielded no results. Re-approach the topic by rethinking how a Transform component should be done if there wasn't one already.

### Analysis

- Implement lots of unit tests for Transform before beginning any implementation.
- Is `deriveAngle` used anywhere? Remove it otherwise.
- Can transformation change events be removed?
  - Their main purpose is ensuring safe interaction between RigidBody and Transform so they always remain synced up.
  - With the implementation of deterministic component update order, this can potentially be solved differently.
- Can velocity values be removed?
  - It was established during #576 that a distinction between moving to X and teleporting to X is required, so the answer is generally "no".
  - However, an alternative implementation using last / current values would be viable, if that was preferable for some reason.
- Can the `tempVel` accumulation values be removed?
  - Depends on the exact outcome of velocity value removal or adjustment, but potentially yes.
  - Their main purpose was to ensure stable velocity values over the current frame as different objects adjust Transform position in any order.
  - With the implementation of deterministic component update order, this might no longer be necessary.
- Can absolute values be removed?
  - They're derivative and can always be calculated from relative values plus object hierarchy.
  - This would save object size / memory, but would require calculating them on access.
  - If it's fast enough, it might still be worth it. If it isn't, keep them.
- Is it possible to make Transform no longer implement `ICmpUpdatable`?
  - Probably not, as long as there are velocity values to be maintained.
- If not, is there any way to adopt an array-of-structs approach internally without public API changing in any way?
- With an updated, simplified Transform implementation, make sure to [fix parent rotation velocity behavior](https://github.com/AdamsLair/duality/blob/1dd4802fe1fd0a0c3b31d726a88183656addb45f/Test/Core/Components/TransformTest.cs#L242-L245) and reactivate their tests.

**Comment by Barsonax** [comment]
Some work has been done to make the transformation methods (like GetLocalPoint) faster in #595. Notably sin and cos values are now calculated when the rotation changes in order to prevent recalculating these everytime you had to transform a point. There might be a bit more to gain but the end result is these methods now execute in less than 10ns at the cost of having to calculate these when changing the rotation. I think this will help alot in keeping the performance high when if remove the absolute values.

A observation I made while rewriting the transformation methods is that writting the calculation out instead of combining separate methods for each operation (like translation, rotation and scaling) can make a difference. This is a micro-optimization and it will lead to duplicated code but there might be cases where this is worth it. Do not always count on the compiler optimizing/inlining the calculations as it seems to be a bit conservative in this regard. I seen this making a difference of ~2x in alot of cases and it happens both in the legacyJIT and RyuJIT.

**Comment by ilexp** [comment]
### Progress

- Started working on this is the `feature/3.0/refactor-transform` branch.
- Removed `DeriveAngle` without replacement, as it was a 0.1% feature that can be easily added with a custom Component.
- Removed `EventTransformChanged` without replacement for the same reason. Rewrote RigidBody update-from-Transform code to work without relying on the now removed event.
- Removed change flags, as they were no longer necessary.
- Attempted to simplify velocity calculations to operate in world space only, but reverted because derived velocities wouldn't work that way.
- Attempted to move velocity calculations into a separate VelocityTracker component, but reverted for complexity reasons.

### Immediate ToDo

- Consider simplifying velocity calculations into using a "last pos" / "current pos" form, and velocity information into world space only.
  - Movement doesn't update last values, generating velocity.
  - Teleportation updates last values, resetting velocity to zero.
  - This will lose pre-teleport velocity information, but is that really an issue?
  - If it is, teleport updates could still update last values to match, so velocity is retained.
- Investigate whether `ICmpUpdatable` can be removed from Transform.
- Investigate removing absolute values from Transform.

**Comment by ilexp** [comment]
### Progress

- Adopted a "last pos" / "current pos" velocity calculation approach and restricted it to using world space values only, removing all local space velocity calculation fields.
- Velocity values are no longer serialized.
- Added and updated some Transform unit tests.

### Immediate ToDo

- Consider renaming all "RelativeXY" style properties and methods with "LocalXY".
- Write unit tests for transform changes when switching object parents.
- Investigate removing absolute values from Transform.
  - Watch out for parent change operations in code and editor. They're currently implemented so that absolute transform values remain, while relative values are recalculated. This is no longer possible within Transform when there are no fields for absolute values.
  - Editor code will need to be adjusted to explicitly retain world space transform values.
  - Introducing some API to do the same via code would be nice.
- Investigate whether `ICmpUpdatable` can be removed from Transform.
  - The only blocker for this is velocity calculation.
  - After velocity calculations have now been simplified a lot, reconsider moving them into a separate `VelocityTracker` component.

**Comment by ilexp** [comment]
### Progress

- Renamed public Transform API to match the new "Local" / "World" space terminology.
- Updated Transform XML comments to match the renamed API, but also clarified some members that didn't have a good description before.
- Switched the editor default from editing world space values to editing local space values.
- Added a unit test to check for Transform behavior when switching parent objects.

### Immediate ToDo

- Investigate removing absolute values from Transform.
  - Watch out for parent change operations in code and editor. They're currently implemented so that absolute transform values remain, while relative values are recalculated. This is no longer possible within Transform when there are no fields for absolute values.
  - Editor code will need to be adjusted to explicitly retain world space transform values.
  - Introducing some API to do the same via code would be nice.
- Investigate whether `ICmpUpdatable` can be removed from Transform.
  - The only blocker for this is velocity calculation.
  - After velocity calculations have now been simplified a lot, reconsider moving them into a separate `VelocityTracker` component.

**Comment by ilexp** [comment]
### Progress

- Started with an experimental `VelocityTracker` implementation and moved all velocity related code from `Transform` into it. `Transform` is no longer an updatable component.
- Adjusted all code that relied on `Transform` velocity to instead use or requrie a `VelocityTracker`.
- Adjusted all sample projects (except DualStickSpaceShooter) to have `VelocityTracker` components where they are required.
- Found a few bugs after the recent `Transform` changes, to be fixed before proceeding.

### Immediate ToDo

- Fix `RigidBody` behaviour in certain parent / child scenarios. Can be reproduced in the physics sample, check out Pulley-, Friction-, Distance- or AngleJoint sample scenes.
- Fix Prefab changelists with regard to Transform values. Can be reproduced in the DualStickSpaceShooter and Steering samples.
- After the above fixes, adjust the DualStickSpaceShooter main scene to use `VelocityTracker` where needed.
- Adjust the `Scene View` icon choosing algorithm to take a hint from the object name too, so "Camera" objects don't look like a microphone, because "SoundListener" happens to have the larger dependency hierarchy.
- Investigate removing absolute values from Transform, or (if keeping them) not serializing absolute values anymore.
  - Watch out for parent change operations in code and editor. They're currently implemented so that absolute transform values remain, while relative values are recalculated. This is no longer possible within Transform when there are no fields for absolute values.
  - Editor code will need to be adjusted to explicitly retain world space transform values.
  - Introducing some API to do the same via code would be nice.

**Comment by ilexp** [comment]
### Progress

- Fixed Prefab changelist entries that were still referring to the old `RelativeXY` naming.
- Fixed `DualStickSpaceShooter` sound listener not having a `VelocityTracker`.
- Added an icon and XML docs for the `VelocityTracker` component.
- Adjusted the `Scene View` to take object naming into account when choosing a representative component icon.

### Immediate ToDo

- Fix `RigidBody` behaviour in certain parent / child scenarios. Can be reproduced in the physics sample, check out Pulley-, Friction-, Distance- or AngleJoint sample scenes.
- Investigate removing absolute values from Transform, or (if keeping them) not serializing absolute values anymore.
  - Watch out for parent change operations in code and editor. They're currently implemented so that absolute transform values remain, while relative values are recalculated. This is no longer possible within Transform when there are no fields for absolute values.
  - Editor code will need to be adjusted to explicitly retain world space transform values.
  - Introducing some API to do the same via code would be nice.

**Comment by ilexp** [comment]
### Progress

- Adjusted `Transform.IgnoreParent` implementation so it matches behavior when there actually is no parent. Local transform properties will return and accept world values while `IgnoreParent` is active, as they would when there was no parent.
- Added a new test case to verify `IgnoreParent` behavior.
- Minor bugfix in `RigidBody` to avoid erratic update-from-Transform calls due to rounding errors when comparing last to current transform values. There still seems to be some problem with regard to angle handling.

### Immediate ToDo

- Fix `RigidBody` rotation behavior in certain parent / child scenarios. Can be reproduced in the physics sample, check out AngleJoint sample scene.
- Verify that the new `IgnoreParent` behavior doesn't introduce new bugs. Check movement-related sample projects:
  - All physics sample scenes.
  - DualStickSpaceShooter
  - FlapOrDie
  - Steering
  - AudioHandling
  - CameraController
- Investigate removing absolute values from Transform, or (if keeping them) not serializing absolute values anymore.
  - Watch out for parent change operations in code and editor. They're currently implemented so that absolute transform values remain, while relative values are recalculated. This is no longer possible within Transform when there are no fields for absolute values.
  - Editor code will need to be adjusted to explicitly retain world space transform values.
  - Introducing some API to do the same via code would be nice.
- Do a full benchmark run before / after to see the perf impact of the cleanup.

**Comment by ilexp** [comment]
### Progress

- Identified the RigidBody problem as a bug in `MathF.CircularDist`, which was introduced in a recent optimization.
- Fixed the above bug, all physics samples now work as expected.
- Checked all movement-related sample project (listed above) and verified that they all work as expected with the new `IgnoreParent` behavior.

### Immediate ToDo

- Investigate removing absolute values from Transform, or (if keeping them) not serializing absolute values anymore.
  - Watch out for parent change operations in code and editor. They're currently implemented so that absolute transform values remain, while relative values are recalculated. This is no longer possible within Transform when there are no fields for absolute values.
  - Editor code will need to be adjusted to explicitly retain world space transform values.
  - Introducing some API to do the same via code would be nice.
- Do a full benchmark run before / after to see the perf impact of the cleanup.

**Comment by ilexp** [comment]
Thinking a bit more about the removal of world space transform fields:

### Remove Abs Fields Completely

- Every call to world space value properties will require a recalculate.
- It will be fast, but stack up quickly in parent-child hierarchies. If there are 6 hops from object to root, a single get of the position property will require to recalculate the *full* world transform of all six objects.
- With this in mind, there definitely should be a cached world space value for performance reasons.

### Keep Abs Fields, Don't Serialize Them

- As discussed above, this would require an "abs available" flag, so initialization out of order will work properly.
- Shrinks serialized data, but adds slightly more load to runtime data and increases init complexity.

### Keep Abs Fields As-Is

- No changes necessary.
- Probably the best course of action, unless there is a more serious reason to remove the world space fields than minimalism.

**Comment by ilexp** [comment]
### Progress

- Did a full benchmark run to compare before / after:
  - [BenchmarkReportBefore601.txt](https://github.com/AdamsLair/duality/files/1754172/BenchmarkReportBefore601.txt)
  - [BenchmarkTestReportAfter601.txt](https://github.com/AdamsLair/duality/files/1754173/BenchmarkTestReportAfter601.txt)
  - Average frame times went down between 1.4 and 2.0 ms for 10k objects. Rendering and update of 10k sprite renderers with varying materials now under 7 ms per frame.
- Merged back to `develop-3.0`
