### ISSUE TITLE
Extract flood fill algorithm from FillTilemapTool

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#612]
At the moment the [flood fill alogrithm](https://github.com/AdamsLair/duality/blob/7febba7196982e9fa7903a501378bf6e121157fe/Source/Plugins/Tilemaps/Editor/CamViewStates/TilemapTools/FillTilemapTool.cs#L121-L316) is implemented directly in the fill tilemap tool. 

It would be clever if this alogrithm would be extracted, because you could reuse this code for other tilemap tools like a magic wand selection tool.

**Comment by ilexp** [comment]
Sounds good. Would be important to make sure that we don't introduce any performance downgrade by abstracting too much, since the flood fill is actually a bottleneck for very big maps. Do you have a design proposal for this?

**Comment by Barsonax** [comment]
Is it just me or does the flood fill looks overly complex? Shouldnt it be a simple BFS algorithm?

**Comment by ChristianGreiner** [comment]
> Do you have a design proposal for this?

Maybe we could create a new class called `FloodFillArea` inside the [Utility](https://github.com/AdamsLair/duality/tree/7febba7196982e9fa7903a501378bf6e121157fe/Source/Plugins/Tilemaps/Editor/Utility) folder and move all methods and stuff from the FillTilemapTool into this class. 

Any other suggestions?

**Comment by ilexp** [comment]
The Utility folder you linked is part of the editor plugin like the current place of the algorithm. I think this will be more useful if we find a core plugin location for the algorithm, similar to [TilemapCulling](https://github.com/AdamsLair/duality/blob/7febba7196982e9fa7903a501378bf6e121157fe/Source/Plugins/Tilemaps/Core/Tilemaps/TilemapCulling.cs). Maybe call the class TilemapFloodFill and put it next to it?

**Comment by deanljohnson** [comment]
This one is done, right? (https://github.com/AdamsLair/duality/pull/627)

**Comment by ilexp** [comment]
It has. Thanks! Closing this.
