### ISSUE TITLE
Steering Sample - Agent Comment Errors and Typos

### ISSUE THREAD

**Issue by deanljohnson** [AdamsLair/duality#614]
### Summary

In the Steering Sample project, the Agent class has a few errors in it's XML comments. Most significantly Agent.TargetPos has an incorrect Summary comment. It seems to be copy and pasted from Agent.TargetVel.

### Analysis
Errors include:
- TargetPos Property - copied from TargetVel. Perhaps it should be "[GET / SET] The Agents target position, i.e. the position it moves toward while avoiding other agents."
- Class Comment - 'get stuck' rather than 'gets stuck'
- Radius Property - 'representet' rather than 'represented'
- ToiHorizon Property - 'wich' rather than 'which'

Unless someone would rather fix these directly on master, I can submit a pull request for these fixes. Before doing so, I could also review the rest of the Steering sample for similar typos. It's been a while since I've done anything with Duality - it'd be an easy way to get my feet wet again :grin:

**Comment by ilexp** [comment]
Thanks for reporting! Closing this, since you also already fixed it 🙂
