### ISSUE TITLE
Code-side window resizing gives wrong results

### ISSUE THREAD

**Issue by SirePi** [AdamsLair/duality#621]
### Summary
The client window is not resized correctly when resolution changes are applied via code

Probably a side effect of the latest upgrade to OpenTK's last version, since the behavior was not observed before despite having code that actually resized the game's window.

### How to reproduce
Just programmatically alter the resolution by changing UserData

### Attachments
- log obtained by modifying NativeWindow.cs
`[Core] Msg: Resize > targetSize:{Width=800, Height=650}, ClientSize:{Width=816, Height=639}`
expected:
`[Core] Msg: Resize > targetSize:{Width=800, Height=650}, ClientSize:{Width=800, Height=650}`
- zip file with minimal reproduction situation (press space once the scene starts, it should increase the window size by 50 pixels, but it does not)
[Resizing_Bug.zip](https://github.com/AdamsLair/duality/files/1661390/Resizing_Bug.zip)

**Comment by ilexp** [comment]
This looks like a bug in the [AdamsLair.OpenTK](https://github.com/AdamsLair/opentk/tree/duality-master) dependency (`duality-master` branch) that could have been introduced in one of these recent commits:

- https://github.com/AdamsLair/opentk/commit/4b031b0d99fc2643d411405a02950383a3f183c9
- https://github.com/AdamsLair/opentk/commit/dd9bf5064bf54113092d4cbf106f387a517d8d0e
- https://github.com/AdamsLair/opentk/commit/01ad6065a7fddb412cc7317c52d4c4bda9f14164

I'm currently suspecting [this one](https://github.com/AdamsLair/opentk/commit/4b031b0d99fc2643d411405a02950383a3f183c9), as it also touches window size values. Maybe some code needs to be adjusted to match with the cherry-picked changes.

**Comment by ilexp** [comment]
It seems like [this line](https://github.com/opentk/opentk/commit/950cef3eaedc52c9da7e72c4c7f0716e80e46acf#diff-fac522c2c66d7345997aca3388af37ceL1444) from the original commit was applied [at the wrong place](https://github.com/AdamsLair/opentk/commit/4b031b0d99fc2643d411405a02950383a3f183c9#diff-91da623a0d73d7cad73a1ccc486be45bL1073). @SirePi is currently on a fix for this.

**Comment by ilexp** [comment]
Fixed by @SirePi, binary release in progress. Package update should be available in about 15 minutes.
