### ISSUE TITLE
Introduce a Way to search for a Component before adding it to a GameObject.

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#637]
At the moment is quite annoying when you want to add a new component via the context menu,
especially when you have a "big project structure"...

Here is an example:
![image](https://user-images.githubusercontent.com/6233308/37707780-9c38935e-2d04-11e8-8d4b-51ae8a28e9c0.png)

So it would be nice if you could search for a specific component instead of clicking through the context menu.
Here is an example:
![image](https://user-images.githubusercontent.com/6233308/37707922-1c0b87c6-2d05-11e8-940d-4824c98e451f.png)
_by Unity_

We could reuse this dialog by @BobGneu for this propose.
![image](https://user-images.githubusercontent.com/6233308/37708146-dd16e8e8-2d05-11e8-9044-eaaa7caa4297.png)
 

So what do you say?

**Comment by ilexp** [comment]
Looks like an overdue usability improvement 👍 Let's say we go with the pop-up dialog variant, how would you trigger the dialog?

**Comment by ChristianGreiner** [comment]
One way to trigger the dialog could be a button on the right hand side (red button)?

![image](https://user-images.githubusercontent.com/6233308/37724901-111b34c4-2d32-11e8-8770-0257731090ca.png)

**Comment by mfep** [comment]
Just a little addition: I'd be happy to see that in the *Add new GameObject* context menu as well

**Comment by ilexp** [comment]
> One way to trigger the dialog could be a button on the right hand side (red button)?

Sounds good. We could extend this even further:

- A small (but maybe not red?) button to the top right of the GameObject property editor in the inspector. Not super prominent, but always reachable. Can be implemented in the [GameObjectPropertyEditor](https://github.com/AdamsLair/duality/blob/c260bba93d739cfb25723f8aeb624792bc4a6a80/Source/Plugins/EditorBase/PropertyEditors/GameObjectPropertyEditor.cs).
- A bigger, "faded" button below the last component editor in the inspector. Not always reachable (scrolling), but more prominent than the top right one. Can probably be implemented as a dummy property editor similar to [ResourceImportExportPropertyEditor](https://github.com/AdamsLair/duality/blob/c260bba93d739cfb25723f8aeb624792bc4a6a80/Source/Plugins/EditorBase/PropertyEditors/ResourceImportExportPropertyEditor.cs) and hooked into [GameObjectOverviewPropertyEditor](https://github.com/AdamsLair/duality/blob/c260bba93d739cfb25723f8aeb624792bc4a6a80/Source/Plugins/EditorBase/PropertyEditors/GameObjectOverviewPropertyEditor.cs)
- A context menu item in the Scene View's "New" menu, [right below the "GameObject" item](https://github.com/AdamsLair/duality/blob/c260bba93d739cfb25723f8aeb624792bc4a6a80/Source/Plugins/EditorModules/SceneView/Modules/SceneView.cs#L673-L679), so it'll say "New / GameObject", "New / Component...", followed by a separator and then the dynamically populated list of component types.

Three ways to reach the new dialog should be good enough and fit most situations. As a side note for later implementations, all three will need to account for multi-selection of objects.

**Comment by TheBoJaN** [comment]
Would it not be better to add components to the Project View under a read-only folder similar to the Default one? It would all be neatly organized by namespace and the filter functionality is already there.
Then you could drag a component onto the inspector or an object in the scene view to add it to the selected object.

**Comment by ilexp** [comment]
> Would it not be better to add components to the Project View under a read-only folder similar to the Default one?

Hmm, wouldn't agree in that regard. 

In a way, you have a point - there's already dragdrop from the Project View to Scene and Camera view to create things, so why not just add a folder for component types? However, the Project View currently deals with Resources only, and there is a clarity in that distinction that I think is worth keeping.

**Comment by deanljohnson** [comment]
Is anyone actually working on this? If not I'll start looking into it.

**Comment by ilexp** [comment]
@deanljohnson Nope, this is currently up for grabs. I'll assign you 👍

**Comment by deanljohnson** [comment]
You can see the branch I am working on [here](https://github.com/deanljohnson/duality/tree/add-component-popup).

I've implemented both styles of buttons within the GameObject editing panel:
![image](https://user-images.githubusercontent.com/12946946/39447905-1c0560d4-4c78-11e8-8c1e-e1429001d88f.png)

I haven't figured out yet how to remove the "Actions" header on the bottom button but I'll keep looking into that.

I've implemented this by adding a new option to [ObjectRefSelectionDialog](https://github.com/deanljohnson/duality/blob/352424def59ada3d6e857c36caf003deff024b6b/Source/Editor/DualityEditor/Forms/ObjectRefSelectionDialog.cs#L69) which causes the dialog to select types rather than instances. This is a bit counter to the naming of the dialog, but it was so easy to hijack the dialog for this I went with that. Should we rename ObjectRefSelectionDialog if this implementation sticks?

### ToDo
* Add "New / Component" button to Scene View's "New" menu
* Improve look and feel of "Add Component" button
* Cleanup logic in GameObjectPropertyEditor

What do we think about changing the curButton int property (usage example [here](https://github.com/deanljohnson/duality/blob/352424def59ada3d6e857c36caf003deff024b6b/Source/Plugins/EditorBase/PropertyEditors/GameObjectPropertyEditor.cs#L259-L309)) to being a private enumeration identifying each button? It's not really related to this PR but would be a nice bit of cleanup IMO.

**Comment by ilexp** [comment]
> I've implemented both styles of buttons within the GameObject editing panel:

Awesome 🙂 

> I haven't figured out yet how to remove the "Actions" header on the bottom button but I'll keep looking into that.

Check out the [Hints property](https://github.com/AdamsLair/winforms/blob/7560c8e449232d929cf65cb4297b05f7ee342678/WinForms/PropertyEditing/GroupedPropertyEditor.cs#L189) of PropertyEditor, it has a way of telling its parent editor whether it wants to be displayed with a name, or use the full space for content. Not 100% sure if that's it already, but could be.

> I've implemented this by adding a new option to ObjectRefSelectionDialog which causes the dialog to select types rather than instances.

Nice work 👍 For the gray-ish part, can we rename the `Path` column to `Origin` or something similar, so it works for both resource paths and full type names? Also, check out the [GetTypeCSCodeName](https://github.com/AdamsLair/duality/blob/3e87f326cb5a63bc2f6d0409d528e62067296419/Source/Core/Duality/Utility/ReflectionHelper.cs#L507) extension method, it will give you a string representation that matches what you'd write in C#, and without the assembly name and version.

> Should we rename ObjectRefSelectionDialog if this implementation sticks?

Sounds good, do it. It's a nice general-purpose use case, actually, and the dialog provides common functionality such as filtering and convenient keyboard input. Could be just "that dialog" to select a thing from a list of things.

**Comment by ilexp** [comment]
Done by @deanljohnson and merged back to `master`. Release will follow soon. Closing this.

**Comment by ilexp** [comment]
Release in progress. Should be out there in about 15 minutes.
