### ISSUE TITLE
Investigate and Potentially Fix Clipboard Handling of GameObject References

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#653]
### Summary

While investigating PR #652, I looked through some old editor code that is used when calling `dataObject.SetGameObjectRefs(x)` and it seems that the current setup will clone and serialize the objects when storing them on the Clipboard, rather than storing just their references as documented.

### Analysis

- [SetGameObjectRefs](https://github.com/AdamsLair/duality/blob/012a34282f660f06292590e9b1addb6f8735cab9/Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsDataObject.cs#L123) invokes [SetWrappedData](https://github.com/AdamsLair/duality/blob/012a34282f660f06292590e9b1addb6f8735cab9/Source/Editor/DualityEditor/Utility/Extensions/ExtMethodsDataObject.cs#L22), which packs the objects in a [SerializableWrapper](https://github.com/AdamsLair/duality/blob/012a34282f660f06292590e9b1addb6f8735cab9/Source/Editor/DualityEditor/Utility/SerializableWrapper.cs).
- As long as the `DataObject` is not put in the `Clipboard`, no serialization takes place and the objects are retrieved back as references, as expected.
- However, as soon as storing it on the `Clipboard`, serialization is performed, so new objects will be retrieved back, rather than references to the previous objects.
- Based on the method name and usage, expected behavior would be to always retrieve either references, or no value at all. There are cases where this leads to bugs, for example when using PropertyGrid copy / paste on a GameObject- or Component reference editor, where a detached clone will be pasted, rather than the proper reference.
- Since the `Clipboard` [requires objects to be serializable and does serialize](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.dataobject?view=netframework-4.7.1), simply removing the wrapper may not an option.
- It may be an option to instead put an object ID into the clipboard and keep an in-application lookup to resolve the ID back to the object. This could be done in a type-agnostic way, simply mapping from a randomized `long`, or counting `int` ID to an `object`.

### ToDo

- Double-check usage of both the GameObjectRefs method and similar methods for ComponentRefs and others "Refs" to make sure the API is used as a means of storing references only, rather than cloning.
- Investigate an internal ID lookup as an alternative implementation for reference storage in the clipboard. This should remain an implementation detail of the reference Set / Get extension methods for DataObject that is not visible from the outside.
- Implement if viable, find alternatives otherwise.
- Consider adding `DataObject` extension methods for storing actual serialized object data, rather than references, if that functionality is used anywhere.

**Comment by deanljohnson** [comment]
Existing usages of GetGameObjectRefs, GetComponentRefs, and GetContentRefs are all using these for references and none of them are relying on the way that cloning may happen. Even the way it is used in the current implementation of #652 doesn't rely on the cloning behavior since the copy operation creates clones of object/components anyways.

Given the above, I don't think this is actually causing us any problems at the moment, but it is a gotcha that looms because of the naming of the method.

If we do implement the ID lookup table, do we really need to put every object into it? Wouldn't it suffice that only objects/components/references passed through a DataObject are stored in the table? When they move through a DataObject is the only time they could get inadvertently serialized.

**Comment by ilexp** [comment]
> Existing usages of GetGameObjectRefs, GetComponentRefs, and GetContentRefs are all using these for references and none of them are relying on the way that cloning may happen. Even the way it is used in the current implementation of #652 doesn't rely on the cloning behavior since the copy operation creates clones of object/components anyways.
>
> Given the above, I don't think this is actually causing us any problems at the moment, but it is a gotcha that looms because of the naming of the method.

Sounds good, all clear for the fix then.

> If we do implement the ID lookup table, do you think we would to put all objects in it? Would it suffice that only objects/components/resources passed through a DataObject are stored in the table? When they move through a DataObject is the only time they could get inadvertently serialized.

Yep, I think that last option would suffice, and that's what I had in mind too. We could introduce a "reference list" data into `DataObject` via extension methods, which will internally map the provided enumeration of `object` instances to an ID lookup, which is then used to retrieve instances later on. This ID lookup would need to be static / application global.

Only downside I can see is that we're never safe to remove one of the lookup objects again until the application closes, as we can never be sure thee won't be an occasion where we might need to resolve the reference again. We might reduce the impact of that though by introducing a new `SerializableReferenceWrapper` class (or extending `SerializableWrapper` with an optional flag) that only introduces the lookup entry on serialization, so it only ever triggers when actually using the clipboard, not when using a `DataObject` internally somewhere in the application.

**Comment by deanljohnson** [comment]
I like the Idea of implementing this around SerializableWrapper or a
SerializableReferenceWrapper as serialization is really the culprit, not
DataObject. What I’m not sure about is whether we need to walk the scene
graph of the object and put everything in the table or if we can just take
what is passed into the constructor.

**Comment by ilexp** [comment]
Fixed by @deanljohnson. Closing this.
