### ISSUE TITLE
SpriteIndex is not copied during call to SpriteRenderer.OnCopyDataTo

### ISSUE THREAD

**Issue by raycrasher** [AdamsLair/duality#669]
Simple issue with simple fix. Basically, just adding `target.spriteIndex = this.spriteIndex;` to `SpriteRenderer.OnCopyDataTo` fixes the problem.

Reproduce by duplicating a SpriteRenderer with a non-negative SpriteIndex.

(develop-3.0 branch, b8db412bdbf5da999bab31bc31ab876b7e6b403e)

**Comment by ilexp** [comment]
Nice catch! Merged your PR right away. Thanks! 🙂
