### ISSUE TITLE
Box2DNet with liquidfun

### ISSUE THREAD

**Issue by Jaygem** [AdamsLair/duality#673]
### Summary

I'm actually trying to bring the liquidfun code into the .Net framework (4.5).
I want to know if this work will be usable in this engine. The API would work the same as the Box2D in c++ but with different names.

### Analysis

Adding a fluids in the engine could help bring more gameplay ideas.

**Comment by ilexp** [comment]
Hey there,

for general question, please use [the forum](https://forum.adamslair.net/) or visit us in [the chat](http://chat.adamslair.net) - the issue tracker is intended for the usual bugs, features and dev discussions 🙂 

As for your question, I am not familiar with liquidfun, but assuming it is a demo or library that is built on top of a 2D physics API, it should be possible to make it work on top of Duality as well. While not all physics API is exposed through the engine, the usual force calculation and interaction methods are all there, and if all else fails, it does provide a way to access the underlying Farseer objects as well. Farseer is not Box2D, but it started as a port and is overall very similar.

Closing this - check out forum or chat in case you need more info, or just want to throw around some ideas.
