### ISSUE TITLE
Can't add prefabs to scenes

### ISSUE THREAD

**Issue by gregnk** [AdamsLair/duality#685]
### Summary
Whenever a prefab is dragged into a scene, it does not get added to the scene.

### How to reproduce
Try to add a prefab to a scene.

**Comment by ChristianGreiner** [comment]
@gregnk To add a prefab to a scene, you have to double click on the prefab or drag and drop it into the scene view

**Comment by gregnk** [comment]
@ChristianGreiner Ok, so I was just doing it wrong.

Thanks.
