### ISSUE TITLE
Consider upgrading the C# version

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#698]
### Summary

Currently duality uses C# 4.0. This means we are missing the newer features that C#7.3 brings. Consider upgrading to a newer C# version.

### Analysis

- Will enable us to write cleaner more readable code. For instance C#6 has null propagation. This is a pretty long list of features so its better to actually read up on the newer C# versions than to post them here.
- We would be able to do #600 
- Will make duality incompatbile with older visual studio versions. Only applies to ppl working on the source code itself.
- Even if we don't upgrade .NETstandard will make the solution incompatible with older visual studio versions anyway.

**Comment by Barsonax** [comment]
C# 8.0 among other features will bring nullable references. This is a opt in feature as the new syntax is a breaking change. It is backwards compatible once compiled though. You do need Visual studio 2019 which is currently still in preview.

Even if nullable references are not directly beneficial to duality it is to users that use duality as they can see when returns/parameters etc can be null or not. This will help users write more robust code.

It might be worth looking into once C# 8.0 is stable.

**Comment by ilexp** [comment]
Alright, let's get things started. Is there a feature-by-feature list of changes to C# by language version, as well as minimum required VS toolchain and its release date? If not, can we compile one as a basis for deciding which version to upgrade to?

**Comment by Barsonax** [comment]
From what I know:
VS2015 C#6
VS2017 C#7
VS2019 C#8

Since you need C#8 for nullable references I say we go for C#8. VS2019 is out already and it's stable (and ALOT faster I have to say).

**Comment by Barsonax** [comment]
As a first step I say we just switch all projects to C# 8.0 and get appveyor working with it. After that we can start working on actually using the new features and changing the coding style where needed.

**Comment by ilexp** [comment]
Not new info, but for the record, as I didn't see it mentioned here: We can't upgrade to C# 8.0 yet, as VS 2019 doesn't support building PCL libraries by default and the AppVeyor 2019 image doesn't have the .NET Portable Library Targeting Pack. 

So we can either do the switch to .NET Standard first (#573), or just upgrade to C# 7.3. I've created a [new discussion on the AppVeyor support](https://help.appveyor.com/discussions/problems/24595-visual-studio-2019-image-with-pcl-build-support) in the mean time.

I'll pick this up to upgrade to C# 7.3 and .NET 4.7.2.

**Comment by ilexp** [comment]
## Progress

- Updated all Duality projects using the .NET Framework to 4.7.2
- Updated all Duality projects to use C# 7.3.
- Triggered a binary release and did a quick test. Everything seems to be in order.

## ToDo

- Wait for the VS 2019 issue to be addressed or for the .NET Standard switch, then revisit this issue to consider upgrading to C# 8.0.

**Comment by Barsonax** [comment]
> Updated all Duality projects to use C# 7.3.

#600 is now no longer blocked

**Comment by ilexp** [comment]
> So we can either do the switch to .NET Standard first (#573), or just upgrade to C# 7.3. I've created a new discussion on the AppVeyor support in the mean time.

Discussion was moved to GitHub for further updates. See here: https://github.com/appveyor/ci/issues/3041

**Comment by ilexp** [comment]
According to [this thread](https://social.msdn.microsoft.com/Forums/en-US/ac6168d7-2cba-48d9-9cd1-06dd2b25d064/c-8?forum=csharpgeneral), C# 8.0 will only be available on .NET Core 3.0 and .NET Standard 2.1, but not on .NET Framework. That means further work on this is blocked until we eventually switched to .NET Core, which probably happens even way after the .NET Standard switch.

**Comment by ilexp** [comment]
Because this will probably remain blocked for a bit and we've already done the upgrade to C# 7.3, I've made a new issue for C# 8.0 in #738. Closing this.
