### ISSUE TITLE
Move Forum to new Domain

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#707]
### Summary

After the recent move from `duality.adamslair.net` to `www.duality2d.net` in issue #700, the forum is the only place left on the old domain. Consider moving it to a `duality2d.net` subdomain as well.

### Analysis

- Since the forum was, for the most part, superseded by the chat in active usage, this issue is flagged nice2have for now.
- Moving could be done with an "as-is" approach where the databases and files are copied over to the new space and adjusted internally to match the new domain.
- It could also be done with an entirely new phpbb installation where the old content is imported. However, the forum has custom changes all over the place, so more time might be needed for this than with a move only approach.

**Comment by ilexp** [comment]
Removed the `Nice2Have` label, as the current provider is planning to update the minimum PHP version from 5.6 to 7.0 on the server, which will break the current forum software. There is a rollback in place, which will stay active for the time being, but not indefinitely.

As similar issues could happen on the new provider as well, prefer going with a new installation with imported old content. Also consider using a more modern forum software instead of phpbb.

**Comment by ilexp** [comment]
Links of alternative forum software by @SirePi:

- https://flarum.org/
- https://vanillaforums.com/en/software/

**Comment by mika76** [comment]
https://www.discourse.org/ seems to be quite popular these days...

**Comment by ilexp** [comment]
### Quick status update

The forum is currently the only part of the Duality web infrastructure that is still hosted on my personal webspace, as opposed to being hosted on GitHub with just a thin, domain-only "front". Given the [new core team of maintainers](https://github.com/orgs/AdamsLair/teams/duality-core) and my departure from the project as "the main dev", this is something that I'd like to change sooner or later, to avoid unnecessary dependencies of the project on me personally. 

My current plan is to take the forum offline at some point in the future. It has been mostly inactive for about two years now, with the [chat](https://chat.duality2d.net) superseding its purpose as a community platform, and place for tech and general gamedev support. 

I'd leave it up to the new maintainer crew to decide whether we actually need a forum replacement at some point, but my intuition is that the combo of chat, docs and issues works quite well for now, and also has a very low maintenance overhead.

**Comment by ilexp** [comment]
With all old postings secured [here](https://github.com/AdamsLair/duality-docs/issues/60#issuecomment-636498248), links to it replaced with chat links and a proper redirect active, the old forum is now offline.

**Comment by ilexp** [comment]
Late update: We now have a new forum via the GitHub discussions feature, see [welcome posting here](https://github.com/AdamsLair/duality/discussions/879).
