### ISSUE TITLE
Upgrade Nuget.Core to 2.14

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#711]
### Summary

Duality is still using `Nuget.Core` 2.8.3 which does not understand the newer targetframeworks like netstandard. Consider upgrading to `Nuget.Core` 2.14 which does understand these.

In a small test during #710 I found no breaking changes and I was able to install a package.

### Analysis

- Together with #710 this should make it really easy for duality to start supporting netstandard plugins.

**Comment by ilexp** [comment]
Addressed by @Barsonax. Closing this.
