### ISSUE TITLE
could not copy file NVorbis.XML 

### ISSUE THREAD

**Issue by iplayfast** [AdamsLair/duality#713]
### Summary
Fresh install of monodevelop, fresh install of duality
Compile error is
/home/chris/cs/duality/Source/Core/Duality/Duality.csproj(5,5): Error MSB3030: Could not copy the file "bin/Debug/NVorbis.xml" because it was not found. (MSB3030) (Duality)

I'm a newbie to cs so I'm not sure where this file is created from

**Comment by ilexp** [comment]
Did you restore packages via `nuget restore`? VS does this automatically before build, not sure about MonoDevelop.

Also, what operating system are you on, and which (Mono?) toolchain?

**Comment by Barsonax** [comment]
@iplayfast did you resolve the error using @ilexp suggestion?

**Comment by Barsonax** [comment]
I think we can close this issue.

**Comment by ilexp** [comment]
Closed due to inactivity and missing info.
