### ISSUE TITLE
Unit tests not working in VS2017

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#716]
### Summary

VS2017 is unable to discover the unit tests in duality

### How to reproduce

- Try run a test in VS2017
- It doesnt run any test and prints out 0 run

EDIT: updating to nunit 3.x fixes this issue. This probably might have to do with nunit 2.x being really old and the visual studio test discovery changed somewhere around v15.6 to be roslyn based.

**Comment by ilexp** [comment]
A workaround without code changes is to install the NUnit 2.X test adapter extension into Visual Studio. It seems to no longer be enough to install the adapter package as a dependency of the actual test projects.

**Comment by ilexp** [comment]
Addressed by @Barsonax and me in PR #717. Closing this.
