### ISSUE TITLE
Consider switching to package reference

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#736]
### Summary

Consider migrating all projects to package reference. This is already done with success on my netstandard branch (https://github.com/Barsonax/duality/tree/feature/netstandard_barsonax)

To do this you can either look at my branch for the needed changes or use the migration tool. The latter does a good job of migrating. One thing you do need to do manually is to modify the Copy tasks a bit. Taken from #573:

For this I found a solution since the buildoutput is no longer copied to the build output folder with package reference:

Add GeneratePathProperty="true" on the packagereference: https://github.com/Barsonax/duality/blob/feature/netstandard_barsonax/Source/Core/Duality/Duality.csproj#L11
You can now use $(PkgPackageNameWithUnderscoresInsteadOfDots) to refer to the package path:
https://github.com/Barsonax/duality/blob/feature/netstandard_barsonax/Source/Core/Duality/Duality.csproj#L97

After this is done we also need to update my netstandard branch to solve the conflicts that will arise.

### Analysis

- Needed for our transition to netstandard #573 
- Makes the changes we have to do on the netstandard branch smaller
- Cleaner project structure, with packagereference you don't need a separate package.config anymore than can get out of sync with the csproj.
- Faster restores due to the use of the global nuget packages folder

**Comment by ilexp** [comment]
Addressed in #739. Closing this.
