### ISSUE TITLE
Enable sourcelink

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#746]
### Summary

Sourcelink would enable consumers of duality to debug it like they had the source code. For instance here iam doing just that with [Singularity](https://github.com/Barsonax/Singularity) while its installed in a console app:
![demo](https://user-images.githubusercontent.com/19387223/63719912-4e68b500-c84e-11e9-8f71-fbcb7c31176d.gif)

https://github.com/dotnet/sourcelink

### Analysis

- No more copying over dll's and pdb's just to be able to debug duality source code from another project. Just disable just my code and you are good to go.
- Was easy to setup in a evening for Singularity.

**Comment by ilexp** [comment]
Done by @mdonoughe. Closing this.

**Comment by ilexp** [comment]
Unfortunately we'll have to re-open this as it turns out that SourceLink doesn't work when building packages via AppVeyor CI, rendering the recent addition inactive.

The following messages show up in the [CI build](https://ci.appveyor.com/project/AdamsLairBot/duality/builds/27890377/messages):

> Source control information is not available - the generated source link is empty.
> Unable to locate repository with working directory that contains directory 'C:\projects\duality\Source\Core\Duality'.

@mdonoughe Do you have any idea how this could be addressed?

**Comment by Barsonax** [comment]
Seems to be a hardcoded path?

**Comment by ilexp** [comment]
It's not a path from my machine, if that's what you're wondering - I'd guess it's just the directory where AppVeyor happens to store the project checkout.

**Comment by ilexp** [comment]
Did a bit of research and I'm guessing it could be [this AppVeyor setting](https://github.com/AdamsLair/duality/blob/06b283956db6357d7c9bb01291652c1d49708795/appveyor.yml#L9):

```
# fetch repository as zip archive
shallow_clone: true
```

If there's no git, then of course SourceLink has no way of knowing where to link to. I'll try disabling this on the release branch and see if it helps.

**Comment by ilexp** [comment]
That seems to have done it, the warnings are gone. I've triggered a new binary release that should now have SourceLink support, should be out there in about 30 minutes.
