### ISSUE TITLE
"Auto-Refresh of properties in Sandbox" doesn't work

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#752]
The editor doesn't refresh properties of components, if you start the sandbox mode, even though
its enabled.
After you toggle the option, it works again.

![lul](https://giant.gfycat.com/PreciousBiodegradableHatchetfish.gif)

**Comment by ilexp** [comment]
Looks like a glitch - not sure why, but potentially a small fix. Tagging this for new contributors.

**Comment by ilexp** [comment]
Fixed by @SirePi. Closing this.
