### ISSUE TITLE
visual editor for slicing up textures

### ISSUE THREAD

**Issue by Shadowblitz16** [AdamsLair/duality#772]
### Summary
Please make a visual editor for slicing up pixmaps like in unity.

### Analysis

pros
-makes creating sprite atlas quicker and easier
-more visual

cons
-requires more code making duality bigger 

### Attachments

![image](https://user-images.githubusercontent.com/2453707/77240795-5bad0e80-6ba7-11ea-9063-99160f3c6036.png)

**Comment by deanljohnson** [comment]
We actually already have one - if you right click on a pixmap and select 'Slice Pixmap' you will open the 'Pixmap Slicer' window. You can manually specify sprite rects, resize rects with the mouse, slice with a grid, and automatically slice the pixmap by opacity.

**Comment by Shadowblitz16** [comment]
Awesome thanks
