### ISSUE TITLE
Can't Delete Objects with no name

### ISSUE THREAD

**Issue by Shadowblitz16** [AdamsLair/duality#773]
### Summary
I just tried deleting a asset and it didn't do anything

### How to reproduce
-Rename a asset to "" in the Assets folder
-Try to delete it
-See that its still there

### Workaround
- I can't seem to rename it back so idk

### Attachments

- Logfiles (if available)
[Console.txt](https://github.com/AdamsLair/duality/files/4364545/Console.txt)

- [Screenshots or Screencaps](https://getsharex.com/) (if applicable and useful)
![image](https://user-images.githubusercontent.com/2453707/77240910-c0b53400-6ba8-11ea-8dc1-1f54019c87aa.png)

**Comment by deanljohnson** [comment]
Seems to be only editor side - if you look inside the Data folder with Windows Explorer you will see that the file no longer exists once you delete it.

**Comment by SirePi** [comment]
Should you be allowed to rename a resource to [nothing] in the first place? That fix is quite easy to apply

**Comment by ilexp** [comment]
> Should you be allowed to rename a resource to [nothing] in the first place? That fix is quite easy to apply

Yep, that sounds like it should be prohibited in the first place.

**Comment by Shadowblitz16** [comment]
I agree files should not be re nameable to ""

**Comment by SirePi** [comment]
Fixed in #780
