### ISSUE TITLE
built in code editor

### ISSUE THREAD

**Issue by Shadowblitz16** [AdamsLair/duality#775]
### Summary
A Live C# code editor built into the the editor

### Analysis

A built in code editor would be useful so we don't have to open visual studio and switch tabs all the time
it would have to be fast and have the following..
- search and replace
- syntax highlighting
- auto complete
- suggestion
- linting  

pros
- faster development
- no switching from program to program
- overall feels better

cons
- requires coding
- must be fast or it wouldn't be worth it

**Comment by Barsonax** [comment]
This does sounds like something that can be complex to implement as it would involve quite a bit of UI and whatnot.

Compared to simply using visual studio or vs code its a bit hard to see many benefits from this.

**Comment by Shadowblitz16** [comment]
well it would basically just be a colored text editor with a context menu and a info panel.
alot of it can be done by using reflection to look up member info

the main benefit would be that you don't have to exit the editor to create and edit scripts

**Comment by Barsonax** [comment]
I don't really see the benefit of this but I do see a large investment and maintenance cost. So decided that we are not gonna implement this feature.

There already many tools like vscode or visual studio out there that provide alot of functionality.

**Comment by Shadowblitz16** [comment]
@Barsonax This should be considered to be reopened I currently switched to ubuntu and I haven't gotten a good C# editor to work.
- vs studio doesn't run on linux
- vs code doesn't seem to work at all
- mono develop has odd features and bugs effecting workflow
- other ide's are bloated or slow
- other text editors have same problem that vs code has

**Comment by Barsonax** [comment]
I think you be better off opening a issue at one of the code editors you mentioned.

**Comment by Shadowblitz16** [comment]
I disagree its a major usability issue more over on linux
I don't see what would be so hard about using reflection to build a code editor. there are even reflection libraries that could make it faster then vs studio with the same basic features like linting, code completion and intellisense.

the chance vscode is going to turn their text editor into a ide or monodevelop is going to update and fix it's issues is less likely then someone here implementing a script editor.

like it doesn't have to support multiple files just a single script editor

**Comment by Barsonax** [comment]
Vscode works fine for me. Its a (lightweight) IDE already.

Feel free to build your own IDE though.
