### ISSUE TITLE
Component members are not added in order

### ISSUE THREAD

**Issue by Shadowblitz16** [AdamsLair/duality#777]
### Summary
Component members are not added in the order they are added and declared

### How to reproduce

- Create a component
- Add a few properties to it
- Compile it
- Add it to a game object
- See that the the properties are in a random order
 
### Workaround
- Unknown

### Analysis
- Unknown

### Attachments

![image](https://user-images.githubusercontent.com/2453707/77242444-b51f3880-6bbb-11ea-9369-bd5acab88bab.png)

![image](https://user-images.githubusercontent.com/2453707/77242449-c10afa80-6bbb-11ea-8dfc-8d13733b627d.png)

**Comment by deanljohnson** [comment]
Pretty sure it is alphabetical, not random.

**Comment by ilexp** [comment]
This is a default-on setting in the inspector 🙂 Click the little icon with A and Z and an arrow in it to toggle this. You'll instead get the actual ordering of the properties.
