### ISSUE TITLE
Resources don't seem to be drag and dropable in inspector 

### ISSUE THREAD

**Issue by Shadowblitz16** [AdamsLair/duality#778]
### Summary

Unlike the unity engine resources like pixmap are not assignable in the inspector by dragging and dropping.

### How to reproduce

- make a component script like so..
```
	public class Object : Component
	{
		public Pixmap Texture    { get; set; }
		public uint   Frame      { get; set; }
		public Rect   FrameStart { get; set; }
		public uint   FrameCount { get; set; }

	}
```
- Add it to a object
- Try to drop a pixmap onto the property in the inspector

### Workaround
- Unknown
### Analysis

I would guess its just not added as a feature yet and if thats the case this can be labeled suggestion
### Attachments

- Logfiles (if available)
- [Screenshots or Screencaps](https://getsharex.com/) (if applicable and useful)
![image](https://user-images.githubusercontent.com/2453707/77242532-92d9ea80-6bbc-11ea-8cc8-78fe28e2d762.png)

**Comment by deanljohnson** [comment]
You need to use a `ContentRef` property. You can get more information from the corresponding [docs](https://docs.duality2d.net/pages/v3/Resource.html).

**Comment by ilexp** [comment]
Yep, that should be it! Closing this, as @deanljohnson already gave the right pointers.
