### ISSUE TITLE
Sourcelink not working

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#814]
### Summary

Sourcelink as its implemented now does not work in duality. One missing thing that is needed is that the repository link is included in the nuspec and also the commit hash so that sourcelink knows how to find the source code.

The repository link and hash look entry in the nuspec should look like this (taken from https://www.nuget.org/packages/Singularity/0.17.5):
```
<repository type="git" url="https://github.com/Barsonax/Singularity" commit="033c260d09d006cd4b679aef23e63fae043ced8b" />
```

Instructions can be found here https://github.com/dotnet/sourcelink

There might be more missing. It might be easier to add the required entries and use dotnet pack which should handle things like adding the commit hash to the package.

**Comment by ilexp** [comment]
Wait, didn't that work in the past? What caused it to break?

**Comment by Barsonax** [comment]
idk but iam not seeing this in the nuspecs in the source nor in the nuspecs of the downloaded nuget package from nuget. Haven't tested it in visual studio but without this sourcelink shouldnt be able to figure out the source code because the data is simply not there.

**Comment by Barsonax** [comment]
https://github.com/AdamsLair/duality/pull/758 only added a build.props file. It didnt changed anything about the build itself so how did this ever work?

**Comment by ilexp** [comment]
I believe the required metadata will end up in the `.pdb` files, and which repository is used was pulled dynamically from the git repo that was being built. Maybe I'm imagining things, but I _think_ I have seen this working when looking into the post-PR fix.

**Comment by ilexp** [comment]
Just verified this with a fresh Duality install, works fine. I get the VS popup asking whether I want to download the source code to step into, and then I can do just that.

**Comment by Barsonax** [comment]
Inspected the pdb in the nuget package:
![image](https://user-images.githubusercontent.com/19387223/81326628-67db2580-909a-11ea-9751-c078c0e7d5d2.png)

so ye it seems to end up in the pdb itself.

Now iam wondering why it adds the git metadata in the nuspec with dotnet tooling.

**Comment by Barsonax** [comment]
closing this as it turns out to be working properly
