### ISSUE TITLE
Replace Legacy .zip packaging with the new DualityTemplates .zip packaging

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#831]
### Summary

Right now, the NightlyBuilder will pack a binary `.zip` that will no longer be usable with the v4.0 pre-release. It will show up as a CI artifact and could otherwise confuse any future maintainers or users. This can be fixed by replacing it with the new [DualityTemplates](https://github.com/AdamsLair/duality/tree/f4b7ef531d383725df855618680fcf2c0fd8ee31/Source/DualityTemplates) `.zip` that is generated on build.

### Analysis

- Remove all legacy `.zip` code from NightlyBuilder, e.g. [this block](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Tools/NightlyBuilder/Program.cs#L242-L267), [this block](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Tools/NightlyBuilder/Program.cs#L211-L240) and all [related config variables](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Tools/NightlyBuilder/ConfigFile.cs).
- Remove the legacy [AdditionalFiles](https://github.com/AdamsLair/duality/tree/f4b7ef531d383725df855618680fcf2c0fd8ee31/Build/NightlyBuild/AdditionalFiles) folder and [related](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Build/NightlyBuild/BuildConfig.xml#L13-L14) [config](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Build/NightlyBuild/BuildConfig.xml#L6) [entries](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Build/NightlyBuild/BuildConfig.xml#L17-L76), and [some more](https://github.com/AdamsLair/duality/blob/f4b7ef531d383725df855618680fcf2c0fd8ee31/Build/NightlyBuild/BuildConfig.xml#L12). This will leave the nightly builder with only build, test, `.chm` docs and package steps remaining as-is.
- Update the [CI artifact path](https://github.com/AdamsLair/duality/blob/9d2b47d8e4d2bc43c7043c53a6fe61824f3caed2/appveyor.yml#L40) for the template download `.zip` to point to the new template `.zip` - or adjust the output path of the templates project to match it.

Simplifying NightlyBuilder as outlined above will also make it a little easier to talk about retiring NightlyBuilder altogether because there's less moving parts left to identify for replacement.

**Comment by ilexp** [comment]
Pinging @Barsonax for awareness.

**Comment by Barsonax** [comment]
Will look into this the coming week

**Comment by Barsonax** [comment]
@ilexp I see this comment in the appveyor.yml:
```
# The following lines trigger a complete NuGet Package and Binary Release build.
# They do not attempt to deploy them - it's just a build, made available through artifacts.
# The reason why it's inactive is that releases are in fact a relatively rare thing,
# while AppVeyor runs on each commit. It's probably for the best to not accumulate 6 - 11 MB
# of disk space in the AppVeyor VM on each commit, never to go away because of build history.
```

My understanding is that every build uses a fresh instance of the VM so this should be a non issue for the VM.

After a while appveyor will cleanup old artifacts as wel: https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy

So I think you can just leave that part active.

**Comment by Barsonax** [comment]
Its not meant for archival purposes because they clean it after 6 months :).

I believe the max artifact storage capacity is around 50GB (which in case its not enough they are willing to increase) so we would need alot of builds happening in 6 months to fill this up. Probably still best to just put a branch condition on it (only master/release) but commenting it out shouldn't be necessary.

I never ran into problems with this as most CI's auto clean after a while.
