### ISSUE TITLE
JsonFormatter / Add JSON Serialization Support

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#93]
- Add support for [JSON](http://en.wikipedia.org/wiki/JSON) as alternative to XML.
- Pro:
  - Smaller Resource files
  - Higher data frequency than XML, but still human-readable
  - A good excuse to create a [plugin API for adding custom serialization formats](https://github.com/AdamsLair/duality/issues/94) to Duality
- Con:
  - Need to create said plugin API first in order to keep additional dependencies out of the core
  - Probably won't add that much of value to the user, will still need to be maintained

**Comment by AdamsLair** [comment]
...or maybe use YAML instead?

Also, make sure the unit tests for serialization just use any kind of formatting that is available - whether defined in a plugin or not.

**Comment by ilexp** [comment]
Support for custom Serializers is now part of Duality, see [here](https://github.com/AdamsLair/duality/issues/94). Just define your own one in a Core Plugin, and it'll be a "first-class citizen" for serialization in both core and editor. This enables projects to use their own kind of serialization, as well as multiple distinct Serializers for different purposes - such as a fast binary format without metadata and versioning for non-dev releases of the game or similar.

**Comment by ilexp** [comment]
Closing this, as it has become a non-issue now that custom serialization can be added via plugin.
