### ISSUE TITLE
Plugin API for Custom Serialization Formats

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#94]
* Evolve Duality Serialization to allow adding custom Formatters via CorePlugin
* A good exercise for testing this would be adding a new Serialization format via plugin - like [JSON](https://github.com/AdamsLair/duality/issues/93)
* As long as no-one needs it, this is reeeaaally a nice2have feature. Probably exploring it just out of interest. If there's something urgent, do it first.

**Comment by ilexp** [comment]
Done for v2.0
